### ISSUE TITLE
Lasso effect on top of react virtualized

### ISSUE THREAD

**Issue by asafbe** [bvaughn/react-virtualized#1011]
Hi,

I'm looking for examples on how to create "Lasso" effect (a box for range selection) on top of react virtualized grid. I don't care about the selection itself, a callback for a cell being hovered should be enough.
I know there is a react-selectable out there and also some forks, but none of them actually works well with react virtualized.
any ideas?

Thanks

**Comment by bvaughn** [comment]
Hello! 😄 

For this type of question, I suggest using Stack Overflow with a [#react-virtualized tag](http://stackoverflow.com/questions/tagged/react-virtualized) or asking in the [react-virtualized Slack channel](https://react-virtualized.now.sh). Issues are reserved for bug reports and feature-requests.

This helps keep the project somewhat more maintainable for me _and_ hopefully gets you an answer faster (since more people check those places than monitor GitHub issues). 😄
