### ISSUE TITLE
Grid and MultiGrid makes 2 render passes on simple scroll

### ISSUE THREAD

**Issue by pete-moss** [bvaughn/react-virtualized#1035]
I am using both Grid and MultiGrid and I am noticing that 2 render passes are made when doing a simple scroll by either clicking on the arrow caret in the scrollbar, or by calling Grid.scrollToCell({rowIndex: n}). Doesn't seem right, and since I already see fairly significant delays when scrolling with MultGrid (the rendering of the row/column header Grids lag behind), I am wondering this could be addressed.

**Comment by aem** [comment]
Hi Pete. Can you please provide us with a code example that demonstrates the scrolling delays you're seeing and a verification of the second render pass?

**Comment by wuweiweiwu** [comment]
The latency will probably be solved once I finish migrating `Grid` #1053.

The double render is only observed for `Grid` when the component initially mounts and also on scroll end.

For `Multigrid` you will see a "double" render because at any time, you are scrolling two grids either horizontally or vertically.

**Comment by wuweiweiwu** [comment]
I'll have to double check. This should be in Grid. So I'm going to hold off until the rewrite is done. Which should be in the next week or so

**Comment by HtmlRanger** [comment]
Hi! Any progress on this issue?
