### ISSUE TITLE
Hide/Show rows OR columns with animated transition for Grid mode

### ISSUE THREAD

**Issue by idibidiart** [bvaughn/react-virtualized#104]
Great work!

You asked for suggestions. Here are some :)

1. be able to hide and show (via e.g. Show All) columns after selecting them, with an animated transition

2. not concurrently with the above, be able to do the same with rows

Any thoughts on how to approach that with react-virtualized? 

:)

**Comment by bvaughn** [comment]
Sorry but I'm afraid I don't understand what you mean. "show all" ?

**Comment by idibidiart** [comment]
Ok let's say i have a grid built with react-virtualized. It has 20 columns 10 of which are in currenf view. I select 3 columns and I click Hide on my UI. I want to be able to smoothly animate the hiding of those 3 colums such that the row shrinks width wise as those columns disappear, showing 3 more columns from the portion of the grid that was outside the current view. 

Then i clixk Show All and have the hidden columns reanimate into place taking the row back to its original 
Width

**Comment by idibidiart** [comment]
Show All is another thing on my UI

**Comment by idibidiart** [comment]
I would be responsible for passing in an array of rows or columns to show/hide

**Comment by bvaughn** [comment]
Oh I see! Thank you for elaborating. :)

What you're describing sounds slick! But to be honest... I'm not sure if this type of feature has a place in react-virtualized. I'll admit I haven't given any thought to animation (so there may be a graceful way to do it) but I'm afraid it might complicate things and result in bugs or worsened performance.

In this use-case you describe for instance, react-virtualized would have to have a way of differentiating between the 3 columns you had showing initially and the newly-visible ones. But it doesn't actually know that. The components all just work with collections of anonymous data. (This is often what you want, since an updated number of rows may mean an entirely new source of data has been specified.)

If you have a proposal for how this might be accomplished I'd be happy to review it (as either a PR or a proof-of-concept). :)

**Comment by idibidiart** [comment]
It's more in the realm of industrial strength data grids where you actually can have millions of rows and tens or even hundreds of columns. Some have an adjunct Ui to enable collapsing a whole set of rows (during filtering) as well as hide/show. 

If you have a doc describing how react virtualized works conceptually then myself or others will find it easier to adapt it. Right now it's a black box to me so any kind of description would help ... All the data grids out there suck in terms of their memory management and horrible bugs so i was hoping react virtualized can be a good substrate for an advanced data grid :)

**Comment by bvaughn** [comment]
I'd like to think it's not _that_ much of a black box :)

The `Grid` code is [here](https://github.com/bvaughn/react-virtualized/blob/master/source/Grid/Grid.js) and it uses a few helper methods [here](https://github.com/bvaughn/react-virtualized/blob/master/source/utils.js). Both are heavily commented and should be pretty easy to follow I think. (I spend a lot of time on documentation.) Both also have pretty extensive tests (see [Grid](https://github.com/bvaughn/react-virtualized/blob/master/source/Grid/Grid.test.js) and [utils](https://github.com/bvaughn/react-virtualized/blob/master/source/utils.test.js)) which should hopefully help further clarify intent. Those combined with the [markdown documentation](https://github.com/bvaughn/react-virtualized/tree/master/docs#documentation) I think provide a pretty clear example of how things work. (Although I'm open to suggestions for how to improve the documentation.)

> It's more in the realm of industrial strength data grids where you actually can have millions of rows and tens or even hundreds of columns. Some have an adjunct Ui to enable collapsing a whole set of rows (during filtering) as well as hide/show.

To be clear, react-virtualized supports columns or rows being hidden/shown. That's simply a matter of changing the [visible] columns or rows count and it will update the rendering. The only thing that is _not_ supported (that I don't think belongs in react-virtualized) is the ability to animate the showing/hiding of columns or rows.

**Comment by idibidiart** [comment]
My bad. I have yet to dig into the code. I've only played with the demo and had a glance at the readme :)

So if you are saying that overwriting the list with a new one that has less rows or columns would be ok as react virtualized will just rerender the current view? If so then why couldn't something like CSSTransitionGroup be used to animate the max-width/max-height of React elements being removed/re-added? Basically to have the hide animation run on every element on componentWillUnmount and the show animation on componentWillMount? It sounds like a bad idea but not sure why... I will have to look at the code before I can think up something more intelligent :)

**Comment by bvaughn** [comment]
No problem! That's why I provided you with all of the links. I hope they're helpful :D

> So if you are saying that overwriting the list with a new one that has less rows or columns would be ok as react virtualized will just rerender the current view?

That's correct. The test harness / demo that I linked to you lets you do just this (change the num-rows/num-cols and simulate what your'e describing).

> If so then why couldn't something like CSSTransitionGroup be used to animate the max-width/max-height of React elements being removed/re-added? Basically to have the hide animation run on every element on componentWillUnmount and the show animation on componentWillMount? It sounds like a bad idea but not sure why...

This might be worth putting together a proof of concept and trying out. I'm not sure how this works with React essentially recycling children in the way it does. It might be funky. :)

**Comment by bvaughn** [comment]
@idibidiart,

I'm going to close this issue for now since I'm not planning on actively working on it. (I do this to keep the list of defects from piling up and obscuring important issues.) But we can still continue talking on this ticket and I'll be happy to review prototypes or PRs if you have anything to share.

Cheers :)

**Comment by idibidiart** [comment]
Cool! I am working on stuff related to this and will circle back sometime soon. :)

**Comment by LawJolla** [comment]
Rather than open a new issue, I think my question is related.

I'll preface with "I don't think this can work, but..." 😄 

There's a need for react-virtualized windowing with filter and sorting.  Two well known JQuery libraries, [Isotope](http://isotope.metafizzy.co) and [MixItUp](https://mixitup.kunkalabs.com) effectively use filtering and sorting animations to show users data changes.

I hand rolled a react-virtualized with filtering and sorting.  It works great!  Is it possible to add Isotope style animations to a filter/sort?  It would seem to be that it's at worst not possible and at best difficult because of how React Virtualized windows the content.

Any thoughts or packages I've missed?  Thanks!

**Comment by bvaughn** [comment]
@LawJolla I'd love to know the answer to this, actually! I haven't tried combining animation with react-virtualized components because I haven't yet had a use-case myself. But it is a question that comes up from time to time.

If you're just talking about animating from row X to row Y then I _think_ that should be possible by using an animation frame and passing in a new `scrollTop` prop. However if you're talking about animating things like the MixItUp link does...that's much trickier. In theory, you _could_ do something like that by specifying your own `cellRangeRenderer` and managing the animations yourself, but it might be tricky _and_ you might run into problems that I haven't anticipated.

If you do it, and it works out, I'd love to hear about it. 😁

**Comment by LawJolla** [comment]
Thanks for the input!  I will give it a whirl in the next several weeks and report any positive progress.  This is one of my favorite React libraries, and I'd love to help.  Fingers crossed.

**Comment by bvaughn** [comment]
That's great to hear! And kind of you to say! Thanks :)
