### ISSUE TITLE
Resize column

### ISSUE THREAD

**Issue by hyeminHwang** [bvaughn/react-virtualized#1054]
Are you guys support resizing column?

What I mean,
http://adazzle.github.io/react-data-grid/examples.html#/resizable-cols

**Comment by aem** [comment]
is this something react-virtualized needs to support? or rather, is there a reason this can't be handled in the client's provided component renderer?

**Comment by hyeminHwang** [comment]
I'm trying to make a table by using the react-virtualized. But I need resize column features on my table. Is there anyway to support this feature?

**Comment by bvaughn** [comment]
Resize functionality is not core to virtualization, so it's not something this library will ever support natively.

I have used [react-draggable](https://github.com/mzabriskie/react-draggable) in the past to add resizing columns to a `Grid` and resizing rows to a `List`. I would suggest you look into doing the same.

[Here's a demo of resizable rows with a `List`](https://bvaughn.github.io/forward-js-2017/#/28/1) and [here is the source code](https://github.com/bvaughn/forward-js-2017/blob/master/src/Components/ResizableRowsList.js). I don't have a demo for the resizable columns because it was code I wrote for a company I used to work for.
