### ISSUE TITLE
ScrollTop input to grid fails if the scrollHeight of the Div to be virtualised exceeds 1.5 million. Happens on all browsers except chrome

### ISSUE THREAD

**Issue by scarlettlite** [bvaughn/react-virtualized#1086]
# Reporting a Bug?

Please include either a failing unit test or a simple repro. You can start by forking one of these:
* Code Sandbox:https://codesandbox.io/s/rl5jv04k3q

**Comment by wuweiweiwu** [comment]
#1076 

I was unable to repro on safari/firefox/chrome. Manually setting scrollTop to 15 million causes no errors

**Comment by scarlettlite** [comment]
In sandbox that i created , we should scroll to the top of the div . Instead we scroll beyond that. Please try again

**Comment by illuminist** [comment]
https://codesandbox.io/s/p56k0l9x90 I've reworked the sandbox to focus on the issue.

If set rowHeight to 1000 and rowCount to 1600, scrolling using number input will cause scrolling pass beyond head of div in firefox, but in chrome it will scroll to exactly head of div.

Chrome also has the same issue but can tolerance to much greater number. For me, it's rowHeight 1999, rowCount 8393 when it starts acting weirdly

Browser 
- Chromium Version 69.0.3497.81.
- Firefox 62.0.3

OS: Kubuntu 18.04

**Comment by dreamershl** [comment]
I believe the issue is because of the offset scaling issue. From here https://codesandbox.io/s/rl5jv04k3q you can see, the 90th Div start offset is not accurate any more. But if you try the 10th Div, the scrolling will be right. 

Grid has 2 methods, scrollToPosition &  scrollToCell. The scrollToPosition will directly use the provided scrollTop offset to adjust the scroll bar position. But the scrollToCell has an extra step to calculate the row offset. 

The issue is caused by this extra calculation. Because Grid is using the "ScalingCellSizeAndPositionManager" to calculate the offset. When the scroll height is greater than the 1.5M pixels, it will scale the actual pixel offset as the percentage of the current Grid height (like the pagination). 

**In another words, client can't directly use the actual element pixels as the Grid scrollTop parameter**.   


![image](https://user-images.githubusercontent.com/1271739/50675097-dc293300-1026-11e9-95ac-a330bcfccfba.png)

**Comment by dreamershl** [comment]
To addo, ScalingCellSizeAndPositionManager has methods to convert the pixel offset to the "safe" offset and vice verse, _safeOffsetToOffset & _offsetToSafeOffset. 

These are should be exported for client side.
