### ISSUE TITLE
Performance Degradation in v5.x for VirtualScroll Component

### ISSUE THREAD

**Issue by whatknight** [bvaughn/react-virtualized#109]
In a direct comparison between v5 and v4 versions of the VirtualScroll component in my app I noticed a drop in framerate from and avg of 50fps in v4 to an avg of under 20fps in v5. Has anything changed that would account for this difference?

**Comment by bvaughn** [comment]
I updated `VirtualScroll` and `FlexTable` components to use the `Grid` component internally (where as before, `VirtualScroll` was like a vertical-only implementation of `Grid` - so lots of redundant code). I suppose this change incurs a little more processing since `Grid` cares about vertical _and_ horizontal axes but... I haven't seen any such slowdown like you mentioned in my own testing. (Nor have I heard of it from anyone else yet, although admittedly... version 5 is still pretty new.)

Can you point me at examples or... provide more info somehow?

**Comment by whatknight** [comment]
The degradation appears to be related to my row renderer and Chrome 48 as perf is great when I'm only rendering a string and Safari actually performs _better_ with v5. I'm not sure we have an actionable issue (for react-virtualized) so I'll go ahead and close this issue until I know more. Thanks for the quick follow-up! :100:

**Comment by bvaughn** [comment]
Whew! No problem. Thank you for replying with more info. :)

If you're able to narrow down what's causing the perf issue, let me know. If nothing else, I can add it to a GOTCHAS doc somewhere or something. :)

**Comment by whatknight** [comment]
Actually may have been been a webpack cache issue. The production build didn't have any jank and when I back to dev it was still gone. Thanks again! Sorry to light a fire in the issues. The Gitter looks like it's out of commission.

**Comment by bvaughn** [comment]
No problem. False positives happen. :)
