### ISSUE TITLE
How to use the table

### ISSUE THREAD

**Issue by SelaO** [bvaughn/react-virtualized#1110]
I'm asking here because it looks like most SO questions are ignored and I don't see anything helpful for this in the docs or examples. 

Can you provide a proper, standalone, minimal example on how to use this in my project? 

How are you supposed to import and pass data into it, I don't see any prop for this. 

It would be great if you could provide live examples like this: https://react-table.js.org/#/story/cell-renderers-custom-components

**Comment by matiii** [comment]
Have you checked documentation ? There are basic minimalistic example. In short you have rowGetter property which you define how te get data. In Column you render default string value or  you can just implement cellRenderer property for customization.

https://github.com/bvaughn/react-virtualized/blob/master/docs/Table.md
https://github.com/bvaughn/react-virtualized/blob/master/docs/Column.md

**Comment by wuweiweiwu** [comment]
Thanks @matiii

**Comment by bvaughn** [comment]
As @matiii mentions, there are minimal examples in the docs.

You can also view the source of the demo site in GitHub, if you'd like to see a more elaborate example:
https://github.com/bvaughn/react-virtualized/blob/master/source/Table/Table.example.js

The same is true for all RV components.

In addition to SO, There's also a [public Slack channel](http://react-virtualized-v10.now.sh) you can join if you'd like to chat with other people using RV.

**Comment by pixelass** [comment]
If a "basic minimalistic example" has over 300 LOC and requires numerous custom methods to make it work I wouldn't call it "minimal".

I would really aprechiate better support for this library since it is very complex and not really easy to understand.

The documentation does not really help.


IMHO documentation is not meant to be read but rather to bve used to direct developers to a certain section when a support request has been made.

This is just my humble opinion so please ignore it and feel free to hate me for bringing this up.
