### ISSUE TITLE
Should AutoSizer, WindowScroller, etc. use PureComponent?

### ISSUE THREAD

**Issue by jgoz** [bvaughn/react-virtualized#1128]
It might be worth reconsidering whether it is correct to inherit from `PureComponent` in `AutoSizer`, `WindowScroller`, and other utility components that use render props/children functions. Consider the following contrived example:

```js
class MyComponent extends React.Component {
  state = { count: 0 };

  render() {
    return (<AutoSizer>{this.renderChildren}</AutoSizer>);
  }

  renderChildren = ({ width, height }) => {
    return (
      <div style={{ width, height }}>
        <button onClick={this.increment}>{this.state.count}</button>
      </div>
    );
  };

  increment = () => {
    this.setState(prevState => ({ count: prevState.count + 1 }));
  };
}
```

This will render the component correctly, however, clicking the button will appear to have no effect. 

Since the function reference passed to `AutoSizer`'s `children` prop does not change and there are no other props passed to `AutoSizer`, `PureComponent` will prevent `renderChildren` from being re-invoked with the new state.

This is not an issue if an inline function is passed to `AutoSizer` because the function reference will change every time it is rendered, but that defeats the purpose of using `PureComponent` to begin with. In fact, `PureComponent` might be slightly less efficient for these render prop components because it will have to do a few shallow comparisons before returning `true` from `shouldComponentUpdate`, rather than simply returning `true`.

My recommendation would be to just extend `React.Component` for components like this. It will avoid confusion and have no impact on performance (or maybe even improve performance slightly).

**Comment by wuweiweiwu** [comment]
@jgoz That is a good point.

However, `AutoSizer` is for passing `width` and `height` props to the children components. I don't think it makes sense for other state to require `AutoSizer` to rerender, since it only cares about the height and width. 

I would suggest having a ref to the inner child components and call `forceUpdate` when needed.

**Comment by jgoz** [comment]
@wuweiweiwu Thank you for the response. I'm not sure `forceUpdate` is the right approach, though.

As I mentioned in the original issue, you can get around this behaviour by using an inline function for `children`, rather than a bound function, but it defeats the purpose of using `PureComponent`. In other words, when you use an inline function, `AutoSizer` will _always_ re-render anyway because its props will be different every time its parent renders.

This is the pattern presented in all of the documentation for this component, so clearly that's how the components are intended to be used. My argument is that since render prop components will always re-render when their parents render (with recommended usage), `PureComponent` doesn't make sense and might actually have a negative performance impact. It also causes the issue I pointed out in my example.

**Comment by bvaughn** [comment]
> This is the pattern presented in all of the documentation for this project, so clearly that's how the components are intended to be used.

I understand why this is the impression you've gotten, but actually- the docs are written the way they are for conciseness. I'm trying to emphasize RV's API without things like instance binding that maybe get in the way.

That being said, I agree that extending `PureComponent` is a little controversial. [The front page of the docs does mention this detail](https://github.com/bvaughn/react-virtualized#pure-components), but I'm not positive I've made the right decision here.

**Comment by jgoz** [comment]
@bvaughn 

> I understand why this is the impression you've gotten, but actually- the docs are written the way they are for conciseness. I'm trying to emphasize RV's API without things like instance binding that maybe get in the way.

That's totally fair, apologies for the assumption.

> That being said, I agree that extending PureComponent is a little controversial. The front page of the docs does mention this detail, but I'm not positive I've made the right decision here.

Thank you for pointing out that documentation. I think it absolutely makes sense for `Grid`, `List`, `Table`, etc., to implement `PureComponent` since (for the most part) they are not pass-through components. My only issue is with the utility components whose main function is to pass props to user-provided components, such as `AutoSizer` and `WindowScroller`.

[This issue](https://github.com/reactjs/reactjs.org/pull/700#issuecomment-375525559) presented some of the same arguments I have here, which is that render-prop components should probably not implement `PureComponent`, especially if the props supplied by the render function will usually be a subset of the props rendered by the returned component.

If you're open to a PR on this, I'd be happy to open one.

**Comment by jbarker4682** [comment]
I ran into this exact issue just this week and spent several days tearing my hair out trying to figure out why my code, which had previously been working, suddenly stopped updating...

I am creating a list component that dynamically loads statistical data for the visible rows... the structure is:

`StatsList -> InfiniteLoader -> AutoSizer -> Table`

The StatsList accepts a list of fields via props and then passes that list of fields down to Table...  

Originally, this was all contained within StatsList.render() method, and InfiniteLoader and AutoSizer's children were inline functions... so whenever I updated fields, everything re-rendered and worked perfectly.

But then, per some PR feedback, I reworked these inline functions to be named methods on the class and passed references to InfiniteLoader and AutoSizer via their children props... As @jgoz described above, suddenly everything stopped working... 

Unfortunately, this change was only one of many, so it wasn't immediately apparent to me what broke or why... Based on the doc's, I resorted to calling `forceUpdateGrid()` everywhere, trying to make it work again... sometimes it did and other times it didn't.. it was frustratingly difficult to nail down...

Finally, I realized that in fact, when I called `forceUpdateGrid`, the underlying Table *WAS* re-rendering, however, because `InfiniteLoader` and `AutoSizer` did not, the updated `fields` collection never got re-passed down to Table, so calling `forceUpdateGrid` just caused it to re-render the old data...

**Comment by jgoz** [comment]
I’ve since moved on from `AutoSizer`, but at the time, my solution was what is described in the Readme: passing extra props to `AutoSizer` that should trigger a re-render.

There are good arguments both for and against `PureComponent` here, but now I think these kinds of reusable behaviours should be implemented as Hooks, if possible.
