### ISSUE TITLE
List does not re-render when the parent component rendering.

### ISSUE THREAD

**Issue by bee0060** [bvaughn/react-virtualized#1133]
I think it's a *bug* but not very sure.

I have wrote some sample code in codepen: [here](https://codepen.io/bee0060/pen/GGqxRe). 
(You can try to click any rows and check in the console, I have added some console.log there)

I use `List` component in my component. In `rowRenderer` of `List`, it uses `state` or `props` of my component, when the `state` or `props` changed, my component will be re-rendered, but `List` component does not. 

My expectation is `List` will re-render and display by the new `state` or `props`.

Is it a bug or did I implement in a incorrect way, please?

Thank you very much for support.

**Comment by bee0060** [comment]
I used Table component implemented the simular feature, but it works as my expectation in Table.

**Comment by wuweiweiwu** [comment]
Since the List is implemented using `PureComponent` unless the props to it explicitly change, it will not update. see [this](https://github.com/bvaughn/react-virtualized#pure-components) so I would recommend using [forceUpdateGrid](https://github.com/bvaughn/react-virtualized/blob/master/docs/List.md#forceupdategrid)

**Comment by bee0060** [comment]
Yeah, you are right, it works.
Thank you very much for your reply @wuweiweiwu .
