### ISSUE TITLE
esm output provides wrong import statement

### ISSUE THREAD

**Issue by TrySound** [bvaughn/react-virtualized#1212]
There is in the end unused and not existing import. Seems like generated by mistake
https://unpkg.com/react-virtualized@9.20.1/dist/es/WindowScroller/utils/onScroll.js

```js
import { bpfrpt_proptype_WindowScroller } from '../WindowScroller.js';
```

/cc @brigand

**Comment by brigand** [comment]
Hey, this is expected behavior of [the plugin][1], but since `bpfrpt_proptype_WindowScroller` isn't used anywhere, we'd ideally remove it. However, this requires some form of escape-analysis, which is a bit tricky. Created [an issue][2].

If a quick fix is needed, you can add this line to the file:

```
'no babel-plugin-flow-react-proptypes';
```

[1]: https://github.com/brigand/babel-plugin-flow-react-proptypes
[2]: https://github.com/brigand/babel-plugin-flow-react-proptypes/issues/206

**Comment by remorses** [comment]
I cannot build the package with esbuild because of this issue
```
error: No matching export for import "bpfrpt_proptype_WindowScroller"
    75 │ import { bpfrpt_proptype_WindowScroller } from '../WindowScroller.js';
```

**Comment by YurySolovyov** [comment]
For esbuild, i've redirected imports to umd and it seems to work
```js
const resolveFixup = {
  name: 'resolve-fixup',
  setup(build) {
    build.onResolve({ filter: /react-virtualized/ }, async args => {
      return {
        path: path.resolve('./node_modules/react-virtualized/dist/umd/react-virtualized.js'),
      }
    })
  },
};

esbuild.build({
  plugins: [
    resolveFixup,
    // your plugins
  ],
});
```

**Comment by lucantini** [comment]
@YurySolovyov This is a good patch fix for this issue, but this needs to be resolved in a later release of `react-virtualized`!

**Comment by kitsune7** [comment]
For anyone using Vite v2.3.0 or newer, you can apply the esbuild plugin that @YurySolovyov wrote above by modifying your Vite config to include the following:

```javascript
export default defineConfig({
  optimizeDeps: {
    esbuildOptions: {
      plugins: [resolveFixup]
    }
  }
});
```

**Comment by jasonwilliams** [comment]
wow saw the date this was raised. This is still an issue for us when building with esbuild.

**Comment by intafon** [comment]
Yeh, I worked through several issues I had trying out esbuild and using a lerna monorepo, and after all those were resolved I hit this. Bumping this in hopes it gets attention. :-)

**Comment by jasonwilliams** [comment]
@intafon if you need a quick fix https://github.com/bvaughn/react-virtualized/issues/1212#issuecomment-847759202 solution worked for me.

In terms of this being fixed in general, it's already been fixed and merged but it seems to be stuck on being published. https://github.com/bvaughn/react-virtualized/commit/2e962d8f8aebc22cb1168a8d147bcaa1d27aa326

**Comment by VladBrok** [comment]
It's still an issue in 2023 vite v4.3.8

**Comment by VladBrok** [comment]
![image](https://github.com/bvaughn/react-virtualized/assets/79661007/448836e3-facc-4e8c-a113-b5a150557845)

please fix (((

**Comment by H0JLuk** [comment]
Hotfix for this issue has been resolved above at the comment
[comment](#issuecomment-893591870)

**Comment by abemedia** [comment]
I wrote an esbuild plugin to fix this: https://npmjs.com/package/esbuild-plugin-react-virtualized
