### ISSUE TITLE
Column Resize and Column re-ordering

### ISSUE THREAD

**Issue by pkumar84** [bvaughn/react-virtualized#128]
Not sure, but is nice to support Column Resize and Column re-ordering ?

**Comment by bvaughn** [comment]
Hi @pkumar84,

That seems like something that could potentially be added as a high-order component but I don't expect I'll have the time or energy to do it. If you'd like to put together a PR, I'd be happy to review it though. It _does_ sound like a useful feature- just a complicated one.

I'm going to close this issue now since I don't plan on taking any direct action- but if you decide to pick it up and post a PR, we'll reopen for review. :) And we can always chat about it here even after the issue is closed.

**Comment by shiyang-fei** [comment]
I agree with the author. React virtulized would better to remain as basic as possible to make it extendable. Extra features could be added as plugin. I am actually working on these features. 

If @bvaughn could maintain another repo for all RV plugins, it will be awesome.

**Comment by aashayjoshi** [comment]
Hi @bvaughn and @shiyang-fei 

Any updates on resizable columns.

**Comment by bvaughn** [comment]
I've created a basic demo showing resizable `Table` columns here: https://codesandbox.io/s/j30k46l7xw
