### ISSUE TITLE
CellMeasurer with multiple flexGrow columns - wrong height

### ISSUE THREAD

**Issue by bbenejc** [bvaughn/react-virtualized#1294]
I have a table, where all columns are `flexGrow={1}`. Some of the columns have wrapping content - so I am using CellMeasurer to set their height. Sometimes the height is wrong.

I have created a "simple" repro here: [https://codesandbox.io/s/oow8mxov0y](https://codesandbox.io/s/oow8mxov0y)

It generates two rows - one with wrong height, and second one with correct height.
I have simplified my use case... but I am using a custom rowRenderer and cellRenderer. I am also not including react-virtualized/style.css, but instead using my own. 

I have noticed, that if I set flexGrow to 0, then it works. Not sure if it is the only reason.

**Comment by EricTheRed-VT** [comment]
Hey @bbenejc, not sure if this will help you at this point, but I had the same issue and found the solution, and I imagine other people have or will come across it.

### How do I fix this?
You have to pass a style object to the node being wrapped in CellMeasurer, with a value for the fixed axis. 
i.e. if you have a fixed width for a column, you need to pass something like `style={{width: 40}}`. If you were using a fixed height, it would be like `style={{height: 40}}`.

So the cellRenderer code from your repro would look like:
```
    return (
      <CellMeasurer
        cache={this._cache}
        columnIndex={columnIndex}
        key={`${rowIndex}-${columnIndex}`}
        parent={parent}
        rowIndex={rowIndex}
      >
        <div
           className={css.td}
           style={{width: columnData.width /* or some other way to derive this value */}}
         >{cellData}</div>
      </CellMeasurer>
    );
```

### Why is this fix necessary?
You have to pass this as an inline style, and not through CSS, because the CellMeasurer grabs the value directly off the DOM node. As a point of interest: before I worked this out I was seeing (random?) column widths during the "false" render when the values are calculated that had nothing to do with my CSS or Column width props.

I couldn't find a mention anywhere that inline styling is required for proper measuring, and only one example in the docs explicitly passes a style value like this. @wuweiweiwu or @bvaughn, could someone add this to the CellMeasurer documentation? If you prefer I could send a pull request, but you are probably able to word it better.

**Comment by EricTheRed-VT** [comment]
@keann's recommendation (https://github.com/bvaughn/react-virtualized/issues/1174) of recalculating the measurement should fix the underlying issue.
