### ISSUE TITLE
Masonry Scroll To Position

### ISSUE THREAD

**Issue by VikrantShirvankar** [bvaughn/react-virtualized#1311]
How to implement scroll to position in masonry?
This feature is available in List component.

**Comment by remy-poirier** [comment]
Hi, did you find a solution to do so ? 
I wanna scroll to a specific position also, I am trying to do so via native js but it's a real pain, so I am wondering if there is a solution included in the library ?

**Comment by VikrantShirvankar** [comment]
No. I didn't found any solution.
Actually i have opened another ticket related to same problem. I tried many solutions but main issue is re-rendering of list when props get updated.
#1328

**Comment by remy-poirier** [comment]
Ah ok I see, in my case, the `Grid` component did the job and I find this component much documented and flexible (I could scrollToPosition with no trouble and adapted the view in responsive).
I hope you will find a solution soon

**Comment by neemanjabu** [comment]
Hi,
there is way to do it, but it is not a nice one since you have to deal with private property. 
Just save the reference to the Masonry component and update the scroll position by settings the scrollTop property of the masonry container.

Saving reference
`setRef = (ref) => {this.masonryRef = ref};`
`<Masonry ref={setRef} ...`

Set scroll postion
`masonryRef._scrollingContainer.scrollTop = 0`

Working example: https://codesandbox.io/s/react-virtualized-image-measurer-krfqr
