### ISSUE TITLE
custom css

### ISSUE THREAD

**Issue by lienict** [bvaughn/react-virtualized#1362]
i using List, AutoSizer and CellMeasurer to create a list.
when i set border to row and margin

, margin is not working
how can i fix?
![Capture](https://user-images.githubusercontent.com/42538719/56404883-7be79580-6293-11e9-84b8-fa2454f76129.PNG)

**Comment by leak4mk0** [comment]
Hello,
I have encountered this problem, too.
I use this module and `react-bootstrap` module and create long list by `ListGroup`.
However, list separator become bold (2px) because of margin.
https://codesandbox.io/s/react-virtualized-bootstrap-list-group-p92ss

So, I thought a workaround.
We need to consider margin of bottom element is different from margin of other elements.
https://codesandbox.io/s/react-virtualized-bootstrap-list-group-workaround-l90xg

But, this method is not smart.
(margin size is hard coded, style is rewritten...)
Does anyone have any good idea?

**Comment by NodeMirai** [comment]
I have the same problem
