### ISSUE TITLE
How to autofit the columns in FlexTable?

### ISSUE THREAD

**Issue by cheahkhing** [bvaughn/react-virtualized#142]
hi, i notice there is ColumnSizer for Grid, but how about FlexTable?
Basically I'll need a table with autofit the width whenever resized.
That includes all the child columns inside. It will save the efforts need to explicitly set width for each individual children. Is this possible?

**Comment by Guria** [comment]
@cheahkhing Have you tried Autosizer to automatically update FlexTable width?

**Comment by bvaughn** [comment]
This behavior is already supported by `FlexTable` since its columns accept not only a `width` but `flexShrink` and `flexGrow` properties. (Check out [the docs](https://github.com/bvaughn/react-virtualized/blob/master/docs/FlexColumn.md).)

The only thing left is to auto-size the table itself, which as @Guria points out can be done with `AutoSizer` as is done in the [demo](https://bvaughn.github.io/react-virtualized/?component=FlextTable) ([source code](https://github.com/bvaughn/react-virtualized/blob/master/source/VirtualScroll/VirtualScroll.example.js)).
