### ISSUE TITLE
Spike for supporting arbitrary / dynamic heights

### ISSUE THREAD

**Issue by bvaughn** [bvaughn/react-virtualized#149]
**Note**: This issue is a place for me to keep notes about an idea I have that I hope to eventually have enough time to focus on implementing.

All react-virtualized components currently require their cells to have explicit widths and heights. These dimensions can change from cell to cell but they must be known ahead of time in order for the windowing algorithms to determine which cells, and how many, to display. I think it might be possible to _not_ require this information ahead of time and instead just use a fixed width and height (representative of an "average" cell) to do the initial, rough layout. Then as a cell is brought into view, its rough dimensions could be replaced with real dimensions and the overall grid-size could be adjusted slightly as necessary.

Because react-virtualized allows programmatically jumping directly to an item- it's possible that _real_ cell measurements might be sparse within the overall tree but I think this approach may still work. This would enable cells with dimensions that are determined at runtime based on things like the amount of space required to display a string of text. It has a potential downside that the scrollbar may grow/shrink unexpected as a user scrolls if the _real_ cell sizes are vastly different than the "average" sizes used for initial layout. It also has potential performance implications.

**Comment by wmertens** [comment]
Came here to request this exact feature. I think some min- and maxHeight would be useful too, or is that something for the CSS of the individual rows?

I was thinking that when mounting a row, it could simply give it absolute positioning and the fixed width, and on its componentDidMount you measure and adjust the actual height. Since the row is absolutely positioned it is happy about being moved around when something above it changes its height, without causing the browser to recalc. I suppose that was what you have in mind?

**Comment by bvaughn** [comment]
More or less. But a lot of care would/will need to be taken to ensure that performance didn't suffer with this feature. I'm currently working (in a branch) on some optimization aimed at reducing the number of render calls and potentially caching grid cells. Those may help.

This feature is a big lift though. Not sure when I will find the time to get to it.

**Comment by oyeanuj** [comment]
Since this is my pet request, I will add in some points of discussion that we had in our Discord conversations. 

One approach to minimize performance impact on load could be to ask for a `startingNumberOfRows` that you keep in view regardless of height and once those are loaded, start calculating based on height. That parameter could also double up as minimumNumberOfRows which is what you can show if someone sets it. 

I imagine you'd need a function which on scroll would keep making height calculation to see if rows loaded are within the viewport height? 

The more I think of it, it seems like it is probably best to start this off for a simple component that performs the most basic case of lazy loading as that will avoid the complications that come with going directly to a component, etc. (although I am not sure if that diverges from the goal of the library..)

**Comment by bvaughn** [comment]
I was thinking more along the lines of the `estimatedItemSize` property of the iOS [`UICollectionViewFlowLayout `](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UICollectionViewFlowLayout_class/):

> Providing an estimated cell size can improve the performance of the collection view when the cells adjust their size dynamically. Specifying an estimate value lets the collection view defer some of the calculations needed to determine the actual size of its content. Specifically, cells that are not onscreen are assumed to be the estimated height.

Scrolling directly to an item _does_ complicate things as you say but it's one of the primary features of this library so I don't want to drop it.

**Comment by kof** [comment]
http://facebook.github.io/fixed-data-table/ offers this feature, any body looked into that how they do it?

**Comment by bvaughn** [comment]
fixed-data-table doesn't support other properties that react-virtualized does (like programmatically scrolling a cell within view) so their use case is probably easier than mine. But no, I haven't looked too closely at their implementation in a couple of months.

**Comment by kof** [comment]
They didn't commit anything since 5 months, I am not sure it is maintained, but maybe, just maybe, they have good ideas regarding this particular thing.

**Comment by bvaughn** [comment]
I didn't mean to suggest they didn't. But this project is only maintained by me in my free time so I just haven't had the bandwidth to really bite this size of a feature off yet. Not sure when I will.

**Comment by kof** [comment]
Can we access this things currently?
1. get the rows that currently in the window
1. get the speed of current scrolling
1. update them with new height/width values

If yes I could do the following:
1. If speed is higher than X, return  some fixed height/width
2. once speed gets slow enough, start calculating sizes and update it with new sizes
3. when speed is real high, we could even avoid rerendering at all, its a trick but with really high speed nobody will see the difference anyways.

**Comment by bvaughn** [comment]
> 1: get the rows that are currently in the window

This is possible via the [`onSectionRendered` callback](https://github.com/bvaughn/react-virtualized/blob/master/docs/Grid.md) for `Grid` (or `onRowsRendered` if you're using `VirtualScroll` or `FlexTable`).

> 2: get the speed of current scrolling

No, this information is not available although you could certainly implement it with a HOC using the [`onScroll` callback](https://github.com/bvaughn/react-virtualized/blob/master/docs/Grid.md). A HOC to look at for ideas on doing this would be [`ScrollSync`](https://github.com/bvaughn/react-virtualized/blob/master/docs/ScrollSync.md).

> 3: update them with new height/width values

The problem is determining which cells are visible based on the current scroll position. Unless you assume a fixed size for all cells, you can know which ones are visible for a given offset without knowing the sizes of all cells before that offset.

This ticket is basically for me to keep track of ideas regarding efficient ways to compute (and estimate) the sizes of the cells before- given that a user might jump to the middle or end of a virtualized component.

**Comment by kof** [comment]
> The problem is determining which cells are visible based on the current scroll position. 

Maybe we don't need to know if it is really visible, we can calc heights for all rows in the window. We just need to keep window not too big, because otherwise there will be a bigger overhead.

I am  not sure how visible would be the flickr, because rows will be already rendered with some fixed height and then once we know the real height, rows gets resized.

**Comment by bvaughn** [comment]
> Maybe we don't need to know if it is really visible, we can calc heights for all rows in the window. We just need to keep window not too big, because otherwise there will be a bigger overhead.

This would require rendering _all_ of the cells which would defeat the purpose of the windowing approach.

**Comment by kof** [comment]
Why all, we have a fixed amount of rows we render in the window, which is based on the initial row height, right?

**Comment by bvaughn** [comment]
We're misunderstanding each other somewhere. I think you're over-simplifying this a bit, but I think continued discussion of it via the GH issue probably isn't going to be as effective as just chatting. Feel free to hop on the Gitter room if you'd like to talk about it more. :)

**Comment by wasd171** [comment]
Just saying that I would also really like to have such feature implemented! So much data with approximate height(s) need to be rendered efficiently

**Comment by bvaughn** [comment]
Hoping this makes its way into version 7. Myself and @kof are working on it from different angles.

**Comment by bvaughn** [comment]
This feature was introduced (in a limited way) via the version 7 `CellMeasurer` component.

This component could be improved significantly~ something I'd welcome contributions from others on~ but the basic functionality exists now, so I'm going to close out this issue.

**Comment by cephirothdy2j** [comment]
Hi, can the `CellMeasurer` component be used in a `Table`? If not, is that support anywhere on the roadmap? Thanks!

**Comment by bvaughn** [comment]
No. Unfortunately `Table` and `CellMeasurer` can't be used together. (And support is not on the roadmap.)

**Comment by cephirothdy2j** [comment]
Thanks for the quick reply. With that in mind, is there a way using this plugin to reap the benefit of sticky table headers *without* virtual scroll? Meaning, all row heights are calculated and rendered in the DOM?

My use case is similar to ones posted by others, where my row height simply cannot be calculated without retrieving data from the server first and rendering via Markdown.

Note that I am using this plugin as intended in other use cases within the project, and I've invested some time in formatting data to fit this plugin, so I'm invested in using it for the use case described above if I can.

Fantastic work, by the way. The virtualized table has been a performance lifesaver in my other use cases.

**Comment by bvaughn** [comment]
Thanks 😄

Hm. I have not yet needed to use `CellMeasurer` in a production app. I created it for others but I haven't had a use-case for it myself so I'm a bit of a disadvantage offering advice about edge-cases usage. I think it might be possible to combine the 2 but you would likely need to wrap `CellMeasurer`'s `getHeight` function with your own function that set some boundaries.

I have heard a couple of other people say they use react-virtualized with [react-measure](https://github.com/souporserious/react-measure) instead of `CellMeasurer`. I haven't tried this myself, either, but maybe it would be worth looking into.

**Comment by john-osullivan** [comment]
Hi, @bvaughn !  I've been looking into using react-virtualized's Collection component for a while but was unsure it was possible because of an issue like this.  Our usecase is laying out a set of nodes which can be either opened or closed -- opened nodes are wider and stacked in a column on the right.  A picture is worth a thousand words:

![image](https://user-images.githubusercontent.com/3820981/27575400-a7e6ee7a-5ae7-11e7-8669-1816c326be08.png)

The key issue is that the column widths aren't identical (so the magical Masonry component doesn't work) and the height of each node can change.  As the layout is responsive, the height and width won't be known until things are mounted to the page.  Any recommendations on how I'd set up the positions and row/column indexing for a case like this?

**Comment by bvaughn** [comment]
@john-osullivan I'm not sure of a good way to achieve the kind of flowing/responsive layout you're describing within RV at the moment.

**Comment by john-osullivan** [comment]
Bummer.  I'll leave a comment if I come up with a smooth system that can be contributed back to the library!

**Comment by bvaughn** [comment]
👍 That would be great @john-osullivan !
