### ISSUE TITLE
Grid.scrollToCell/scrollToRow does not scroll to a proper location on a very large list

### ISSUE THREAD

**Issue by goroskob** [bvaughn/react-virtualized#1537]
I have a really large lists (often over 1 billion entries) which I display with react-virtualized. Rows height is static. Besides preformance/memory issue fixed with [this](https://github.com/bvaughn/react-virtualized/pull/1343) pull request, I have an issue with scrollToCell accuracy.
When I use scrollToRow prop or Grid.scrollToCell instance method, it does not scroll to a correct location. In a Codesandbox example it jumps to row 100,022 instead of 100,000 and to 999,976 instead of 1,000,000.

Reproduction example is here
https://codesandbox.io/s/pedantic-galois-jop78?file=/src/App.js

**Comment by colleen1414** [comment]
I think I may be having a similar issue. When setting the scrollToIndex for a Table it sometimes jumps to an index 10-20 items from the intended entry. After reading through the source code it seemed it might be from miscomputing the offset in getUpdatedOffsetForIndex in CellSizeAndPositionManager because in my case the currentOffset is not correct and it causes the computed idealOffset to be incorrect

**Comment by ibarrae** [comment]
I jumped into the same issue today, is there any news about this issue?
