### ISSUE TITLE
All items re-mount on list change

### ISSUE THREAD

**Issue by yingfangdu** [bvaughn/react-virtualized#1621]
### What is the expected behavior?
Whenever a item has a data change, all nodes from this List will get unmount and remount.
I can see that from the latest version 9.22.2.

Here is the reproduce step:
1. open this link https://diogofcunha.github.io/react-virtualized-tree/#/examples/filterable
2. click one check box.
3. inspect the element from the developer tool. 
4. the DOM elements are recreated.

And I find react-window has a similar issue reported. https://github.com/bvaughn/react-window/issues/413

This issue cause bad bugs in accessibility to access a node as the tree always recreate all its nodes and it cannot focus on one node.

It would be great that DOM elements are not re-created and only update the changed attributes.

**Comment by jasonLaster** [comment]
Hi @yingfangdu, I just created a [replay](https://replay.io/view?id=90abedec-aa52-469a-8d4f-1bed4d77b35c) while looking into reproducing the problem. 

Could you confirm that I reproduced it correctly and let me know where in the code you're seeing the unmount? I think it is in the row renderer, but I could easily be off.

**Comment by richburdon** [comment]
@yingfangdu I'm seeing the same issue:

I have created a custom header that contains a <select> control which is used to set-up a filter. The select popup closes whenever the table is updated (because everything is unmounted). Note: this happens even if zero rows are rendered and NONE of the Table properties are modified, but when the container properties are updated.
