### ISSUE TITLE
Support for variable height?

### ISSUE THREAD

**Issue by pke** [bvaughn/react-virtualized#171]
My list is located in a container that is relatively positioned 300px from the top. 
The user is able to pull the container up to see more items. 

I fill the container with all the items I have now, but already with 20 items its kind of slow to fill the list. So I wanted to try out a virtual list. However due to the nature of the container described above, I cannot give the list a height in px.

Any idea if that component would work with variable height containers?

**Comment by bvaughn** [comment]
Hey @pke,

What you're describing is the reason I wrote the `AutoSizer` HOC. Check it out ([docs](https://github.com/bvaughn/react-virtualized/blob/master/docs/AutoSizer.md), [demo](https://bvaughn.github.io/react-virtualized/?component=AutoSizer)).

All you need to do is wrap it around your react-virtualized list/table/grid/whatever and it tells you the correct width and height to pass down.

Going to close this issue since it's just a question and not very actionable on my part but we can keep talking here if you have more questions. :)

**Comment by pke** [comment]
Thanks for the quick reply. Will check it out.

**Comment by bvaughn** [comment]
No problem. Hope it works for you- but reach out to me again if it doesn't. Happy to help.
