### ISSUE TITLE
Adding Custom CSS

### ISSUE THREAD

**Issue by Pszek** [bvaughn/react-virtualized#178]
I tried to append custom CSS styles for grid cell like this:

```JSX
<VirtualScroll
  className={styles.VirtualScroll__row}
  ...
/>
```
According to docs it should be responsible for style of single row. Unfortunately class I added is being appended to the main VirtualScroll component:

<img width="740" alt="screen shot 2016-04-06 at 10 50 00" src="https://cloud.githubusercontent.com/assets/10253750/14311031/9cecc6d2-fbe5-11e5-9129-a06fea5cc583.png">

The styles are appended correctly, but to the wrong element. Also tried to replace "VirtualScroll__row" with "Grid_cell", but to no avail

**Comment by Guria** [comment]
@Pszek there is no such statement in docs:
```
className	String		CSS class name
```
It means exactly as it works. Additional class name to use on VirtualScroll.

Docs have [list of classnames used internally](https://github.com/bvaughn/react-virtualized/blob/master/docs/VirtualScroll.md#class-names) that you can use in styling:
```js
<VirtualScroll
  className="MyVScroll"
  ...
/>
```
```css
.MyVScroll .VirtualScroll__row {
  border-top: 1px solid #d8d8d8;
  background-color: blue;
}
```

**Comment by bvaughn** [comment]
Thanks @Guria.

@Pszek he's right. The `VirtualScroll` component only accepts a custom class name for itself (the outer component) because each row is rendered by the user- so I figured you could just add whatever class names you wanted directly to the row you rendered. `FlexTable` offers more class name overrides but that's because a lot of the elements it renders (eg. header row, body row) are out of your control. There would be no other way to customize them.

Ultimately as @Guria mentions you can also customize by overriding the global default default styles.

In this case though I think the best/easiest thing to do is just to attach your row-style onto the element your `rowRenderer` returns. Something like...

```js
function rowRenderer (index) {
  return (
    <div className={styles.VirtualScroll__row}>
      {list[index] /* or whatever your content is */}
    </div>
  )
}
```

**Comment by bvaughn** [comment]
Going to close this question since I think it's been adequately answered- but I'll still see responses so if anything is unclear, feel free to ask. :)

**Comment by Pszek** [comment]
Thank you for feedback. 

I hoped that there is an option to set cell's outer frame bottom-border (renered element has overflow set to hidden so the border is not visible). I can omit this problem by setting border-top instead, yet I couldn't find a way to disable it for the first child rendered. 

But now solved it by using inline-styling and index parameter.

**Comment by bvaughn** [comment]
Oh! I see. That's a fair point. Maybe I'll add a new prop in the next release. :)

Glad you've found an acceptable solution for now though.
