### ISSUE TITLE
unused import bpfrpt_proptype_WindowScroller causing issue in Vite

### ISSUE THREAD

**Issue by reuben-gomesBP** [bvaughn/react-virtualized#1849]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-virtualized@9.22.5` for the project I'm working on.

on vite this unused import seems to be throwing a build issue 

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-virtualized/dist/es/WindowScroller/utils/onScroll.js b/node_modules/react-virtualized/dist/es/WindowScroller/utils/onScroll.js
index d00f0f1..c8496e8 100644
--- a/node_modules/react-virtualized/dist/es/WindowScroller/utils/onScroll.js
+++ b/node_modules/react-virtualized/dist/es/WindowScroller/utils/onScroll.js
@@ -71,4 +71,3 @@ export function unregisterScrollListener(component, element) {
     }
   }
 }
\ No newline at end of file
-import { bpfrpt_proptype_WindowScroller } from "../WindowScroller.js";
\ No newline at end of file
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by lxlyjss** [comment]
Me too!

**Comment by ysmood** [comment]
Does older version of `react-virtualized` not having this issue?

**Comment by reuben-gomesBP** [comment]
i haven't been able to try with an older version 

the issue mainly showed up when migrated to ViteJS

**Comment by rehangit** [comment]
It is coming from es build of react-virtualized@9.22.5

![image](https://github.com/user-attachments/assets/a89cfe60-dd35-4910-a355-8b2fb67670e8)

Causing problems for projects that have deep dependency on react-virtualized. Patching using `patch-project` doesn't really work in npm workspaces due to hoisting and other complications. Can this be prioritised to be fixed.

**Comment by rehangit** [comment]
1. How come we are seeing the 9.22.**5** in dependencies when it does not even exist? The latest version shown 9.22.**4**
2. Can someone explain what [this commit](https://github.com/bvaughn/react-virtualized/commit/2ef636783ea93f8196040f5c3f09bd4f304f316b#diff-12770653bcfc9ed10499741257e70e6d9c072a3ee7693b63586311700176f99fR2) achieved? Because it seems to be the root cause of this error

**Comment by mormoassaf** [comment]
I also used pnpm patch, you just run pnpm patch react-virtualized, then it will create a patch folder where you can fix it, then just commit and it will create a patch file for you after. Other option is to find a version that works and modify the package.json and make your own npm package with this patch.

**Comment by grahamhency** [comment]
`patch-package` totally works for this, but I wanted to throw an alternative out there in case people don't want to use that. 

In your `package.json`:
```json
{
  "postinstall": "npx replace-in-files-cli --string=\"import { bpfrpt_proptype_WindowScroller } from '../WindowScroller.js';\" --replacement='' node_modules/react-virtualized/dist/es/WindowScroller/utils/onScroll.js",
}
```

Then `npm i` and you're good to go.

**Comment by sebbean** [comment]
@grahamhency bless you

i noticed for me the import was actually using double quotes so the match didnt work

here's my fixed one
```
    "postinstall": "npx replace-in-files-cli --string=\"import { bpfrpt_proptype_WindowScroller } from \"../WindowScroller.js\";\" --replacement='' node_modules/react-virtualized/dist/es/WindowScroller/utils/onScroll.js"
```

**Comment by fregante** [comment]
@bvaughn this is still an issue. It would be great to see this line removed.
