### ISSUE TITLE
Grid to Infinite Scroll

### ISSUE THREAD

**Issue by miguelvalerio** [bvaughn/react-virtualized#191]
Hello.

Currently, I have the following structure in one of my components:

``` html
<ScrollSync>
    <AutoSizer>
        <ColumnSizer>
            <div>
                <Grid/>
                <Grid/>
            </div>
        </ColumnSizer>
    </AutoSizer>
</ScrollSync>
```

In this setup, the 1st Grid is a simple 1 row Grid that acts as a header, and the 2nd Grid displays tabular data. However, the amount of data that the 2nd Grid has to render is increasing, and I would like to know if it is possible to apply an InfiniteLoader to the 2nd Grid.

**Comment by bvaughn** [comment]
Hm. Good question.  The current [`InfiniteLoader` interface](https://github.com/bvaughn/react-virtualized/blob/master/docs/InfiniteLoader.md) was written with vertical windowing (eg. `FlexTable`, `VirtualScroll`) in mind and so it only mentions a single index (row index by name, but you could also use it for horizontal windowing I suppose- just not in both directions).

You could use this with a `Grid` but you'd have to essentially pick which axis you wanted to just-in-time load data for. (Maybe this is an easy choice for you, if your data tends to have more rows than columns for example. Let me know if this is the case?)

It would be possible to write a similar HOC that managed just-in-time loading of data for both axes of a `Grid` but the state management would be more complicated than the current `InfiniteLoader`. I don't have a need for such a component at the moment so it's not really on my roadmap.

**Comment by miguelvalerio** [comment]
Yes, in this use case all I'm interested in is asynchronously loading the rows.

**Comment by bvaughn** [comment]
Great! In that event then the `InfiniteLoader` component should work well for you. Here's an [example](https://github.com/bvaughn/react-virtualized/blob/master/source/InfiniteLoader/InfiniteLoader.example.js) I put together showing how it can be used. Should be able to swap the `VirtualScroll` for a `Grid` pretty easily if you don't care about just-in-time loading columns. :)

Going to close this issue since it seems like there's no action required on my part but feel free to ask more questions if you have them, here or on Gitter.

**Comment by Pedrozena** [comment]
Hi! 
I was wondering if there's an update on this. I need to show a grid of 5Milions rows x 5Milions cols, so the InfiniteLoader won't work in any direction
