### ISSUE TITLE
ScrollSync disables scroll depending on cursor target

### ISSUE THREAD

**Issue by kxcrl** [bvaughn/react-virtualized#196]
First, thank you very much for this project!

This is happening not just in my particular implementation of ScrollSync, but on the main github page for this repo as well (https://bvaughn.github.io/react-virtualized/)

To test, go to the ScrollSync page (on the github page for this repo), hover your cursor over the R0, C0 cell (or any cell in the C0 column, really), and attempt to scroll via mousewheel or touchpad. If this isn't just a bug for me, nothing will happen.

Tested in the latest chrome and latest firefox, on both Linux and Mac.

If it works fine for you, feel free to close this issue and I'll troubleshoot my current linux/osx setup.

**Comment by kxcrl** [comment]
Of course, 5 minutes after opening this, I may have solved it on my own anyway.

Looks like my issue is with my code, but the main github page is just because the C0 column is set to have `overflow: hidden` in the styles. I'll leave it to whoever sees this first on whether they want to just close this issue or actually suggest a strategy for handling that. At least right now, I'm just planning to add in a `mouseWheel` even listener to the component and pass the `onScroll` callback to it (right now it's only passed into the main grid area).

**Comment by bvaughn** [comment]
Hey @kxcrl. Thanks. :)

I actually intentionally disabled scrolling in the far left and top (fixed) grids although I can totally understand why you may think of it is as a bug. It's not an attribute of the `ScrollSync` component though- just the way I chose to use it (aka my CSS) in the example file as you've probably noticed. `ScrollSync` itself doesn't disable anything (or set any properties of its children). It just provides a couple of parameters to the child function and lets you use them however you want.

So...back to my example harness. I disabled scrolling in the top and left areas because the browser scrollbar makes them look a little ugly. Especially in the top row, the scrollbar covers over 1/3 of the row.

That being said, you can go the route of _hiding_ the scrollbar for those fixed elements if you'd like. So something like...

```css
.LeftSideGrid {
  overflow-x: hidden !important;
}
.HeaderGrid {
  overflow-y: hidden !important;
}
.LeftSideGrid::-webkit-scrollbar,
.HeaderGrid::-webkit-scrollbar {
  display: none;
}
```

**Comment by bvaughn** [comment]
> At least right now, I'm just planning to add in a `mouseWheel` even listener to the component and pass the `onScroll` callback to it (right now it's only passed into the main grid area).

By the way, I would advise against adding a wheel handler. Attaching a wheel handler forces the browser to scroll in the UI thread which can cause noticeable performance issues for larger grids.

Instead just attach the `onScroll` callback to each of your `Grid`s if you want them all to be scrollable. Something like this:

```js
<ScrollSync>
  {({ clientHeight, clientWidth, onScroll, scrollHeight, scrollLeft, scrollTop, scrollWidth }) => {
    <Grid
      className='leftGrid'
      onScroll={onScroll}
      scrollTop={scrollTop}
      {...otherProps}
    />
    <Grid
      className='topGrid'
      onScroll={onScroll}
      scrollLeft={scrollLeft}
      {...otherProps}
    />
    <Grid
      className='mainGrid'
      onScroll={onScroll}
      scrollLeft={scrollLeft}
      scrollTop={scrollTop}
      {...otherProps}
    />
  }}
</ScrollSync>
```

**Comment by bvaughn** [comment]
I'm going to close this since there's nothing actionable for me to do (other than perhaps update my demo/example code). But feel free to continue asking questions if you have any. :)

**Comment by kxcrl** [comment]
Oh wow, thank you for the very rapid and in depth response. Thanks also for the heads up about the performance issues. I'll be taking your advice and just hiding the scrollbars instead. No further questions. = )
