### ISSUE TITLE
Question: is there functionality built in to do something like onCellClick() or onCellDblClick()

### ISSUE THREAD

**Issue by mikedevita** [bvaughn/react-virtualized#224]
I need to be able to do *something* when a user doubleclicks on a cell in a table. I dont see anything documented for this but was wondering if it already exists and is just not documented, or if it can be added in a future release?

**Comment by bvaughn** [comment]
Hey Mike,

`FlexTable` supports an row on-click callback (since you couldn't implement that yourself) but if you want a cell on-click, you would have to just render your cell (and attach the on-click yourself). Does this make sense?

I am very wary to pass through all possible events for a cell because there are a lot of them and a user can always implement it themselves via a custom table cell renderer. Basically just fork [this](https://github.com/bvaughn/react-virtualized/blob/master/source/FlexTable/defaultCellRenderer.js) and add on-click behavior. :)

**Comment by bvaughn** [comment]
Going to close this as I don't plan on taking any action on it and I like to keep the issues list clean. We can chat more here if you have follow up questions though. :)

**Comment by mikedevita** [comment]
holy quick response... thanks @bvaughn .. ill look into forking it and adding a dblClick
