### ISSUE TITLE
react-virtualized not work in react-router

### ISSUE THREAD

**Issue by geminiyellow** [bvaughn/react-virtualized#226]
Hi, @bvaughn 

i want to use `react-virtualized` in my project. and i try the demo, it work well. then i try to move it into `react-router`:

- `import 'react-virtualized/styles.css';` will cause module not found error, so i copy the `styles.css` file to the project folder

- the router 
```
export const route = {
  path: 'demo',
  indexRoute: { component: Summary },
  ...
};
``` 

- and `Summary` component just copy the code from [VirtualScroll.md](https://github.com/bvaughn/react-virtualized/blob/master/docs/VirtualScroll.md)

- run the project, the container 
```
<div aria-label="grid" class="Grid VirtualScroll" role="grid" tabindex="0" style="height: 300px; width: 300px; overflow: hidden;"></div>
```
is working, 

but the items gone. the method not working

```
rowRenderer={
      ({ index, isScrolling }) => list[index] // Could also be a DOM element
    }
```

can you tell me what should i do?

**Comment by bvaughn** [comment]
I'm afraid I can't help you with the information you've posted. You'll need to post sample code on Plunker to begin with so that others can see what you're trying in a little more detail. I assure you though that react-virtualized and react-router work fine together.

You may also try a site like Stack Overflow for this type of question. It's likely to get a faster response (and from more people than just me). :)

Going to close this issue since it's not a feature request or bug. Once you've posted your code somewhere that can be seen, try Stack Overflow or maybe the react-virtualized Gitter room for help. :)
