### ISSUE TITLE
Why is width required?

### ISSUE THREAD

**Issue by clauderic** [bvaughn/react-virtualized#229]
Why isn't the `width` prop required? Shouldn't it just default to `width: 100%` and be an optional prop?

**Comment by bvaughn** [comment]
A `width` property is required because there is no HTML element resize event and so there's no straight forward, native way for an element to detect its own size (if it changes). I feel it's better for react-virtualized components to be _pure_ and _stupid_ about their sizes. If you want 100% width or height behavior, use the `AutoSize` HOC.

**Comment by clauderic** [comment]
I see your point, and part of me agrees with you, but I still feel like it's an opinionated standpoint that adds an unnecessary constraint.

I can definitely see the benefits of using AutoSize for the height of a component, but for the width... I feel like the AutoSize HOC adds an unnecessary layer of complexity, not to mention the performance hit (which is especially true when working with low powered mobile devices)

**Comment by bvaughn** [comment]
You don't _have_ to use `AutoSizer` if you don't plan on dynamic a (changing at runtime) width. Just read the width in your wrapper component and pass it down to whatever react-virtualized component you're using.

It _is_ an opinionated standpoint but it provides the most flexibility to users. You can use a fixed-size, or `AutoSizer`, or your own lightweight wrapper. Should be pretty simple, no?

**Comment by mmontag** [comment]
This is disappointing. I am still confused on the answer. Why does `List` need to know the width of child elements *at all* if it's only going to be scrolled vertically?
