### ISSUE TITLE
Allow onScroll when Grid does not have scrollbar

### ISSUE THREAD

**Issue by khankuan** [bvaughn/react-virtualized#230]
Hi,

I have a use cases for onScroll where i'm using it to detect downward scrolling. When that happens, i will collapse a component above the Grid. Unfortunately, this causes the Grid to resize and now the Grid does not have a scrollbar as it is large enough. Originally, when i'm scrolling upwards back to the top, I will uncollapse the component above. Since onScroll does not happen when the Grid is not scrollable, the backward behavior is not triggered. 

I tried various methods in attempt to force the scrollbar but wasn't successful. Any tips appreciated :)

**Comment by bvaughn** [comment]
Hey @khankuan,

Unfortunately this is not enough information for me to help. I suggest creating a Plunker (or similar) that shows what you're trying to do and then maybe asking on the Gitter channel or Stack Overflow?

In the meanwhile I'm going to close this issue since it's not actionable (just a question). I'll still see responses and such though. :)
