### ISSUE TITLE
FlexTable - rowspan would be a nice to have feature

### ISSUE THREAD

**Issue by davidworkman9** [bvaughn/react-virtualized#245]

**Comment by bvaughn** [comment]
Hey @davidworkman9, thanks for suggesting a feature!

Unfortunately I don't think the `FlexTable` interface has a meaningful way to accommodate a `rowSpan` attribute. With HTML tables, `rowSpan` and `colSpan` are specified on a `<td>`, but with react-virtualized, cell-rendering is managed by `FlexTable` itself in order to simplify the flexbox display properties. (That's actually the primary function of `FlexTable`- you could just use `VirtualScroll` if you want to manage the flexbox properties manually.)

There are some additional compexities as well:
* Since `FlexTable` is flexbox based, actually implementing `rowSpan` would be a little tricky. We'd have to render empty column(s) in the later row(s)- so that flex sizing for that "row" would not get screwy- and position the spanned column so that it extended over top of the lower columns.
* react-virtualized windows rows and columns (for performance purposes) but in the case of row/col span this opens some complicated edge-cases. If a given row or column could extend past its normal grid boundaries, then the logic for determining which rows/columns to display for a given scroll position becomes significantly more complicated.

Please feel free to share a proposal if you have ideas for ways to account for the above challenges. In the meanwhile though, I'm going to close this ticket as I don't currently plan to take any action on it. :)

**Comment by bvaughn** [comment]
For what it's worth, I posted a link on Twitter to this issue asking others to chime in if they have ideas. You're not the first one to request this feature! ;)

**Comment by davidworkman9** [comment]
Oops, sorry to repeat an issue. I searched first but forgot to search closed issues. I can understand the complexity that would be involved. My requirements for a rowspan are pretty simple, limited to a single row span. What I ended up doing was rendering an unordered list and calculating the row height based on the number of entries in my list.

**Comment by bvaughn** [comment]
Oh no worries! I didn't mean to sound like I was complaining about a duplicate. I just meant that you're not the only one wanting this feature! :)
