### ISSUE TITLE
Add working Plunker with JSX to documentation

### ISSUE THREAD

**Issue by andynoelker** [bvaughn/react-virtualized#263]
I have seen a considerable number of issues raised that follow this pattern:

1. User says some feature in this project isn't working as expected
2. @bvaughn asks for a Plunker demonstrating the issue
3. User cannot figure out how to get code example working in Plunker and leaves in frustration

I can sympathize with people experiencing this, as I've just spent 2 hours trying to get Plunker to work with my own code so I could also show an issue I'm experiencing. If we were to add a basic working Plunker example of this project to the documentation, I think it would save everyone a considerable amount of time and frustration - issues could be asked in a much more helpful manner.

I am aware of the [playground files](https://github.com/bvaughn/react-virtualized/tree/master/playground) and I have been successfully able to copy/paste those into a Plunker and it looks like they work. However, they do not use JSX nor seem to be very basic examples to build upon. As all of the documentation uses JSX and I would assume most people using this library, it makes sense that the Plunker would also need to incorporate that.

@bvaughn what do you think? Would this be a good thing to add to the documentation? I'd make this a PR myself, but as I said, I can't get it figured out in the first place. :flushed:

**Comment by bvaughn** [comment]
Hey @andynoelker,

You raise a good point. This pattern does sometimes happen. Usually I try pretty hard to work with people to figure out what's happening from their description or demo videos. (I don't always _insist_ for a Plunker.) But sometimes it's just too hard to guess what's going on- and Plunkers often make it super easy for me to spot that the problem is a missing CSS file or something superficial like that.

I maintain the Playground files to help with this although I realize they don't use JSX and a lot of people are familiar with that. In the past I have suggested people also use [Babel's online tool](https://babeljs.io/repl/) to convert their JSX demos to something that can be run in Plunker.

I'm actually surprised and pleased to see that Plunker supports JSX now. (When did that happen!) So I've created a Plunker that others can fork: https://plnkr.co/edit/6syKo8cx3RfoO96hXFT1

I'll update the `ISSUE_TEMPLATE.md` file to link to this.

**Comment by bvaughn** [comment]
New issue templates now link to this Plunker. :)

Thank you for the suggestion!

**Comment by andynoelker** [comment]
Wow! You are fast! Thanks so much! :smile:

**Comment by bvaughn** [comment]
No problem. Hope it helps with your issue report ;)
