### ISSUE TITLE
FlexTable documentation error

### ISSUE THREAD

**Issue by newswim** [bvaughn/react-virtualized#264]
This may have been obvious to many, but the demo had a prop of `rowCount` however the component expects a prop `rowsCount` - with an s.

Tripped me up for a while.

**Comment by bvaughn** [comment]
Hey @newswim,

The [docs](https://github.com/bvaughn/react-virtualized/blob/master/docs/FlexTable.md) and [code](https://github.com/bvaughn/react-virtualized/blob/master/source/FlexTable/FlexTable.js#L106) all say `rowCount` because that's what's expected. Maybe you're using an older version of react-virtualized? That property was renamed in version 7, as mentioned in the [release notes](https://github.com/bvaughn/react-virtualized/blob/master/CHANGELOG.md#700). I even included a jscodeshift script to auto-rename.

**Comment by newswim** [comment]
Ah! I was using 6.2.1, thank you!

**Comment by bvaughn** [comment]
No problem! :D
