### ISSUE TITLE
Can we have scrollable fixed header in ScrollSync?

### ISSUE THREAD

**Issue by hiddenl00p** [bvaughn/react-virtualized#266]
We are using ScrollSync component and really like it, but few users get confused when they try to scroll from the fixed header. Our use case is first fixed header column is the contact name, and other columns are for contact details.

**Comment by bvaughn** [comment]
I assume you're asking about vertically scrolling- because horizontal scrolling should already work fine. But vertical scrolling isn't something I can really support from within `Grid` or `ScrollSync`.

You could maybe listen for scroll/wheel events in the common ancestor of both grids and do something with it (eg update the `scrollTop` in the lower grid). But I think you'll have to do that in your application code because I don't think I know of a generic solution within react-virtualized. :)
