### ISSUE TITLE
FlexTable Horizontal Scrolling

### ISSUE THREAD

**Issue by vjancik** [bvaughn/react-virtualized#268]
Filing here, because of a possible bug / missing feature.

Hey, my FlexTable Columns total sum of minWidths is larger than the width of the whole table. However the columns and it's contents that overflow get cut. Instead it should enable horizontal scrolling right? As FlexTable uses Grid underneath.

How can I enable this? I can't seem to find an option for this.

Thank you!

**Comment by bvaughn** [comment]
`FlexTable` does not support horizontal scrolling. I've looked briefly at supporting it in the past but it was more complicated than seemed worth doing so I bailed on it.

If you want a similar affect, have you tried giving the `FlexTable` a larger width (the sum of your column min-widths) and putting it within a container that scrolls horizontally? (Wouldn't that achieve the same affect?)

If you want true horizontal scrolling, `Grid` is the way to go. :)

**Comment by bvaughn** [comment]
By the way I'm going to close this issue because I don't intend to take any action on it beyond discussion, which we can continue to do once it's closed. (I'll still see comments and respond to them.)

**Comment by vjancik** [comment]
That's surprising? Isn't FlexTable building upon Grid?
And yes, horizontal overflow scrolling could work, with some extra work. But I can't leverage the JIT rendering horizontally, which for my use case isn't that big of a deal, but could be, for bigger tables.

And I can't fixate the first column! To follow the horizontal scroll, which would be nice even for my use case.

**Comment by bvaughn** [comment]
I can understand why you feel that way, but it's an intentional design decision. `FlexTable` is a (somewhat) narrowly focused HOC intended to simplify a specific use-case: data the grows to fill the available width while behaving somewhat similar to an HTML `<table>`. Horizontal windowing is left to the realm of the much-more-generic `Grid`. Bigger "tables" that require horizontal windowing should just use `Grid`. (Why wouldn't they?) If they want some form of column resizing similar to `FlexTable` then they can also use the [`ColumnSizer` HOC](https://bvaughn.github.io/react-virtualized/?component=ColumnSizer) I created for that purpose. :)

Fixed columns are another bag. Basically they're tricky and I don't have the bandwidth to really explore them fully. (This is a nights-and-weekends project for me and it already takes a good chunk of time to stay on top of, so that's something I just haven't had a chance to get to.) In the meanwhile, the [`ScrollSync` HOC](https://bvaughn.github.io/react-virtualized/?component=ScrollSync) can be used to create certain types of fixed rows and columns.

:)
