### ISSUE TITLE
Misuse of names ("cell" used in place of "row")

### ISSUE THREAD

**Issue by gajus** [bvaughn/react-virtualized#276]
The current markup hierarchy is:

```
Grid__cell
  FlexTable__row
    FlexTable__rowColumn
      FlexTable__truncatedColumnText
Grid__cell
  FlexTable__row
    FlexTable__rowColumn
      FlexTable__truncatedColumnText
...
```

This does not make much sense, because:

* "cell" is used to store the data (see https://en.wikipedia.org/wiki/Table_cell)
* "row" is used to group cells horizontally
* "column" is used to group cells vertically

Therefore, the markup should be:

```
FlexTable__row
  FlexTable__rowColumn (optional; could be used to optimize lookup of colums, but the same can be achieved using a bit of math with Grid__cell)
    Grid__cell
      Grid__truncatedCellText
FlexTable__row
  FlexTable__rowColumn
    Grid__cell
      Grid__truncatedCellText
...
```

**Comment by bvaughn** [comment]
The markup is just `<div>`s. You're referring to the class names. I don't think the semantics of class names are very important- at least not important enough to warrant a non-backwards-compatible change (which would require a major version bump).

It is the way it is because a `FlexTable` is really just a HOC that decorates a `Grid`. Each "row" in the table is actually a `Grid` "cell" that uses a flexbox layout to create columns within it.

I appreciate your taking the time to write this issue but I'm going to close it because I don't plan on taking any action. Cheers. :)

**Comment by gajus** [comment]
> The markup is just <div>s. You're referring to the class names.

I was referring to the semantic meaning meaning.

> I don't think the semantics of class names are very important- at least not important enough to warrant a non-backwards-compatible change (which would require a major version bump).

It is same like saying it is not important what you name your child.

This makes reading the markup/ CSS confusing to say the least. Naming "row", "column", "cell" as "cow", "chicken" and "goat" would have been less confusing than naming them in ~reverse order.

**Comment by gajus** [comment]
Thats fair reasoning.
