### ISSUE TITLE
[Request] Offset grid top & left

### ISSUE THREAD

**Issue by jfrolich** [bvaughn/react-virtualized#284]
Currently it is not possible to have more offset than the cell offset in a grid on the top and the left inside the grid. We cannot set the padding, because it's being positioned absolutely. The right/bottom can however been done with padding (because it just leaves the inside of the components with more space.

My use-case would be to scroll the elements behind a static semi-transparent overlay with some filtering options. The initial y-position therefore needs to be padded otherwise the first row of components will be right under the overlay.

A simpler use-case would be that if you want a different spacing from the first elements towards the upper component, than the 1/2 spacing between the components, this is not possible right now.

Implementation wise I think it would makes sense to have it as a paddingLeft and paddingTop attribute to the grid component, so that all elements just get this number added to their x and y position. I can think this is pretty involved, because those numbers also influence in what rows/columns are visible.

**Comment by bvaughn** [comment]
Hey @jfrolich,

What you're describing would almost be possible using the [`cellRangeRenderer` property](https://github.com/bvaughn/react-virtualized/blob/master/docs/Grid.md#cellrangerenderer). Something like...

```js
// This is the default range-renderer used by Grid
import { defaultCellRangeRenderer, Grid } from '../'

// This is your custom range-renderer
function cellRangeRenderer (props) {
  const children = defaultCellRangeRenderer(props)
  
  return [
    <div
      key={0}
      style={{
        position: 'absolute',
        top: 10,
        left: 10
      }}
    >
      {children}
    </div>
  ]
}

function CustomizedGrid (props) {
  return (
    <Grid
      cellRangeRenderer={cellRangeRenderer}
      {...props}
    />
  )
}
```

Unfortunately this would result in the last column and row being slightly clipped.

As far as supporting this in vanilla `Grid` goes, I'm reluctant to be honest. It feels a little use-case-specific and I try to avoid putting that sort of thing into `Grid` because it increases maintenance complexity and potentially slows things down (since it involves more runtime calculations).

Maybe you can show me some mockups or something of what you're trying to accomplish and I could give you suggestions for alternate ways of achieving it?

**Comment by jfrolich** [comment]
Thanks, will try your solution and see if that solves my use-case.

**Comment by bvaughn** [comment]
I'm struggling to keep on top of issues the last 2 weeks. Lots of requests coming in. So~ I'm going to close this one for now as it's not immediately actionable for me. But we can keep talking! If you can provide me with some more info, hopefully we can find a solution. I'll keep an eye on comments! :)
