### ISSUE TITLE
Use VirtualScroll with Flexbox

### ISSUE THREAD

**Issue by maxnowack** [bvaughn/react-virtualized#285]
I've a scrollable flexbox layout in my app. There are squared boxes with fixed height and width. Depending on the screen size, more or less boxes will be shown in a row.
Is there a way to use `VirtualScroll` in a flexbox like this?

**Comment by bvaughn** [comment]
Hi @maxnowack,

I'm not sure I understand. I _think_ you're saying that you want to use a `VirtualScroll` where each row contains some number of these boxes, and as the screen gets narrower you'd need more rows in order to contain all of the boxes.

If so then yeah, you could use an `AutoSizer` and a `VirtualScroll` together to do that. Something like this...

```js
// Made up numbers, replace these with whatever your real box sizes are
const BOX_WIDTH = 100
const BOX_HEIGHT = 50

function render () {
  return (
    <AutoSizer>
      {({ height, width }) => {
        const numberOfBoxesPerRow = Math.floor(width / BOX_WIDTH)
        const rowCount = Math.ceil(numberOfBoxes / numberOfBoxesPerRow)

        return (
          <VirtualScroll
            width={width}
            height={height}
            rowCount={rowCount}
            rowHeight={BOX_HEIGHT}
            {...otherProps}
          />
        )
      }}
    </AutoSizer>
  )
}
```

**Comment by bvaughn** [comment]
Going to close this issue since I think your question has been answered, and I try to keep the issues list pruned. But I'll see any follow up questions if you have them. :)

**Comment by maxnowack** [comment]
Thank you @bvaughn! I'll try that :)
