### ISSUE TITLE
Webpack UMD config and `react-addons-shallow-compare`

### ISSUE THREAD

**Issue by ducky427** [bvaughn/react-virtualized#292]
Hi. 
I am using the UMD build of this library. It seems that the UMD webpack config file doesn't list `react-addons-shallow-compare` as an external package. So it is included in the final build file. I think this shouldn't be the case. But I don't know enough by webpack to suggest a fix. 

Any help would be appreciated. 

Thanks

**Comment by bvaughn** [comment]
Hey @ducky427,

Interesting. I think I agree with you that it shouldn't be included in the UMD build.

The fix for this is pretty simple. I just need to add a new externals entry for `react-addons-shallow-compare` [here](https://github.com/bvaughn/react-virtualized/blob/master/webpack.config.umd.js#L16).

**Comment by bvaughn** [comment]
Hm, not as straight forward as I hoped. Not sure how to make Webpack play nicely with something from `React.addons`. Tried a couple of things without any luck. Will take another look at this in the evening. In the meanwhile, help appreciated if anyone knows the answer. :)

**Comment by ducky427** [comment]
I think I've figured it out. PR sent.

**Comment by bvaughn** [comment]
7.11.1 release is available with this UMD fix. Thanks for your help!

**Comment by ducky427** [comment]
Thanks a lot for the quick release!

👍
