### ISSUE TITLE
Imprecise scrollTop value when scrolling

### ISSUE THREAD

**Issue by vysinsky** [bvaughn/react-virtualized#304]
Hi,
I use Grid component with onScroll handler to load data when the user stops scrolling.
I calculate offset to load with `let offset = Math.floor(props.scrollTop / ROW_HEIGHT);` in `onScroll` handler. When our datagrid has a lot of rows (249000) the 'lower' I scroll the bigger is deviation between the index of real first visible row in datagrid and calculated offset - deviation is about 19.79 %. I don't know what does this number signify but it causes loading of different data than in viewport.

I've also tried to use `InfiniteLoader` component and it has the same problem. The value of `startIndex` is always lower than real index of the first row. If you need more info, please let me know. I don't know what information should I give you. Thanks in advance.

**Comment by bvaughn** [comment]
Hey @vysinsky,

Assuming your average `rowHeight` is greater than 41, this is because react-virtualized is scaling down the offsets in order to avoid exceeding the maximum browser-supported `scrollHeight` and `scrollTop` (mentioned briefly [in the release notes here](https://github.com/bvaughn/react-virtualized/blob/master/CHANGELOG.md#730)). This functionality is handled by the [`ScalingCellSizeAndPositionManager`](https://github.com/bvaughn/react-virtualized/blob/master/source/Grid/utils/ScalingCellSizeAndPositionManager.js).

Maybe you can explain more to me about why this is causing you problems? I assumed that this feature would be transparent to most users. (It certainly seems better than having a certain part of your grid be unreachable because the browser refuses to scroll that far.)

That being said, I picked 10M pixels as the cut-off point. I could probably increase that slightly. Chrome for instance will go to ~33.5M- but I don't know what the max offsets for _all_ browsers are so I chose to play it safe.

**Comment by vysinsky** [comment]
Hi @bvaughn,

we have `rowHeigth` of 48 px so it means it is scaled down and probably `onScroll` callback receives scaled `scrollTop` value. Is it possible to scale it back again? My colleague (@vojtech-dobes) will provide more info soon.

**Comment by vojtech-dobes** [comment]
What we actually need to achieve is to get *row* we scrolled to, not offset. Our naive calculation `offset / row height` doesn't work because of the scaling (which is great feature of course). Question for us is how to solve this?

- We could maybe replicate scaling algorithm to get the actual row number.
- It would be awesome if we could get row number along with the scroll offset :).
- Or scroll offset could be "scaled back", so our naive calculation would work.

These are approaches I was able so far to think about.

**Comment by bvaughn** [comment]
Thanks for the additional info. But might I ask- if all you're looking for is to know which range of rows have been rendered, why not use `onSectionRendered` instead of `onScroll`? It passes you the following named parameters: `({ columnOverscanStartIndex: number, columnOverscanStopIndex: number, columnStartIndex: number, columnStopIndex: number, rowOverscanStartIndex: number, rowOverscanStopIndex: number, rowStartIndex: number, rowStopIndex: number })`

Alternately you could pass `Grid` a custom `cellRangeRenderer` as shown in the docs: https://github.com/bvaughn/react-virtualized/blob/master/docs/Grid.md#cellrangerenderer. In addition to receiving the `scrollTop` it also receives `rowStartIndex` and `rowStopIndex`.

I don't think `Grid` can pass the row number along with the scroll handler (at least not without some heavy refactoring) as those calculations are done in separate places and I'd rather not duplicate them. (Scrolling is a very performance-sensitive area since events fire frequently so I'm very cautious about what work is done in reaction to a scroll event.)

**Comment by vojtech-dobes** [comment]
> I don't think Grid can pass the row number along with the scroll handler (at least not without some heavy refactoring) as those calculations are done in separate places and I'd rather not duplicate them. (Scrolling is a very performance-sensitive area since events fire frequently so I'm very cautious about what work is done in reaction to a scroll event.)

Totally understood. I was absolutely blind, as I was reading Grid documentation through and still missed `onSectionRendered` :). Looks like exactly what we need.

**Comment by bvaughn** [comment]
Woo hoo! Nice! :)

Going to close this issue then.
