### ISSUE TITLE
[FlexTable] Disable tabindex on rows

### ISSUE THREAD

**Issue by levrik** [bvaughn/react-virtualized#320]
Would it be possible to have an option to disable the tabindex on rows like you can disable the tabindex on the complete FlexTable by using `tabIndex={null}`?

**Comment by bvaughn** [comment]
What's the use-case?

Initial thought is that the API for this would be a bit awkward, since other click/tab things are for the _whole_ table.

**Comment by levrik** [comment]
Sorry, I meant for all rows, not a specific one.

**Comment by bvaughn** [comment]
`tabIndex` is [only added to a row if you have mouse-events registered](https://github.com/bvaughn/react-virtualized/blob/master/source/FlexTable/FlexTable.js#L451-L464). This is an important for a11y (usability). Without it, keyboard-only users can't focus-on (can't "click") the rows. I don't think this is something I should make configurable.

**Comment by levrik** [comment]
I think this is not something a library should decide for me. I understand your intention but there are cases where this is not the wanted behaviour.

**Comment by bvaughn** [comment]
It's not possible for react-virtualize (or any library) to implement every feature that people suggest. Each feature ads complexity (even if only a little) which increases the burden of maintenance. Also once a feature is in a library, there's a much higher bar for removing it. (It requires a major release; people may complain that they've come to depend on the feature. etc)

As a maintainer, I try to choose configurable options that I think are useful to a significant percentage of users and I try to choose reasonable defaults for the rest. In this case, I think choosing a default that is a11y-friendly is the right choice.

If you would like to submit a PR with a proposal for how to implement this I would be happy to review it, but I may decide not to merge it (for the reasons I mentioned above).

All this being said, `FlexTable` and `VirtualScroll` are both just high-order components that decorate a `Grid`. Neither are meant to be as flexible or full-feature as `Grid`. They're just intended to be a convenient way to create a certain _type_ of grid layout. If you don't like their defaults, you can always fall back to using a `Grid`.

I'm going to close this issue for now because I don't intend to take any action on it. We can continue to chat here though. (I'll still see and respond to your messages.) If you'd like to make a case for why this functionality is important to your application, I will give it consideration.

**Comment by levrik** [comment]
@bvaughn I have two tables side by side in some type of container with two search fields above. I want that the user is to be able to switch with Tab between these search fields. The table itself implements an onRowClick and an onRowDoubleClick. The double click action is the main action. I want to implement a keyboard control with the arrow keys (up and down) for the onRowClick action and a Space or Enter for the onRowDoubleClick action. But this is not possible if the tabIndex is active on the rows.
