### ISSUE TITLE
[FlexTable] onRowDoubleClick

### ISSUE THREAD

**Issue by levrik** [bvaughn/react-virtualized#321]
Would it be possible to add a `onRowDoubleClick` callback to FlexTable?
And how I could achieve this now without this callback or would you accept a PR?

**Comment by bvaughn** [comment]
Hm. It's possible, yeah. I'm a bit reluctant to keep adding additional event pass-throughs to row (eg click, mouse-over, mouse-out, double-click, etc) because there's potentially no end 😅 but double click seems like a reasonable one to add.

I wonder if a better way would be to add a generic`rowProps` object that could be used to assign arbitrary event handlers to a row...

Let me sleep on it. It's almost midnight here. :)

**Comment by bvaughn** [comment]
[`onRowDoubleClick` available in 7.13.0](https://github.com/bvaughn/react-virtualized/blob/master/docs/FlexTable.md#prop-types)
