### ISSUE TITLE
[FlexTable] onRowClick and onRowDoubleClick not working always

### ISSUE THREAD

**Issue by levrik** [bvaughn/react-virtualized#322]
Hey there. Me again.
If I scroll a bit down in a FlexTable and try to click or double click on a row the handler does not get called. If I try again the handler does get called.
Here's a plunker: https://plnkr.co/edit/gAEv8xgCjCJ3IZtJTlx5
And a GIF demonstrating the problem:
![2016-07-23_10-49-31](https://cloud.githubusercontent.com/assets/9491603/17077078/7ef4f996-50c3-11e6-81a7-c3341d00d3fa.gif)

**Comment by levrik** [comment]
@bvaughn Here a another GIF demonstrating the source of this issue:
![2016-07-23_10-55-04](https://cloud.githubusercontent.com/assets/9491603/17077087/16bd39e6-50c4-11e6-9ba9-8626f09cb909.gif)
There's sometimes a delay when switching back from `pointer-events: none` to `pointer-events: auto`

**Comment by bvaughn** [comment]
[`pointer-events` are toggled off when scrolling](https://github.com/bvaughn/react-virtualized/blob/master/source/Grid/Grid.js#L525) for performance reasons. They're [re-enabled a short time (150ms) after the final scroll event is received](https://github.com/bvaughn/react-virtualized/blob/master/source/Grid/Grid.js#L637-L657).

While pointer events are disabled, clicks are ignored, as you've observed. Not sure there's much I can do about this though to be honest. Perhaps I could lower the interval slightly before they're reenabled...

**Comment by bvaughn** [comment]
This is a common optimization technique. For example, `fixed-data-table` does this too ([condition](https://github.com/facebook/fixed-data-table/blob/0c8a7d1317077e788eae619a245bd77b09c0bf1c/src/FixedDataTableBufferedRows.react.js#L161), [timeout](https://github.com/facebook/fixed-data-table/blob/53409203d49a87f556903e8be3e1ea9a388e556d/dist/fixed-data-table.js#L1024) defaults to 200ms) as does `react-infinite` ([condition](https://github.com/seatgeek/react-infinite/blob/30269db182663662cd07c50bc961cc081e0aafa1/src/react-infinite.jsx#L424), [timeout](https://github.com/seatgeek/react-infinite/blob/30269db182663662cd07c50bc961cc081e0aafa1/src/react-infinite.jsx#L341-L361) defaults to 150ms)

**Comment by bvaughn** [comment]
Even if I lowered the interval slightly- something I'm reluctant to do, for fear of turning off prematurely- there's still going to be some time when the browser is performing the scroll animation when users would not be able to click on rows.

I think the best thing to do in this case is to use the `isScrolling` parameter passed to the cell renderer to change the style of cells slightly to make it visually clear when they're clickable vs not clickable.

**Comment by bvaughn** [comment]
My guess is that it's fairly unlikely that users are scrolling and clicking at the same time. It's kind of an awkward interaction. (Human brains need a bit of time to process what they're seeing when data has changed.) I suspect this may be something that we do as engineers that real users don't actually do?

**Comment by levrik** [comment]
@bvaughn As you can see on the GIF there is much more time between the final scroll event and the re-enabling. About 800-1000ms. I also experienced in my application a delay by about 2 seconds. I will analyze this in production if it's a problem or not :)

**Comment by bvaughn** [comment]
The gif doesn't show much, to be honest. Because it doesn't show when you're clicking. (There's no indication of ignored clicks.)

The code for this is pretty straight forward. Each time `Grid` receives a scroll event, [it registers a timeout to re-enable scroll events](https://github.com/bvaughn/react-virtualized/blob/master/source/Grid/Grid.js#L815-L824) This is the only place this method is called, and it's called on every scroll.

Browsers manage a smooth scrolling animation that has kind of a long tail as it slows down and stops. Maybe you're perceiving the end of scrolling before it's actually done. (Maybe the browser fires a last few micro-adjustments.) I'm fairly confident this is what's happening. The last ~second of scrolling is just the tail end of the animation, not very noticeable.

Also keep in mind that `setTimeout` isn't guaranteed to invoke the callback _at exactly the specified time_. It's only guaranteed _not to invoke it before_ the specified time. If a lot of heavy crunching is going on (not likely from the look of your Plunkr) that can cause timeouts to be invoked later. Nothing I can do about that if that's the case.

**Comment by levrik** [comment]
Yeah I unterstand. It looks at first like an issue with the library to me. I will close this now and open a new issue this is really a problem. Like you said: It's maybe something a real user don't actually do.

**Comment by bvaughn** [comment]
😅 Sounds good to me.

**Comment by mikhail-eremin** [comment]
Have the same issue with react-virtulized 7.16.0
Sometimes, after scroll, "pointer-events:none" isn't removed from Grid__innerScrollContainer, so items are unavailable for a while after scroll.

**Comment by levrik** [comment]
@bvaughn I will reopen this. Experienced this issue now in production. Users don't see this as problem with the application, but they are trying a second time. This is not the ideal situation.

**Comment by bvaughn** [comment]
> Sometimes, after scroll, "pointer-events:none" isn't removed from Grid__innerScrollContainer, so items are unavailable for a while after scroll.

@mikhail-eremin I have never seen this happen and I've used react-virtualized _a lot_. If you could provide a repro case then I'll be happy to take a look. Else I'm a little skeptical because the code for this is fairly straight forward (see [here](https://github.com/bvaughn/react-virtualized/blob/master/source/Grid/Grid.js#L561), [here](https://github.com/bvaughn/react-virtualized/blob/master/source/Grid/Grid.js#L673-L697), and [here](https://github.com/bvaughn/react-virtualized/blob/master/source/Grid/Grid.js#L834)).

Have you specified a custom/override value for `scrollingResetTimeInterval`?

@levrik Disabling pointer events while scrolling is something _all_ of the windowing libraries do (see [fixed-data-table](https://github.com/facebook/fixed-data-table/blob/5cbf487dd038c2b741cd0298922c1c30dacb38d7/src/FixedDataTableBufferedRows.react.js#L161), [react-infinite](https://github.com/seatgeek/react-infinite/blob/6c38c2ef3c473394a57c80c06339754e621f2909/src/react-infinite.jsx#L418-L421), etc). However if you want to _prevent_ (or change) this behavior, you have 2 options:

1. Set `pointerEvents: 'auto'` on your cell/row/column renderer. (This overrides the parent value.)
2. Try reducing the `scrollingResetTimeInterval` interval. It's 150ms by default which more or less aligns with the others (eg [fixed-data-table uses 200ms](https://github.com/facebook/fixed-data-table/blob/5cbf487dd038c2b741cd0298922c1c30dacb38d7/src/FixedDataTableNew.react.js#L282), [react-infinite uses 150ms](https://github.com/seatgeek/react-infinite/blob/6c38c2ef3c473394a57c80c06339754e621f2909/src/react-infinite.jsx#L99)) but you could try reducing it if you think users are clicking "too soon".

**Comment by levrik** [comment]
@bvaughn Yeah. I understand why `react-virtualized`and the other libs do this.
I investigated this issue a bit more precisely now. It seems that the issue is with Chrome (in my case).
I remove on double click items. The `pointer-evens` changes from `auto` to `none` and back to `auto`. If now I double click on the next item which moved up under the cursor, Chome doesn't regnonize the double click. I will close this again. The initial problem seems not to cause this issue anymore.

**Comment by bvaughn** [comment]
Ah. Interesting. Are you saying that unless you move your mouse a little bit before the click- the browser doesn't pick up on it?

**Comment by levrik** [comment]
@bvaughn Yep. Exactly.

**Comment by bvaughn** [comment]
Hmm... that sounds like a browser security feature. Maybe intended to
prevent malicious sites from tricking a user into clicking something he
didn't intend to buy changing what was under a cursor.

**Comment by levrik** [comment]
@bvaughn Makes sense. I will investigate this a bit more some day :)

**Comment by bvaughn** [comment]
Sounds good. 😄

**Comment by mikhail-eremin** [comment]
@bvaughn I will try you suggestions thank you!
