### ISSUE TITLE
Header for Grid

### ISSUE THREAD

**Issue by arddor** [bvaughn/react-virtualized#331]
Hello

I would like to see the addition of sticky headers on the `Grid` component. Something like `cellRenderer` for row and column headers.  It is currently possible to show the headers just as first row / column however if you have a large `Grid` it gets confusing which cell you are actually editing. `FlexTable` has a header, maybe code could be reused from there?

My usecase is to show a Grid which is editable and functions as matrix input, which is used for computations and provided by the user. The headers should also be editable which would be possible with an approach like in `cellRenderer`.

**Comment by bvaughn** [comment]
Hi @arddor,

This is the reason why the `ScrollSync` HOC was created. Have you considered using it?

Here's an example of it being used to create both a fixed header and a fix column:
https://bvaughn.github.io/react-virtualized/?component=ScrollSync

I have no current plans to add fixed-header support to vanilla `Grid` because I want to keep the interface as simple as possible. This is the reason why I created the `ScrollSync` HOC.

**Comment by arddor** [comment]
No I completely overlooked it. This seems to be a better approach as it also allows to sync multiple Grid with scroll.

**Comment by bvaughn** [comment]
Fantastic :) Glad to hear it!

**Comment by vgopinath** [comment]
Hi bvaughn:
How do i get json data (from AJAX call) and  update the Grid? This virtualized Grid looks really amazing..

Regards
varadhg
