### ISSUE TITLE
expose defaultFlexTableCellRenderer

### ISSUE THREAD

**Issue by olslash** [bvaughn/react-virtualized#339]
In 7.17.1, there doesn't seem to be a way to import the default function that FlexTable/cellRenderer uses. Given that `defaultCellRangeRenderer` and `defaultFlexTableRowRenderer` are exposed, I found it somewhat unexpected that it's not available. 

Obviously it's a very simple function, but it'd be convenient to not have to care what the default renderer does when I'm making a custom renderer with a default fallback.

**Comment by bvaughn** [comment]
I briefly considered exporting the default cell renderer but decided against it because I don't think there's any value to exporting a function that literally reduces to:
```js
function defaultCellRenderer ({ cellData }) {
  return cellData == null ? '' : String(cellData)
}
```

Seems like if someone's overriding the column renderer, they can always just default to returning the string-value of cellData without the need to invoke an external function that requires (but does not actually _use_) all of the following named parameters: `{ cellData, cellDataKey, columnData, rowData, rowIndex }`

**Comment by bvaughn** [comment]
I don't particularly see the usefulness of this but it won't cause any added file-size and so I don't see a reason _not_ to do it either. New named exports are available for `defaultFlexTableCellDataGetter`, `defaultFlexTableCellRenderer`, and `defaultFlexTableHeaderRenderer` via release 7.18.0. Cheers. :)

**Comment by olslash** [comment]
thanks!
