### ISSUE TITLE
InfiniteLoader#loadMoreRows invoked multiple times per scroll

### ISSUE THREAD

**Issue by albertywu** [bvaughn/react-virtualized#345]
Upon scrolling, InfiniteLoader#loadMoreRows is invoked multiple times (sometimes 10+ times) per scroll event. This triggers multiple data fetches to the server.

Feature request: it would be nice if InfiniteLoader fired this event once per scroll. I can't think of a case where a consumer of the API would want to respond to 10+ loadMoreRows callbacks firing.

I see that the behavior is documented [here](https://github.com/bvaughn/react-virtualized/blob/master/docs/InfiniteLoader.md) but curious if there was a good reason for allowing multiple firings.

**Comment by bvaughn** [comment]
Hi @albertywu,

`InfiniteLoader` is a "dumb" component. (If you look at its [source](https://github.com/bvaughn/react-virtualized/blob/master/source/InfiniteLoader/InfiniteLoader.js), minus the inline comments, it's super small.) It doesn't store state; it relies on the smart container or Redux module that's feeding it properties to track loaded/loading progress.

It relies on an `onRowsRendered` callback, which is memoized to only be called when new row/column indices have been rendered. (In other words, it won't call 10x with the _same_ rows, but only if new rows have been rendered.)

In the [`InfiniteLoader` example](https://github.com/bvaughn/react-virtualized/blob/425942327b16d36a132aef40d6a51b622fc7a82e/source/InfiniteLoader/InfiniteLoader.example.js#L114-L125) I track is-loading state in order to prevent loading the same row more than once. It's expected (though perhaps not mentioned explicitly enough in the documentation?) that users of `InfiniteLoader` will do the same. Any suggestions for how I should update the docs to make this clearer?

By the way, you may have already noticed this, but you can also tweak the `minimumBatchSize` and `threshold` to control the granularity of `loadMoreRows` calls.

**Comment by bvaughn** [comment]
Another reason I chose _not_ to track is-loaded state in `InfiniteLoader` (but to make it dumb) is that it has no way of knowing which rows may have been pre-loaded _before_ it requests the first batch of additional rows.

**Comment by albertywu** [comment]
Thanks for the reply!

Makes sense. I added the `isRowLoaded` check, and confirmed that `onRowsRendered` fires with a new set of rows upon scroll.

I did notice that `InfiniteLoader#loadMoreRows` fires multiple times with the same `{startIndex, stopIndex} on scroll though - is this expected? I am currently handling this by cancelling in-flight requests. Curious if this is the correct approach, or if I'm doing something wrong.

**Comment by bvaughn** [comment]
That is not expected, since the `onSectionRendered` callback that triggers `loadMoreRows` is memoized.

You probably don't need to cancel in-flight requests either, FWIW. Once a request has been fired to load a row, just treat it as though the row has been loaded. (No need to re-load it.)

**Comment by bvaughn** [comment]
Hm. I can confirm the behavior you say you're seeing though. I will investigate. :)

**Comment by bvaughn** [comment]
Ah! I see the issue. Kind of a logic bug.

The underlying `onRowsRendered` _is_ memoized. (It only gets called when at least one of its parameters change.) However the `minimumBatchSize` and `threshold` logic inside of `InfiniteLoader` kind of rounds things out so that slightly different `onRowsRendered` values can still result in the same `loadMoreRows` parameters. :)

Good news is that this should not be an issue if you track load-in-progress rows like was suggested above. :)

**Comment by albertywu** [comment]
Maybe a more concrete example will help. In this example, I'm logging out `{startIndex, stopIndex}` immediately before I issue requests to my server to fetch the next batch:

https://gist.github.com/albertywu/b826909bf1147f3ba9262b3d4fd56c6a#file-infiniteloader-tsx-L117

It's probably not a huge issue, but just wanted to confirm.

**Comment by bvaughn** [comment]
Sure, sure. Maybe my explanation above didn't make sense?

**Comment by albertywu** [comment]
Sounds good - thanks for clarifying on the behavior!

**Comment by bvaughn** [comment]
No problem! I'm working on improving the memoization here a bit too for what it's worth. :)

**Comment by bvaughn** [comment]
7.19.3 has improved memoization. :)
