### ISSUE TITLE
[doc] VirtualScroll doesn't like table/tr/td

### ISSUE THREAD

**Issue by estaub** [bvaughn/react-virtualized#351]
In `VirtualScroll`, the injected `<div>` elements cause React to complain about using table tags, e.g.: `Warning: validateDOMNesting(...): <tr> cannot appear as a child of <div>. See TicketTypeListView > div > tr.`  

Given that I see no reasonable way to make table tags work well, I see this just as a need for documentation about it.

The easy workaround (at least in my case) is to use `display: table-row` et al on `<div>` tags in lieu of `<tr>`...

**Comment by bvaughn** [comment]
Seems like the error message you got from React when you tried was pretty helpful. So that's good. :)

**Comment by estaub** [comment]
Ok, I won't bother writing up any of the difficulties with CellMeasurer that need doc'ing (IMHO).  

While expressing what's going on and how to work around it is easy _once one understands_, getting to the point of understanding can be non-trivial, and easily lead to folks saying "this is too hard" and walking away.  A few words can make a difference.

**Comment by bvaughn** [comment]
Sorry if I offended you. I initially wrote a longer reply but decided to go with a shorter one instead because I thought maybe I was just rambling. The longer reply basically said this:

I don't think this belongs in react-virtualized docs.

Firstly because I don't think it's a react-virtualized issue. Rather it is part of the DOM spec. Elements like `div` can contain [flow elements](https://www.w3.org/TR/html-markup/spec.html#common.elem.flow). Table elements like `tr` and `td` have more restricted use-cases. Fortunately, React gave a helpful warning in this case that hopefully limited the confusion and reduced any time lost due to it.

Secondly, and more importantly, longer docs means (1) fewer people will read them and (2) those who do may have more trouble finding what they're looking for.

I've spent a lot of time and effort on react-virtualized docs. I'm sure I'll spend a lot more because they have plenty of room to improve. And I welcome feedback and suggestions on ways to improve them- but I have to make judgement calls on what goes into them- based on my own opinion as well as any larger patterns I've seen from usage of the library over time. (eg if in the future another react-virtualized user expressed a similar opinion- I would probably reconsider my stance on adding this particular issue to the docs somewhere.)

Hopefully this longer explanation makes sense. I didn't mean to sound dismissive with my initial response. 😄 It was early and I hadn't had any. ☕

**Comment by estaub** [comment]
Thanks!  

Likewise, I wouldn't be writing if I didn't think that this is inherently a great project, but I strongly believe that it would be adopted a lot more if it were a little more accessible, especially for people who want to work it into an existing table implementation.  It took a lot of code-reading and breakpointing to understand what's required of the client.  

New users (like me!) have no reason to assume that VirtualScroll works by inserting `<div>`s around each row of their table, or at least aren't likely to have thought about it, and are very unlikely to have thought about the implications re DOM nesting restrictions.

**Comment by bvaughn** [comment]
I see. I thought a bit more about the implications of what you were saying while driving to work this morning and wanted to share a concern with you about using tables in general with windowed ("virtualized") content.

HTML table layouts are determined, in part, by the contents of the columns being laid out. If the contents change, the column widths may be adjusted. With a "virtualized" table this would likely be an issue since- every time you scroll- you're changing the table's contents. The result might be unattractive (columns might resize as a user scrolls up or down).

This is why the `FlexTable` component uses the flexbox layout instead. I'm not sure if flexbxox is an option for your application (given its poor support in older IEs) but if it is- I'd encourage you to consider it as an alternative to table layout. :D

Otherwise, just be sure to use fixed sizes (with min-width and max-width) for your table columns to prevent them from resizing as their content changes. :)

**Comment by estaub** [comment]
Another solution to this problem, which I happened to be using even before working with VirtualTable, is to use  `table-layout: fixed`.  

_Are you sure you don't want to doc this kind of guidance_???  It doesn't have to be inline in the base reference material; "Notes" at the end of a doc page makes sense to me.

**Comment by mackankowski** [comment]
Let me share my experience with **react-virtualized** and some material UI library called [material-table](https://github.com/mbrn/material-table) where the same issue appear (combination table elements with virtualization): https://github.com/mbrn/material-table/issues/891#issuecomment-681986647. There're still some issues like styling problems and `validateDOMNesting(...)` warning.
