### ISSUE TITLE
Memory Leaks in VirtualScroll, Grid

### ISSUE THREAD

**Issue by wesleyahall** [bvaughn/react-virtualized#354]
Need to remove listeners on unmount, possibly more?

**Comment by bvaughn** [comment]
There are no event listeners in `Grid` or `VirtualScroll`.

The only events in RV are in [`AutoSizer`](https://github.com/bvaughn/react-virtualized/blob/master/source/AutoSizer/AutoSizer.js#L46-L59) and [`WindowScroller`](https://github.com/bvaughn/react-virtualized/blob/master/source/WindowScroller/WindowScroller.js#L52-L80) both of which, as you can see, remove their handlers in `componentWillUnmount`.

**Comment by bvaughn** [comment]
If you're seeing a leak somewhere, possible it's in your application code? If you're convinced it's in react-virtualized, then please reopen this issue with more (any?) information.

Keep in mind that GC isn't the most predictable thing too. Browsers choose when to collect, and the threshold is dependent on things like how many resources your system has. So you may see memory grow for a while and hold steady not because of a leak- but just because the browser hasn't decided to pay the cost of collecting.

**Comment by wesleyahall** [comment]
onScroll?

**Comment by bvaughn** [comment]
The only event listeners that can cause leaks would be ones to global objects (eg `window`). If an object adds an event handler to itself or one of its children, then when that object goes out of scope the whole tree underneath of it will be marked for deletion.

What makes you suspect that there are memory leaks? Have you done profiling?

**Comment by wesleyahall** [comment]
Yes, I was profiling this morning and found Instances of virtualscroll allocated after returning from the page that used it to the home page which had no instance.

**Comment by bvaughn** [comment]
Maybe they just hadn't been GCed yet?

**Comment by wesleyahall** [comment]
It looks like the problem might have been in ReactDevTools... still investigating

**Comment by bvaughn** [comment]
Interesting. Keep me posted. :)
