### ISSUE TITLE
Doubleclick on sortable header 

### ISSUE THREAD

**Issue by ellenc345** [bvaughn/react-virtualized#364]
Hey, thanks for the great component! :)
I searched in the past issues and didn't find an handle for double click on the flextable header...
for now it is working fine and sort the column only if i set timeout to prevent doubleclick.
Did i miss something? thanks .

**Comment by bvaughn** [comment]
Hey @ellenc345,

There isn't a built-in convenience function for header-double-click because it's not very common. You can still accomplish it though by specifying your own `headerRenderer` or- easier yet- just decorate the default header renderer. 😄 

```js
import { defaultFlexTableHeaderRenderer, FlexColumn, FlexTable } from 'react-virtualized'

function customHeaderRenderer (params) {
  return (
    <div onDoubleClick={() => console.log('clicked')}>
      {defaultFlexTableHeaderRenderer(params)}
    </div>
  )
}

function render () {
  return (
    <FlexTable {...props}>
      <FlexColumn
        dataKey='foo'
        headerRenderer={customHeaderRenderer}
        label='bar'
        width={100}
      />
    </FlexTable>
  )
}
```

I'd caution against using double click on a sortable header though- since a double click events is accompanied by 2 click events.

**Comment by bvaughn** [comment]
PS. Thank you for the compliment! 😁

**Comment by ellenc345** [comment]
thank you for the quick answer! :)

**Comment by ellenc345** [comment]
@bvaughn, I tried it now and it didnt solve the problem,
the problem when you double click a sortable column it is calling the "load data" once and stops.
it is stop calling the load data with the infinite loader like it should...

**Comment by bvaughn** [comment]
Double clicking and infinite loader seem unrelated. 😄

Firstly, make sure you're using version 7.22.1+ as I fixed a small issue between `FlexTable` and `InfiniteLoader` in that release. 

Check out [this gist](https://gist.github.com/bvaughn/9c7af838646942106a2ff689bbc7a1ff) for an example of using `FlexTable` and `InfiniteLoader`. In particular check out [these lines](https://gist.github.com/bvaughn/9c7af838646942106a2ff689bbc7a1ff#file-infiniteloader-example-js-L32-L44) as you'll need to do something similar when the sort direction changes as the result of a header click since `InfiniteLoader` is memoized. (There is some related discussion about this on issue #361.)
