### ISSUE TITLE
[Feature-Request] Drag and Drop columns

### ISSUE THREAD

**Issue by brene** [bvaughn/react-virtualized#377]
I would love to have a way to drag and drop columns. I believe that this is quite a common use case and can be achieved with [this](github.com/gaearon/react-dnd). I have a feeling that I might not be the only one that needs this feature 😉.

**Comment by bvaughn** [comment]
Hey @brene,

This is already possible using libraries like [`react-sortable-hoc`](https://github.com/clauderic/react-sortable-hoc). :grin:

Drag and drop is complex enough that I think it's best left up to drag-and-drop specific libraries (rather than being baked into `react-virtualized`). Every additional functionality I bring in is something I have to continue to maintain myself (and I have limited bandwidth). For what it's worth, I've used `react-virtualized` and `react-sortable-hoc` together in production and they work great!

**Comment by bvaughn** [comment]
@clauderic is super responsive and helpful. I'm sure if you run into any integration difficulties between the 2 libs, he or I would be happy to help. 😄

**Comment by brene** [comment]
Thanks for the tip! Really means a lot that you are always so fast. Sorry for annoying you all the time😁

**Comment by bvaughn** [comment]
Not a problem 😄

I've been really impressed with @clauderic's components. You should check them all out. 😁

**Comment by clauderic** [comment]
@brene sounds like this should be something that would be feasible with `react-sortable-hoc`, though I haven't tried myself. Happy to assist if you need help 😸

**Comment by bvaughn** [comment]
I've built resizable `Grid` and `FlexTable` columns with `react-draggable` and drag-and-drop `FlexTable` rows with `react-sortable-hoc` but I haven't yet built drag-and-drop _columns_ with it. Should be pretty easy though!

**Comment by samichtioui** [comment]
je cherche un exmple de drag & drop des colonnes avec react-sortable-hoc, je n'ai pas trouver comment je peux le faire. plz help me...

**Comment by bvaughn** [comment]
You should probably be posting on Stack Overflow or the react-sortable-hoc repo for such an example.

**Comment by clauderic** [comment]
@samichtioui you can open an issue in [react-sortable-hoc](https://github.com/clauderic/react-sortable-hoc/issues) and I'll be happy to help you out 👍
