### ISSUE TITLE
[Feature Request] Auto compute static width and height

### ISSUE THREAD

**Issue by romulof** [bvaughn/react-virtualized#388]
`AutoSizer` works brilliantly for dynamic sizing, but it looks like bloated code for static sized lists/grids.

Make VirtualScroll width and height props optional, and compute it's size on `componentDidMount` using refs.

**Comment by bvaughn** [comment]
I think this can be done in user-land easily enough, no?

1. If you have a fixed size, just specify it as props.
2. If you don't know the size at all, and it may change due to window resizing, use `AutoSizer`.
3. If you don't know the size initially, but it's unlikely to change (mobile website?), then do your own just-in-time measurement and inject it as a prop.

RV can't do this _until_ it's mounted, because it has no way of accessing the underlying DOM node or parent until then) which would mean doubling the initial render (or more likely adding some forking logic). I also think that case 3 above is a much less-common one so I'm reluctant to add any code into the library to solve an unusual use-case.

**Comment by romulof** [comment]
I forgot about window resize, and that likely happens too on mobile websites because of orientation changes.

Sorry for your time.

**Comment by bvaughn** [comment]
No problem at all! 😄 Never hurts to ask.
