### ISSUE TITLE
Chat recipe demo broken

### ISSUE THREAD

**Issue by zsherman** [bvaughn/react-virtualized#393]
https://rawgit.com/bvaughn/react-virtualized/master/playground/chat.html

Not a very helpful console error unfortunately.

**Comment by bvaughn** [comment]
That's because I'm in the middle of a major upgrade (version 7 to 8).

You can run the chat recipe against version 7, using master:
https://rawgit.com/bvaughn/react-virtualized/master/playground/chat.html?source=7.24.3

Or you can run it against version 8 from the upgrade branch:
https://rawgit.com/bvaughn/react-virtualized/version-8/playground/chat.html

**Comment by bvaughn** [comment]
This transient error occurs because unpkg.com is defaulting to the RC as the latest build, which causes the master playground files to break. Once v8 is released as main (probably sometime today or tomorrow) master will go back to playing nicely.

**Comment by zsherman** [comment]
Got it, thanks!
