### ISSUE TITLE
Creating Collapsable rows in Table

### ISSUE THREAD

**Issue by amitripshtos** [bvaughn/react-virtualized#452]
Hey!
Thank you so much for this epic library, pure awesomeness!

I'm using the Trade component and I`m trying to create collapsible rows.
How my data looks:
```
[
  {
    "name": "first row",
    "childs": [
       {"name": "first child"}
       {"name": "seconds child"}
    ]
  }
]
```

I want to have a table that will have that are clickable, and when they are clicked - the childs for the specific row will appear (I can use Table of childs in order to show them)

So when I`m trying to show the childs in the rowRenderer, it won't work well because of CSS flex issues.

So I have 2 problems:
1. I don't know how to the row height when I`m showing childs, because it changes when I open/close rows
2. I can`t make the rowRenderer show things under the row columns itself.

A good example of what I want to achieve is:
https://datatables.net/examples/api/row_details.html

the childs have the same columns are as the parent, so they should be like the tables columns (ofc I don't need to sort them or something)

I would love to get some help here, thank you very much in advance.
Amit.

**Comment by bvaughn** [comment]
The link you pasted above is probably not something that `Table` should be used for, since the expanded state doesn't contain columns but rather some sort of list. I suggest using the `List` component for this. I think it would be easier for you to manage the children that way.

[here is an example using `List`](https://rawgit.com/bvaughn/react-virtualized/master/playground/tree.html) that I think is similar to what you're trying to do. (The source code for that can be found [here](https://github.com/bvaughn/react-virtualized/blob/master/playground/tree.js) as well.) It's more of a tree view but it shows _one_ way to manage the expanded/collapsed state with a `List`.

This isn't really an actionable Github issue. It's just asking for advice 😄 which is fine, but probably better done on Stack Overflow or somewhere more people are likely to respond than _just me_. I recently started a new job and I have less time than I used to to help with stuff like this. So I'm going to close this issue here and suggest you move follow-up discussion to SO or _maybe_ the react-virtualized Gitter channel where others can help as well. 😄 Hope you understand!
