### ISSUE TITLE
Problem with WindowScroller when List element offset from top increases

### ISSUE THREAD

**Issue by caliber01** [bvaughn/react-virtualized#489]
Hello, first of all thanks for the great library.

I want to use react-virtualized **List** component with **WindowScroller** and this list on my page is below another card-based list with unknown height. The problem is that when the height of any element above List changes, List starts to render items wrongly. I have created a plnkr to demonstrate this (Initially rendering works perfectly, but after adding some offset it breaks). Is it a bug? Thanks.

https://plnkr.co/edit/7hKDO01BrUpeuapgfNm6

**Comment by bvaughn** [comment]
This is a use-case that `WindowScroller` does not handle. It has no reasonable way to watch for changes to the size and/or position of other elements in the DOM that our above or adjacent to it.

Currently `WindowScroller` checks its position on the page [when it is mounted](https://github.com/bvaughn/react-virtualized/blob/d44dde177ef7d6fe99c74228d0fed2e00b202b5a/source/WindowScroller/WindowScroller.js#L46-L59). This check could be moved into a public method so that you could call it again if you think the position has changed. (If you'd be willing to submit a PR for that, I'd accept it.)

Anything more than that would probably not be appropriate for this component.

**Comment by bvaughn** [comment]
I will go ahead and fix this myself.

**Comment by bvaughn** [comment]
This has been fixed in version 8.7.0

You will now need to call the `updatePosition` if your header changes. It will automatically be called on-mount as well as when the window resizes.

**Comment by caliber01** [comment]
Thank you so much!
