### ISSUE TITLE
CellMeasurer prop validation

### ISSUE THREAD

**Issue by pmuilu** [bvaughn/react-virtualized#504]
Would it make sense to validate the CellMeasurer props, especially whether width or height prop exists? I guess either of them should always exist? 

I accidentally removed the width property and wasted several hours debugging why some of the components overlapped each other. It was pretty hard to figure out as I first thought that it was a style issue.

**Comment by pmuilu** [comment]
Also, I suspect there might be a bug in CellMeasurer, it can be reproduced with chat playground script  by changing the font-size to e.g. 24px and adding lengthier messages to SENTENCES array (e.g. 500 words). Then just click to resize and text elements overlap. Is this a known issue?

**Comment by bvaughn** [comment]
>Would it make sense to validate the CellMeasurer props

Both props are [already validated](https://github.com/bvaughn/react-virtualized/blob/488b7eb0dc1c56d30b5007094745ee56a7d479da/source/CellMeasurer/CellMeasurer.js#L12-L59).

> especially whether width or height prop exists? I guess either of them should always exist?

`CellMeasurer` can work with a fixed width (if you want to measure height only), a fixed height (if you want to measure width only), or neither at all (if you want to measure both dynamically).

> Also, I suspect there might be a bug in CellMeasurer, it can be reproduced with chat playground script by changing the font-size to e.g. 24px and adding lengthier messages to...

I suspect you may be referring to [what's covered here](https://github.com/bvaughn/react-virtualized/blob/488b7eb0dc1c56d30b5007094745ee56a7d479da/docs/CellMeasurer.md#styling). If not, please submit a focused, follow-up issue about that only and include a Plnkr (or similar repro case) so I can verify the bad behavior. 😄 

I'm going to close this issue because I don't think there's anything actionable here. We can keep chatting though. I'll still see and respond to comments!
