### ISSUE TITLE
angular porting

### ISSUE THREAD

**Issue by istiti** [bvaughn/react-virtualized#512]
kind of enhancement: 
I know i don't make me friends by saying that here but this lib is awesome what about porting it to angular (2 and +)?

**Comment by bvaughn** [comment]
Made a proof of concept at one point: https://github.com/bvaughn/ng2-virtualized

Short answer: This project is maintained by an individual. It's not my day job (because it doesn't pay). I don't work with Aguilar 2 so I wouldn't be a good maintainer of a library written for it. If anyone from the angular community wanted to own the port- then we could talk about collaboration, sure.

But I'm not doing it.

**Comment by bvaughn** [comment]
> but this lib is awesome 

PS Thanks!
