### ISSUE TITLE
Add scrollToIndex support for WindowScroller

### ISSUE THREAD

**Issue by bvaughn** [bvaughn/react-virtualized#540]
I has been [reported](https://github.com/bvaughn/react-virtualized/issues/147#issuecomment-272864392) that `Grid` does not support the `scrollToIndex` property when used with `WindowScroller`. Let's investigate if it is possible to add support for this use case.

cc @tiberiumaxim: If you have questions, we can discuss them here or on [Gitter](https://gitter.im/bvaughn/react-virtualized).

**Comment by tiberiumaxim** [comment]
Thank for opening this. I think it would be best to start by adding some info about where to start this thing.

Where do you think it's the problem that's stopping `Grid` from scrolling to the index?
Is this a bug, should it work and it isn't or is it a brand new feature that needs to be implemented?
Any other thoughts would be highly appreciated since I'm not familiarised at all with the module. And if I won't be able to help with this maybe it will be useful for any other people willing to have a look. Thanks

**Comment by tiberiumaxim** [comment]
I started by creating a plunkr for my issue: https://plnkr.co/edit/C7GcrEWQMEFNqtqr0obk

As you can see, the `scrollToIndex` prop is set on the `List` with value of `40`. When the list gets rendered, the first 39 rows are not rendered, resulting in white space. Then, right under the fold, the rows starting with the `40`th are rendered. I checked this using the browser's inspector.

If you remove the `scrollToIndexProp`, the list renders with no problems.

Any help would be much appreciated.

**Comment by bvaughn** [comment]
Well, the problem you'll have to solve in order to implement this feature basically boils down to this:

Normally a user scrolls _within_ a `Grid`; `Grid` listens to scroll events and updates what it displays. When a user sets a prop like `scrollToIndex`- `Grid` determines what the offset of that row would be and updates the scroll position so that it's visible.

`WindowScroller` changes the rules a bit. Its purpose is to enable a page to scroll _outside of_ `Grid` so that other page elements can scroll too. It listens to scroll events and tells `Grid` which offset it should display visible data at.

The problem is this: `WindowScroller` is listening to the `window` object for scroll events. When you set a `scrollToIndex` prop, `Grid` updates _its own_ scroll offset (and then renders new rows). `WindowScroller` _isn't listening_ to `Grid` and so the page isn't scrolled to show the newly rendered rows.

I haven't thought much about this problem because, as I mentioned previously, I don't use `WindowScroller`. 😄

**Comment by jplee91** [comment]
Hi,

I'm assuming if I wanted to implement this on any other components that had scrollToIndex such as `List`, I would need to solve the same issue?

**Comment by bvaughn** [comment]
Sorry. Did not see this comment.

`List` and `Table` both use `Grid` internally, so yes. Unless we solve it on `Grid` and it will not work for those either.

**Comment by bvaughn** [comment]
It's been a while since we've talked about this issue- (totally fine by the way, there's no pressure here). But I don't like leaving tasks open that I don't plan to tackle- and this one isn't a use case I really care to support. So I'm going to close this issue for now.

Still happy to chat about design ideas for supporting it though, if you're ever interested in putting together a PR in the future. 😄

**Comment by Bertg** [comment]
Hello, we have run into a related issue:

**Setup:** 

* ```WindowScroller``` + ```InfiniteScroller``` + ```List```
* ```InfiniteScroller``` only appends items to the bottom (only vertical scrolling)
* We use ```scrollToIndex``` (to follow the selection around with arrow navigation. Allowing the user to brows the infinite loading list with their keyboard. This is combined with ```scrollToAlignment: 'auto'```

**What goes wrong:** 

* When a scrolling to the bottom of the list (before the next section is loaded) everything is fine. However when the next items are loaded, the bottom rows do no longer get rendered. In debugging we found that the ```scrollTop``` outputted by ```onScroll``` value decreases a lot. As if it tries to scroll back to that position (although it did not change)
* When changing the ```scrollToIndex``` value, we see the correct rows being loaded in the DOM. However, the scroll offset is not following along. Causing the user to see rows disappearing. 

**Countermeasures so far:** 

In order to prevent the first issue we do the following: 
When rendering we check if the desired ```scrollToIndex``` value has changed since the last render. If it has we pass the ```scrollToIndex``` and ```scrollToAlignment``` values to the ```List```. If the value has not changed, we do not do this.

We have no solution For the other issue at this point.

**2  possible solutions:** 

* Let ```WindowScroller``` know about ```scrollToIndex```. However, this also means that somehow it has to become aware of rowHeight etc... This would be annoying.
* Create feedback loop between ```WindowScroller``` and ```List```. ```WindowScroller``` provides a function that ```List``` accepts as a property. When ```List``` wants to change it's ```scrollTop``` because of internal reasons (e.g.: ```scrollToIndex``` changes) it invokes this method (instead of changing ```scrollTop```) with either the new desired value (or the delta) so the parent component can update the ```scrollTop``` value, and pass it down again.  (this is a similar relation as between ```InfiniteLoader``` and ```List```, where ```InfiniteLoader``` sends functions to ```List``` instead of values.

Does that make sense? Also, Is this clear? :p 

I currently have no time to set up a test case, I can try later if that would be useful.

**Comment by Bertg** [comment]
I've solved the second case now as well.
Here is a (part) of my solution

* I tried to remove as much non relevant code as possible)
* The solution for the first problem mentioned in my previous comment is in here as well
* Added a few lines of comment

First we need a new WindowScroller:

```jsx
class WindowScrollerWithFeedback extends WindowScroller {

  constructor (props) {
    super(props)
    this.childScrollChange = this.childScrollChange.bind(this)
  }

  childScrollChange ({scrollTop}) {
    console.log(`childScrollChange: ${scrollTop}`)
    const currentScrollTop = this.state.scrollTop,
      scrollElement = this.props.scrollElement || window
    /* Scroll to the correct position, and update the state */
    scrollElement.scrollBy(0, (scrollTop - currentScrollTop) - this._positionFromTop)
    this.setState({scrollTop})
  }

  render () {
    const { children } = this.props
    const { isScrolling, scrollTop, height } = this.state

    return children({
      height,
      isScrolling,
      scrollTop,
      childScrollChange: this.childScrollChange
    })
  }
}
```

This is now our new component:  

```js
  const InfiniteList = React.createClass({

  rowHeight: 250,
  scrollToIndex: null,

  shouldComponentUpdate(nextProps, nextState) {
    return shallowCompare(this, nextProps, nextState)
  },

  render() {
    const {
      loadingNextPage,
      loadMoreRows,
      resources,
      refreshId = 'nill',
      scrollToAlignment = 'auto',
      style: listStyle,
      scrollToIndex,
      scrollTop,
      width,
      height,
      autoHeight,
      childScrollChange
    } = this.props

    const updateScollToIndex = this.scrollToIndex !== scrollToIndex
    this.scrollToIndex = scrollToIndex

    return (
      <InfiniteLoader
        isRowLoaded={this.props.isRowLoaded}
        loadMoreRows={loadingNextPage ? () => {} : loadMoreRows}
        rowCount={this.props.rowCount}
        threshold={4}>
        {
          ({onRowsRendered, registerChild}) => {
            let scrollOffset = {}

            /* Prevent the undesired re-positioning when infinite list changes the rendered collection  */
            if (isNumber(scrollToIndex) && updateScollToIndex) {
              scrollOffset = {
                scrollToIndex: Math.floor(this.scrollToIndex / this.columns),
                scrollToAlignment
              }
            }
            return (
              <List
                ref={registerChild}
                onScroll={(props) => {
                  console.log(props)
                  const {scrollTop: myScrollTop} = props
                  if (myScrollTop !== scrollTop) {
                    console.log(`innerChange: ${myScrollTop} <=> ${scrollTop}/given`)
                    childScrollChange({scrollTop: myScrollTop})
                  }
                }}
                onRowsRendered={onRowsRendered}
                width={width}
                height={height}
                autoHeight={autoHeight}
                {...scrollOffset}
                scrollTop={scrollTop}
                rowCount={this.props.rowCount}
                rowHeight={this.rowHeight}
                rowRenderer={this.props.rowRenderer}
                tabIndex={null} />
            )
          }
        }
      </InfiniteLoader>
    )
  }
})
```

Combined: 

```js
const WindowScrolledAutoWidthComponent = (props) => (
  <WindowScrollerWithFeedback>
    {({height, scrollTop, childScrollChange}) => (
      <AutoSizer disableHeight>
        {
          ({width}) => {
            const sizeInfo = {width, height, scrollTop, childScrollChange, autoHeight: true}
            return <InfiniteList {...sizeInfo} {...props} />
          }
        }
      </AutoSizer>
    )}
  </WindowScrollerWithFeedback>
)
```

**Comment by Bertg** [comment]
Last followup here to our solution. Although it "works" the performance was just not good enough. So we Dropped the ```WindowScroller``` aspect of our feature set (sadly).

I would still be interested to help. I'd still like some architectural guidance form @bvaughn on how to approach this.

**Comment by bvaughn** [comment]
Unfortunately I don't have time to really dig into or think about this at the moment. I'd welcome a contribution if you'd like to dig into it and submit a PR, but I don't have the bandwidth to offer any architectural guidance on it. Sorry!
