### ISSUE TITLE
Can't understand how InfiniteLoader + Grid decides when to stop fetching data

### ISSUE THREAD

**Issue by machineghost** [bvaughn/react-virtualized#573]
# Are you asking a question?

Yes.

However, I tried asking the question on Stack Overflow (http://stackoverflow.com/questions/42170643/how-can-i-debug-react-virtualizeds-infinitescroll-grid-fetching) and got no response.  I believe it is because my question is tied too closely to the inner workings of React Virtualized, and therefore is too specific for (the more general purpose) Stack Overflow.  Therefore I was hoping I could trouble you for (what I imagine) will be a quick answer to a very vexing question.

The Stack Overflow question lists the details of my problem, but essentially my `InfiniteLoader` + `Grid` is stopping its fetching of data long before it hits the provided `rowCount`.  I know my code is to blame (if I change my `isRowLoaded` function to always return false it "fixes" things), but since I believe I'm following the same pattern described in the `InfiniteLoader`/`Grid` example, I can't figure out what I'm doing wrong.

I've tried to work through the `InfiniteLoader`/`Grid` source code (for more than a day now), but the interplay between the two components, plus the heavy use of the memoizers has made it difficult for me to understand something very basic: how do the two components, in conjunction, decide to stop fetching new rows?  My hope is that this will be a simple and easy-to-answer question to someone familiar with the code, and I believe once I have it I should be able to determine what my code is doing wrong to break the logic.

**Comment by bvaughn** [comment]
I suggest waiting longer than 1 hour after asking a StackOverflow question before filing a Github issue 😄 That's really a very short time to get an answer to a question as complex as yours. I would also strongly suggest attaching a Plnkr to your SO post so people can see what you're describing, set breakpoints, step through, etc. It will be much easier to get help that way.

Despite an understanding of the inner workings of react-virtualized, I can't even answer your question without seeing your application code- since the misunderstanding is almost certainly there.

I'm going to close this issue. (As the issues template says, Github issues aren't for asking questions. That doesn't scale. It's just me responding to these and I can't keep up.) Update your SO post and give it a little time. I also regularly check SO for react-virtualized questions.
