### ISSUE TITLE
Columns didn't align properly on iOS 8.4

### ISSUE THREAD

**Issue by lyf1988** [bvaughn/react-virtualized#578]
I am developing a web app using react, and planning to support iOS version down to iOS8.
But I found the Columns did't display properly on iOS8, it seems aligned left instead of display like a table.
If iOS 8 safari is out of support list, please just close this. 
Thank you all for providing such good looking and easy to use components.

## This is the Screen shot from OSX simulator using safari on iPhone 6 Plus - iOS 8.4.
![simulator screen shot 14 feb 2017 03 23 12](https://cloud.githubusercontent.com/assets/11595729/22913799/e5adcaa8-f264-11e6-879a-beb4fc5e03ed.png)

## This is same page on iPhone 6 Plus - iOS 9.0
![simulator screen shot 14 feb 2017 03 30 59](https://cloud.githubusercontent.com/assets/11595729/22913946/d6e1429c-f265-11e6-92fa-d9fce2affda1.png)

**Comment by clauderic** [comment]
### Issue:
Looks like this is because of the current [autoprefixer config](https://github.com/bvaughn/react-virtualized/blob/ea90d300739009dffc08513d0b150f49aac90177/webpack.config.umd.js#L42) being set to last 2 versions. 

I went ahead and tested in iOS 8.4 on the simulator and indeed replicated the same behavior on the demo site. 

Here's what the generated prefixed CSS currently looks like for `Table__row`:

<img width="1344" alt="screen shot 2017-02-15 at 12 18 01 pm" src="https://cloud.githubusercontent.com/assets/1416436/22986286/fd977b18-f378-11e6-9d7f-6f829181b2b8.png">

Notice it's falling back to `display: -webkit-box;`, which seems to behave differently on Safari iOS 8 and prior.

If I go ahead and set it to `display: -webkit-flex;` all is well:

<img width="1343" alt="screen shot 2017-02-15 at 12 18 35 pm" src="https://cloud.githubusercontent.com/assets/1416436/22986353/35e312ac-f379-11e6-9de2-afa6beaf80e6.png">

### Possible solutions
@bvaughn Happy to submit a small PR for this if you feel like updating the autoprefixer config is the right way to go here. 

Alternatively @lyf1988, if you're using a module bundler like webpack, you can always use your own Autoprefixer config in your webpack loader configuration for `css` files.

**Comment by bvaughn** [comment]
Good catch @clauderic!

If it's as simple as nudging the autoprefixer config, I'd be happy to accept a PR 😄

**Comment by bvaughn** [comment]
Fixed with PR #580 (thanks @clauderic!) and will go out soon with 9.0.0

**Comment by bvaughn** [comment]
PS just pushed another RC (2) with this change if you'd like to test early~ `npm i react-virtualized@next`
