### ISSUE TITLE
Support for onScroll callback for VirtualScroll

### ISSUE THREAD

**Issue by aquach** [bvaughn/react-virtualized#60]
It'd be super useful to be able to set a callback to be called whenever the virtual scroll container has been scrolled. As far as I know, it should be passed in through props. Is there already an existing way to do this that I'm not aware of?

**Comment by bvaughn** [comment]
Hi @aquach,

Correct me if I'm wrong, but you should be able to use the `onRowsRendered` callback (supported by `FlexTable` and `VirtualScroll`) for this purpose. I suspect what you care about is the range of rows rendered (or the fact that they've changed) and not the actual scroll position.

This callback's signature is expected to be: `({ startIndex, stopIndex }): void`

Going to close this issue as answered (because I think it is) but please comment again if you have more questions or if this isn't an adequate answer. :)

**Comment by aquach** [comment]
I actually need it to support our existing in-house infinite loading code, which checks to see if one's scrolled close to the bottom of available content. I suppose onRowsRendered is a more quantized way to do that. If implemented via onRowsRendered, it may interact poorly with #53. If many extra elements are rendered, the client may not be able to use onRowsRendered to reliably detect scrolling close to the end of the content.

**Comment by bvaughn** [comment]
Have you considered using the [`InfiniteLoader`](https://github.com/bvaughn/react-virtualized/blob/master/docs/InfiniteLoader.md) component for this? (Sorry if we've already talked about this.)

The implementation for #53 will allow you to configure the number of overflow rows rendered, so you would have to take that into account within your own `onRowsRendered` callback.

**Comment by aquach** [comment]
Our infinite loading is date-based rather than index-based and comes with a bit of extra domain logic, so integrating the infinite loader would take some extra effort. We opted to stick with what we already had. Thanks for asking though!

**Comment by bvaughn** [comment]
I see. Always interesting to hear about different project's requirements. :)

I do strongly prefer the use of the `onRowsRendered` callback for this purpose though. I'd rather avoid adding another callback for scrolling because I think it may muddy the interface and confuse people. (Ideally no one should care about the inner dimensions/offsets of virtualized components, only which rows are visible at any given time).

Let's chat again once I've got an implementation for #53 up though and we'll see if we can't work something out. :)

**Comment by aquach** [comment]
Sure thing, thanks for being so responsive!
