### ISSUE TITLE
We are getting a random error which we can't reproduce but we have it in our Sentry

### ISSUE THREAD

**Issue by vojtatranta** [bvaughn/react-virtualized#619]
Error we get:
```
Requested index 0 is outside of range 0..0
```
Which is clearly a nonsense.

**Comment by bvaughn** [comment]
Sorry mate. This issue isn't actionable. That error could be occurring anywhere- in your application code, in another 3rd party lib (that isn't react-virtualized), etc.

If you can narrow it down to the point where you're sure it's caused by react-virtualized, then please follow the Github issue template instructions:

### Are you reporting a bug or runtime error?
Please include either a failing unit test or a Plnkr demonstrating the bug you are reporting. You can start by forking this Plnk! https://plnkr.co/edit/6syKo8cx3RfoO96hXFT1
