### ISSUE TITLE
Horizontal scrollbar starting too wide

### ISSUE THREAD

**Issue by andrew8088** [bvaughn/react-virtualized#620]
Pretty sure this is a bug, but I might be doing something wrong. Here's the demo: [https://jsfiddle.net/69z2wepo/73926/](https://jsfiddle.net/69z2wepo/73926/)

As you scroll to the right, the horizontal scrollbar gets smaller, until it gets to the correct size, based on the size/number of columns. I'm seeing this when using the MultiGrid, but as the demo shows, it's really a Grid issue.

**Comment by bvaughn** [comment]
It's actually not a bug. It's a feature. `Grid` uses estimated sizes for cells initially to avoid having to explicitly measure them all. This is an important performance optimization, particularly when `CellMeasurer` is used. And as a use scrolls through content, and more cells are _actually_ measured, the total scroll size is updated gradually. For large lists, this usually isn't noticeable because the update is so small each time. In your example it's more noticeable because there are only 6 columns.

You can improve the accuracy of the estimate (if you'd like) by specifying your own `estimatedColumnSize` property in this case.

Here's a graphic I made that illustrates what's happening in case it's helpful:

![screen shot 2017-03-20 at 1 30 58 pm](https://cloud.githubusercontent.com/assets/29597/24120343/7abf4794-0d71-11e7-9ac2-77efd36dd5e5.png)

**Comment by andrew8088** [comment]
Ah, that makes sense. Thanks, and thanks for a great library!

**Comment by bvaughn** [comment]
You're welcome 👍
