### ISSUE TITLE
v9.4.0 AutoSizer no longer works if `disableHeight` and `disableWidth` are on

### ISSUE THREAD

**Issue by EvNaverniouk** [bvaughn/react-virtualized#631]
After upgrading to v9.4.0 the AutoSizer isn't working as before. In my case I want both `disableHeight` and `disableWidth` set to `true` since I don't want the AutoSizer container element so specify a size (I want to control this by my own wrapper container).

But with both of those props set to `true` the AutoSizer will always send 0 values as the state of its children. I've tracked this down and it's due to this line in `AutoSizer.js`:

```javascript
if (!disableHeight && this.state.height !== newHeight || !disableWidth && this.state.width !== newWidth) {
```

Changing this to:

```javascript
if (this.state.height !== newHeight || this.state.width !== newWidth) {
```

Fixes the issue for me.

Here's a Plnkr demo illustrating the issue: https://plnkr.co/edit/gs0zDBmK7ZOJTFIxsN65?p=preview

The AutoSizer was able to support what I need in v9.3.0. Was this an intentional change or an oversight?

**Comment by bvaughn** [comment]
> In my case I want both `disableHeight` and `disableWidth` set to true since I don't want the `AutoSizer` container element so specify a size (I want to control this by my own wrapper container).

Then don't use `AutoSizer`. It's introducing complexity and runtime cost for no reason at all. The only purpose of this component is to observe size/resize of a parent container and pass through the width/height to its child. If you are hard-coding (or otherwise managing) the width and height, there's no reason to introduce the runtime cost of `AutoSizer`.

Am I misunderstanding something?

> The `AutoSizer` was able to support what I need in v9.3.0. Was this an intentional change or an oversight?

This was an intentional optimization to reduce unnecessary renders and potential cache invalidation. It's mentioned in the [CHANGELOG](https://github.com/bvaughn/react-virtualized/blob/master/CHANGELOG.md#940). If a child is only interested in the width value of `AutoSizer` then that's probably because it has a hard-coded height. As such, changes to the `AutoSizer`'s parent height should not trigger a resize callback for the child.

**Comment by bvaughn** [comment]
(Closing for now because I feel, based on your description, that this isn't a bug. We can talk more though!)
