### ISSUE TITLE
Different scroll behavior

### ISSUE THREAD

**Issue by sapottier** [bvaughn/react-virtualized#647]
Hello,

First of all, sorry for my english…

With scrollSync, I'm encounter a different behavior (bug) between scrolling with the mouse wheel and dragging the scrollbar.

While dragging, everything is properly sync but not when I'm using the mouse wheel. this can take a while.

I think (maybe) you can prevent this by preventing the default behavior of onmousewheel and DOMMouseScroll. This events are executed before the onScroll.

thank you,

Simon

**Comment by bvaughn** [comment]
Hi Simon,

I think there's some misunderstanding here. Firstly, browsers manage scroll events in a separate thread from the one JavaScript runs in. JavaScript is periodically notified of "scroll" events and can respond without blocking the momentum scrolling animation.

On the other hand- wheel and touch events (and dragging the scroll track thumb)- are handled synchronously.

This can make things feel a little more responsive sometimes but it can also cause significant performance problems if your wheel event handler is slow. The proposal for adding a "wheel" handler to bypass the "scroll" handle would also cause a performance hit. Just adding a "wheel" event listener can have negative performance impact (see [here](https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md)).

The async "scroll" event is good on the other hand because- although the animation can get ahead of JS sometimes- this allows the page to continue feeling responsive to user input (eg scrolling).

I recently gave a talk about this and the slides ([here](https://bvaughn.github.io/forward-js-2017/#/23/2)) offer a visual explanation of what's happening with the scroll event.

**Comment by sapottier** [comment]
Hi,

I understand, thank you. I already reduced elements rendered into cells, now, has you explain, I will rendering less data while scrolling.

Thank you again,

Simon

**Comment by bvaughn** [comment]
Great! 👍
