### ISSUE TITLE
Fixed columns in MultiGrid aren't scrollable

### ISSUE THREAD

**Issue by cp** [bvaughn/react-virtualized#648]
Hello! I recently brought this up in the Slack channel and wanted to file a ticket here as a way to document the issue to reference internally at my company, as well as possibly start a discussion here.

When using `MultiGrid`, fixed columns (i.e. the `lowerLeftGrid`) aren't scrollable. As Brian mentioned in Slack this was a technical limitation caused by issues using `ScrollSync` to sync 2 grids. This begins to be an issue when anywhere between a good amount of our columns are fixed: it's not obvious to the user that they can't scroll on them.

I recently tried out a potential fix locally, and only found a couple small issues when syncing two `Grid`s. I'm planning on fixing them and opening a PR unless there's any objections.

**Comment by bvaughn** [comment]
Happy to review a PR that fixes this!

**Comment by bvaughn** [comment]
No time pressure on this or anything. But since it's not on my plate, I'm going to clear it out of the open issues list. If you find time to submit a PR for this I'll be happy to review it!

**Comment by fc** [comment]
hey @cp fellow two letter Github user, any luck with a PR on this?

**Comment by danalloway** [comment]
@cp any update on this? want to explore a fix as well and would love for a head-start based on what you've found so far, care to share?

**Comment by karmajunkie** [comment]
+1 for a PR on this, or even just some notes about how to solve it...

**Comment by danalloway** [comment]
https://github.com/danalloway/react-virtualized/tree/scroll-fixed-sections

**Comment by danalloway** [comment]
when MultiGrid is in fixed mode (cols, rows or both) the grid section that is fixed needs an `onScroll` property, but it can't use the one that the main content grid uses because that updates both`scrollLeft` and `scrollTop`.

so two new methods are needed `_onScrollLeft` and `_onScrollTop`, that handle updating each value independently

`_onScrollLeft` is what a fixed row will use
and `_onScrollTop` is what a fixed column will use

after that we adjust the styles for each section to allow overflow visibility in the proper direction and you should have a basic working example of fixed section scrolling

**Comment by bvaughn** [comment]
I'm still happy to _review_ a PR for this but don't plan to take any action on _creating_ one myself. :smile:

**Comment by danalloway** [comment]
#708

**Comment by cp** [comment]
Hey friends, sorry about the lack of update here from me. Unfortunately I went back to using HTML tables as opposed to RV, and wasn't able to find a reasonable path forward with this issue. Best of luck.
