### ISSUE TITLE
scrollTop not working if rendered with 0 items

### ISSUE THREAD

**Issue by omerts** [bvaughn/react-virtualized#659]
Hey,

Thanks for the great lib.

I am trying to set the scrollTop prop on a List that is wrapped by an InfiniteScroller. During the first render the list's rowCount is 0, and after that all scrollTop is ignored, and always stays at 0.

In https://github.com/bvaughn/react-virtualized/blob/master/source/Grid/Grid.js, line 596:
```javascript
componentWillReceiveProps (nextProps) {
    const { scrollLeft, scrollTop } = this.state

    if (
      nextProps.columnCount === 0 &&
      scrollLeft !== 0 ||
      nextProps.rowCount === 0 &&
      scrollTop !== 0
    ) {
      this._setScrollPosition({
        scrollLeft: 0,
        scrollTop: 0
      })
    }
```
Since nextProps.rowCount === 0, and scrollTop !== 0,  _setScrollPosition is setting scrollTop to 0, and now since my scrollTop never changes always staying at a constant number (>0), scrollTop is never set again. 

Here is a fiddle:
https://jsfiddle.net/omerts/qcrg17md/

**Comment by bvaughn** [comment]
Hey @omerts,

Thank you!

Looks like you found a bug. ☹️ At least a glance, I'm pretty sure that check should be:
```js
    if (
      nextProps.columnCount !== 0 &&
      scrollLeft !== 0 ||
      nextProps.rowCount !== 0 &&
      scrollTop !== 0
    ) {
```

I'll try to find time to fix this soon. In the meanwhile, you could work around this issue by using the [`scrollToPosition`](https://github.com/bvaughn/react-virtualized/blob/master/docs/List.md#scrolltoposition-scrolltop-number) API method.

**Comment by omerts** [comment]
@bvaughn I think the rowCount check was actually correct, i think it is meant to set the scrollTop to 0, when there are no items, but there is a scrollTop. 
I didn't mention it in the issue, but from a second look, I think the issue is on line 611:
```javascript
else if (
      nextProps.scrollLeft !== this.props.scrollLeft ||
      nextProps.scrollTop !== this.props.scrollTop
    )
```
I think it should be changed to:
```javascript
else if (
      nextProps.scrollLeft !== this.props.scrollLeft ||
      nextProps.scrollTop !== scrollTop
    )
```

**Comment by omerts** [comment]
I don't mind creating a pull request for the change, I just don't feel familiar enough with the code, to make sure this will not cause some regression bugs

**Comment by bvaughn** [comment]
Ah, you are right about the first issue. I misread (distracted working on something else).

The second check can't be changed, since `scrollTop` (and `scrollLeft`) props are meant to function more as... default values, rather than true controlled props. The change you've suggested would cause a `List` to be snap-locked to the offset specified. (Anytime the state changed in response to a user scroll, the next prop-change would snap it back.)

It's a bit tricky/unfortunate, but I kind of backed myself into a corner with the API design. ☹️

You can use the API method I mentioned above to work around this _or_ you could refrain from setting `scrollTop` until the `List` has some rows. Unfortunately I think those are the only 2 options without a major refactor- so I'm going to close this issue for now. Happy to keep discussing it though.

**Comment by omerts** [comment]
@bvaughn I understand, thank you very much for the super-quick support. Great library!

**Comment by bvaughn** [comment]
You're welcome 😄
