### ISSUE TITLE
MultiGrid with fixedRowCount is rendering incorrect width.

### ISSUE THREAD

**Issue by marcelmokos** [bvaughn/react-virtualized#660]
Using MultiGrid when the render with fixedRowCount then some of the columns do not render with width from the CellMeasurerCache.

Basically, the column has `width: auto;` instead of for example`width: 150;`. This problem is not showing every time more likely is the problem visible on larger tables and the problem and row on which it occurs is random as well. (Tested on mac in chrome, and firefox).

Am I missing something that can cause this problem? 

![widthauto](https://cloud.githubusercontent.com/assets/6388074/25433247/fb228cec-2a87-11e7-889e-6ceb37592894.png)

**Comment by bvaughn** [comment]
Hi @marcelmokos,

Unfortunately I need more than a screenshot to help diagnose a problem.

Please provide a Plnkr that shows the issue you're encountering and I'll be happy to take a look. In the meanwhile I'm going to close this issue since it's not really actionable.

> ### Are you reporting a bug or runtime error?
> Please include either a failing unit test or a Plnkr demonstrating the bug you are reporting. You can start by forking this Plnk! https://plnkr.co/edit/6syKo8cx3RfoO96hXFT1
>
> You may also find the online Babel tool (https://babeljs.io/repl/) quite helpful if you wish to use ES6/ES7 syntax not yet supported by the browser you are using.

In the meanwhile you may also want to check out [this demo page](https://bvaughn.github.io/react-virtualized/#/components/CellMeasurer)- specifically [the source for the page](https://github.com/bvaughn/react-virtualized/blob/master/source/CellMeasurer/CellMeasurer.DynamiWidthMultiGrid.example.js)- to for an example of using `CellMeasurer` with `MultiGrid`.
