### ISSUE TITLE
Wrap 'prop-types' usage in environment check conditional

### ISSUE THREAD

**Issue by romulof** [bvaughn/react-virtualized#682]
There's a nice Babel plugin called `babel-plugin-transform-react-remove-prop-types` that automatically removes React propTypes. Very good for production, but not for development.

Libraries are normally distributed compiled, and people normally don't apply Babel to `node_modules`, thus not removing propTypes from external libraries.

Solution: libraries should wrap their `prop-types` usage in `if (process.env.NODE_ENV !== 'production) { ... }`, and that Babel plugin does this too.

Just add to your `.babelrc`:
```
"plugins": [
  ["transform-react-remove-prop-types", {
    "mode": "wrap"
  }],
  ...
],
```

I can make a PR this weekend.

**Comment by bvaughn** [comment]
I don't understand. Aren't I already doing this? What about the current approach doesn't work?

RV already uses `transform-react-remove-prop-types` and its components currently define their `propTypes` like so:
```js
process.env.NODE_ENV !== "production" ? Grid.propTypes = {...} : void 0;
```

Check out the [`.babelrc`](https://github.com/bvaughn/react-virtualized/blob/master/.babelrc) file which already contains:
```js
      "plugins": [
        [
          "transform-react-remove-prop-types", {
            "mode": "wrap"
          }
        ]
      ],
```

I assume for now this issue was just filed as a misunderstanding so I'm going to close it. :)

**Comment by romulof** [comment]
I'm having some serious problem with webpack :/

![unknown](https://cloud.githubusercontent.com/assets/1225889/26276840/56b3f1dc-3d56-11e7-9438-f87fa22384ac.png)

**Comment by bvaughn** [comment]
:(
