### ISSUE TITLE
AutoSizer inside another AutoSizer returns width 0 height 0

### ISSUE THREAD

**Issue by brunolemos** [bvaughn/react-virtualized#684]
### Reproduction

https://plnkr.co/edit/XLG1FZIolxx74xRj2WxP?p=preview

```jsx
<div style={{ width: 400, height: 400 }}>
  <AutoSizer>
    {calculated => {
      console.log('calculated1', calculated)

      return (
        <div style={{ width: '100%', height: '100%' }}>
          <AutoSizer>
            {calculated => {
              console.log('calculated2', calculated)
            }}
          </AutoSizer>
        </div>
      )
    }}
  </AutoSizer>
</div>
```

## Current behaviour

```
calculated1 Object {height: 0, width: 0}
calculated2 Object {height: 0, width: 0}
calculated1 Object {height: 400, width: 400}
calculated2 Object {height: 0, width: 0}
```
## Expected behaviour

```diff
calculated1 Object {height: 0, width: 0}
calculated2 Object {height: 0, width: 0}
calculated1 Object {height: 400, width: 400}
-calculated2 Object {height: 0, width: 0}
+calculated2 Object {height: 400, width: 400}
```

**Comment by bvaughn** [comment]
Hey @brunolemos! Thanks for the detailed report and Plnkr!

In your Plnkr both the `body` and the `<div id="example">` have a height of 0. The docs [briefly cover this](https://github.com/bvaughn/react-virtualized/blob/master/docs/usingAutoSizer.md#why-is-my-autosizer-setting-a-height-of-0). The tl;dr is that you can fix the outer-most `AutoSizer` by appending the following CSS to your Plnkr:

```css
html, body, #example {
  height: 100%;
}
```

You can fix the inner-most `AutoSizer` using `style={calculated}` instead of `style={{width: '100%', height: '100%'}}`. I'm not sure off the top why the former doesn't work but...nested `AutoSizer`s doesn't seem to be a very common case so I'm inclined to say that I'm not going to prioritize looking into it since a workaround exists.

If you would look to look into it and submit a PR though I'd be happy to review it. 😄 

For now I'm going to close this issue since I don't plan to take any action on it. (We can still keep chatting here though if you have any follow up questions or comments.)

**Comment by brunolemos** [comment]
Thanks @bvaughn. I think I mistakenly narrowed down the issue. Apparently my problem seems to be CellMeasure inside another CellMeasure. But when I'm sure about it I'll post here or on stack overflow.

I know one inside another sounds weird, but it's because I'm implementing a trello-like layout.
@bvaughn Do you have an example or suggestion for a trello-like layout?

- Columns (`horizontal-list`); scrolls horizontally;
- Each column (`vertical-list`) has rows; scrolls vertically.

I was able to implement them separately, but when I put the `vertical-list` inside the `horizontal-list` it doesn't work, CellMeasure measure it 0.

### Only columns (`horizontal-list`)
![image](https://cloud.githubusercontent.com/assets/619186/26286918/3c0653ac-3e46-11e7-9a80-4ea62037b5da.png)


### Only one column (`vertical-list`)

![image](https://cloud.githubusercontent.com/assets/619186/26286921/487a41d4-3e46-11e7-9d0e-9d459cc96872.png)

### Trello-like (`vertical-list`s inside the `horizontal-list`)

Renders blank.

PS: Not that important here, but I'm making it using the `ListView` API for `react-native-web`, in the mobile version they are listview inside another listviews which works fine

**Comment by bvaughn** [comment]
I'm not really that familiar with Trello. Looking at the home page...I'd guess you're looking for vertical windowing only, but with multi "column" each of varying height.

If that's right- then I haven't written a UI quite like that with RV but I'd recommend taking [this approach for the columns](http://plnkr.co/edit/zjCwNeRZ7XtmFp1PDBsc?p=preview) and mix it with [this approach for the dynamic row-heights](https://github.com/bvaughn/tweets/blob/master/src/components/TweetList.js).

Feel free to hop in [the RV Slack](https://react-virtualized.now.sh/) and chat with others about ideas. Maybe someone else has built something closer to what you're looking for already. :grin:

**Comment by brunolemos** [comment]
@bvaughn You might have used TweetDeck, it's exactly that: https://tweetdeck.twitter.com/
Ok, I'll jump to the slack.

**Comment by bvaughn** [comment]
Nope, I haven't used that either. But TweetDeck just looks like a couple of `List`s side by side. (No nested `List`s.) In that case you could just do [what I did here](https://github.com/bvaughn/tweets/blob/master/src/components/TweetList.js) and repeat it enough times to fill the page width, no?

**Comment by brunolemos** [comment]
@bvaughn  Kinda, because I need the horizontal list to be virtualized as well.

But I'm almost there 👌
![image](https://cloud.githubusercontent.com/assets/619186/26287621/dd9f23e2-3e55-11e7-8d29-4426f0818a8e.png)

My current problem is that when I call `measure` from `{({ measure }) => (` everything disappears. But not using this callback function is working fine by now. Let's see how it goes.

**Comment by bvaughn** [comment]
Hm...windowing that horizontally sounds like it might lead to sketchy performance, since each `List` is measuring content with `CellMeasurer` but those cached measurements (and the scroll offset) would get thrown away as the `List` is removed b'c of a horizontal scroll- unless you do some kind of higher level management of the individual caches and scroll offsets- and restore them, which you could do, but it sounds complicated.
