### ISSUE TITLE
Table: also pass rowData to rowClassName and rowStyleObject

### ISSUE THREAD

**Issue by Janpot** [bvaughn/react-virtualized#685]
This already happens for `onRowClick`. It would be nice if `rowClassName` could also receive the `rowData` in its parameters when it's used as a function.

At first sight it looks like it's just a matter of moving [this line](rowClass) up and passing it to the functions. For the header row it can be left undefined.

I can do a PR if you want.

**Comment by bvaughn** [comment]
Hey @Janpot

Thanks for the clearly articulated feature request and the offer to submit a PR. (Especially the second one!)

This sort of request comes up fairly often- to support more event types at the row-level or to pass more data to an event handler. At first I added features like this but more recently I've started pushing back because I think it has the possibility to cause bloat. (If 99% of users don't use a feature- and it's possible to implement in user code- then it probably doesn't belong in the lib.)

Anyway, this is one such feature that can be implemented in your application code and so I think it's probably best to stay there.

```jsx
const list; // Assuming your data lives in an Array or similar

function rowClassName({ index }) {
  const rowData = list[index];
  // Return a height
}

function MyTable(tableProps) {
  return <Table {...tableProps} rowClassName={rowClassName} />;
}
```

The same approach could be applied with a class component:

```jsx
const MyTable extends Component {
  render() {
    return <Table {...tableProps} rowClassName={this._rowClassName} />;
  }
  _rowClassName = ({ index }) => {
    const rowData = this.props.list[index];
    // Return a height
  }
}
```

**Comment by Janpot** [comment]
It's mainly a matter of consistency. Some handlers get `rowData`, some get just the `index`.
it's just strange that I have to do:

```jsx
rowGetter={({ index }) => {
  // here I do the main lookup of the row data
  return this.state.items[index] || {}}
}}
rowClassName={({ index }) => {
  // here I have to repeat the array lookup
  const rowData = this.state.items[index];
  return this._isRowSelected(rowData) ? 'selected' : null;
}}
onRowClick={({ index, rowData}) => {
  // here I don't have to repeat the lookup
  this._onRowSelected(rowData);
}}
```
Everybody will have to do the lookup in `rowClassName` *and* in `onRowClick` anyway, and you do the shortcut in one of them already. Then why not do it both of them?
I appreciate the lesson in basic property access in javascript, but I hope you can look past that and see the inconsistency in your API.

**Comment by bvaughn** [comment]
> @bvaughn It's mainly a matter of consistency. Some handlers get rowData, some get just the index.

`rowData` shouldn't really be passed as a param either in my opinion because it's not strictly needed. I added it by request but kind of regret it in hindsight because it can easily be accomplished in user-land.

> Everybody will have to do the lookup in `rowClassName` and in `onRowClick` anyway, and you do the shortcut in one of them already. Then why not do it both of them?

I don't think this is the case at all. Yours is the first request I've gotten in a year and a half (or more?) asking for data to be passed to `rowClassName`. I think most people use a fixed (string) `rowClassName`. Ones that use the function form generally use it for alternating row colors. I think using it for data-specific stuff is not very common.

> In 99% of the cases, people are going to do do this lookup anyway. using index should be the special case instead.

Again, disagreed. I think the common case (based on the experience of using and maintaining this library and answering _many_ questions about it is that `index` is generally used for alternating row colors.

**Comment by Janpot** [comment]
Ok, maybe most people will use `rowClassName` just for alternating row colors. But this would be better done in CSS. You optimised the API for a use case that is invalid or for outdated browsers.
In the case of `onRowClick` people will most likely need the data instead of the index. Why not just make all these kind of callbacks consistent?

**Comment by bvaughn** [comment]
> Ok, maybe most people will use rowClassName just for alternating row colors. But this would be better done in CSS.

No, it wouldn't, because RV isn't guaranteed to start on an "even" or "odd" row given how it works. This would cause the background colors to shift as you scrolled down.

> You optimised the API for a use case that is invalid or for outdated browsers.

I have no idea what this means, unless you're still referring to the CSS.

> In the case of onRowClick people will most likely need the data instead of the index. Why not just make all these kind of callbacks consistent?

For reasons I described above. It's much easier to _add_ something than to _remove_ it in an OSS project. I would prefer to only pass index but doing so at this point may break existing apps.

Ultimately it comes down to the fact that I maintain the lib, and I don't think this is a direction I want to continue making edits in. Hope you'll understand.

**Comment by Janpot** [comment]
> No, it wouldn't, because RV isn't guaranteed to start on an "even" or "odd" row given how it works. This would cause the background colors to shift as you scrolled down.
I stand corrected
