### ISSUE TITLE
[InfiniteLoader] resetLoadMoreRowsCache doesn't work as expected

### ISSUE THREAD

**Issue by BamaBoy** [bvaughn/react-virtualized#700]
After data cleared, and should be refetched, `InfiniteLoader` doesn't call `loadMoreRows` function, and table stays with unloaded data...
Here's [example](https://codesandbox.io/s/PNgGJ8j31) that reproduces the issue. You can click on `clear data` button, then data and cache will be cleared, but new data wouldn't be loaded(via `loadMoreRows`) function. `loadMoreRows` will be called only after scroll.

I've experimented a little bit and found out, that we can add `clearGridMemoized` method to the `Grid` component:
```
clearGridMemoized() {
  this._onGridRenderedMemoizer = createCallbackMemoizer();
}
```
Calling this method, will solve the problem... 
I could've submit a PR, but maybe there is a better solution exist, or maybe I've made a mistake somewhere..

**Comment by bvaughn** [comment]
What `Grid` memoizes is kind of private/internal data that I don't think an external component should know or care about.

`InfiniteLoader.resetLoadMoreRowsCache()` doesn't auto-load because I assumed that whatever invalidated the cache would _also_ invalidate any currently-displayed data, requiring a re-render, which would also require a redraw of the `Grid` and:
1) Either a new set of rows would be rendered (0...n) or
2) The exact same rows would be rendered but the application code would also load them initially since it knew enough to clear the loaded-rows cache anyway (so why wait for a callback)

That being said, I don't really object to `InfiniteLoader` changing behavior to auto-load the current (most recent) range. I'm just not sure that's always what's _expected_.

PS Unfortunately the CodeSandbox you linked doesn't run for me. It just says "_Loading_" forever.

**Comment by BamaBoy** [comment]
@bvaughn Sorry for the CodeSandBox. It works for me... 
Here's the same example in [webpack bin](https://www.webpackbin.com/bins/-KmbRDfMSNy0AvlSlgD1). The problem is, that the new data is supplied. Or should I supply all data, that was loaded before?
For example, I scrolled to 40th row, then data has been updated, and only 20 rows has been supplied. Shouldn't `InfiniteLoader` request the other 20 via `loadMoreRows` function?

**Comment by bvaughn** [comment]
Ah, I see. This makes more sense.

> For example, I scrolled to 40th row, then data has been updated, and only 20 rows has been supplied. Shouldn't InfiniteLoader request the other 20 via loadMoreRows function?

Let's say you scroll to the point where rows 40-60 are visible (including overscan). Upon resetting cached rows, I think it would be reasonable for `InfiniteLoader` to do 1 of 2 things:

1. Expect your application code to pre-fetch the first set of rows and scroll back to row 0. I think this generally makes sense b'c invalidating cached results also typically invalidates scroll position. (eg What relationship does the 40th row of data set A have to the 40th row of data set B? Probably none). Or...
1. Load the most-recently-rendered range of rows only (so in this case 40-60, not 0-60).

I think the first option above is still a reasonable default behavior, but I'd be open to adding a boolean parameter to `resetLoadMoreRowsCache` that triggers the second behavior if, for some reason I haven't thought about, it makes sense to your application. I'm still not sure if it makes sense to maintain scroll position when the data changes like this though.

**Comment by BamaBoy** [comment]
@bvaughn The second option would be perfect in my case! But it seems, that this feature is too optional...
Should I submit a PR, or just implement this feature in my forked repo and close the issue?

**Comment by bvaughn** [comment]
My intuition is that this feature is kind of edge-case-y. I'd be happy to review a PR if you'd like to submit one, provided it was _opt-in_ and didn't add too much complexity. 😄

I'm going to close the issue for now though since I don't expect to take any action on it personally.
