### ISSUE TITLE
Weird interaction when working with 'react-sortable-hoc'

### ISSUE THREAD

**Issue by FateRiddle** [bvaughn/react-virtualized#709]
https://codesandbox.io/s/qYEvQEl0

So I wrote a demo myself that didn't work compare to one sample that works, the only difference being one props for `<List/>`

`rowHeight={({ index }) => 50}`

`rowHeight={50}`

I use the latter way. And it is not working. Why?

**Comment by bvaughn** [comment]
This creates a new function prop each time you render:
```js
rowHeight={({ index }) => 50}
```
That's sufficient to trigger a re-render of the child component, even if no other properties changed. In this case, you could pass a small attribute that changes each time sort order changes (eg an incremented counter) to let the component know to re-render.

Check out [the section on "pure components"](https://github.com/bvaughn/react-virtualized#pure-components) in the docs for more info.

**Comment by FateRiddle** [comment]
@bvaughn  I  have to do a lot more than sorting, all CRUD on <Row /> items, I'm using redux, so the list of task can be read from redux store as array of tasks

`[{id:12312, title:task1, completed:false,  ... }, { ... }, ...]`

So I add state `sortCount` as you suggested, and making it props of `<List />`, and then to make every change works, I add a `setState()` in `componentWillReceiveProps`, 
```
  state = { sortCount: 0 }

  componentWillReceiveProps(nextProps) {
    this.setState({ sortCount: this.state.sortCount + 1 })
  }
```

my question is, is this a burden in performance? How do I improve?

**Comment by bvaughn** [comment]
Any time your data changes, you need to re-render the list, right? There's no way around this.

You don't _need_ to use a counter. Actually if you have something in the data that changes, it's probably even better to just pass it through (eg a prop like `sortOrder` or...anything).

I spent a lot of effort optimizing react-virtualized. Re-rendering isn't _that_ expensive since it's only rendering a slice of the rows.
