### ISSUE TITLE
styling with sytled components

### ISSUE THREAD

**Issue by achtan** [bvaughn/react-virtualized#710]
what is the best way to style Table with [Styled Components](https://www.styled-components.com/)?

**Comment by bvaughn** [comment]
Hello! 😄 

For this type of question, I suggest using Stack Overflow with a [#react-virtualized tag](http://stackoverflow.com/questions/tagged/react-virtualized) or asking in the [react-virtualized Slack channel](https://react-virtualized.now.sh). Issues are reserved for bug reports and feature-requests.

This helps keep the project somewhat more maintainable for me _and_ hopefully gets you an answer faster (since more people check those places than monitor GitHub issues). 😄
