### ISSUE TITLE
Calling List external methods

### ISSUE THREAD

**Issue by brittbinler** [bvaughn/react-virtualized#711]
Even after successfully setting a List ref ([as shown in the tree.js example](https://github.com/bvaughn/react-virtualized/blob/master/playground/tree.js#L55)), I seem to be unable to successfully trigger a remeasuring of row heights using [public methods](https://github.com/bvaughn/react-virtualized/blob/master/docs/List.md#public-methods) ([also shown in the tree.js example](https://github.com/bvaughn/react-virtualized/blob/master/playground/tree.js#L9)). 

https://plnkr.co/edit/V2JhJL8ZGknrbYgRWDhf?p=preview

**Comment by bvaughn** [comment]
Hello! 😄 

For this type of question, I suggest using Stack Overflow with a [#react-virtualized tag](http://stackoverflow.com/questions/tagged/react-virtualized) or asking in the [react-virtualized Slack channel](https://react-virtualized.now.sh). Issues are reserved for bug reports and feature-requests.

This helps keep the project somewhat more maintainable for me _and_ hopefully gets you an answer faster (since more people check those places than monitor GitHub issues). 😄

**Comment by brittbinler** [comment]
Thanks! I'm asking here because I'm wondering whether there is a bug.

**Comment by bvaughn** [comment]
I understand. But since this project has a single maintainer (me) and since I'm pretty strapped for time lately, it's better (for me and you both) if we start with Slack / Stack Overflow. If, after doing so, you're convinced it's a bug then it's totally fine to open an issue here with repro steps, etc.

I don't _think_ this is a bug though probably because there other are examples of doing this sort of thing. For example, [this Twitter client](https://tweets.now.sh/) which has its source [here](https://github.com/bvaughn/tweets/blob/master/src/components/TweetList.js).

**Comment by brittbinler** [comment]
Thanks! The example was helpful.
