### ISSUE TITLE
How can i edit a column value??

### ISSUE THREAD

**Issue by AvijitDutta95** [bvaughn/react-virtualized#712]
I searched for long time but there was no suggestion about editing in a column. Is there any way to customize a column or any option to edit a column??

**Comment by bvaughn** [comment]
Hello! 😄 

For this type of question, I suggest using Stack Overflow with a [#react-virtualized tag](http://stackoverflow.com/questions/tagged/react-virtualized) or asking in the [react-virtualized Slack channel](https://react-virtualized.now.sh). Issues are reserved for bug reports and feature-requests.

This helps keep the project somewhat more maintainable for me _and_ hopefully gets you an answer faster (since more people check those places than monitor GitHub issues). 😄
