### ISSUE TITLE
Double click inside Grid cell highlights text in adjacent cell

### ISSUE THREAD

**Issue by turnerniles** [bvaughn/react-virtualized#713]
Hi, when double clicking on either side of a Grid cell, or on the first or last character of the text any cell, it highlights part of the text in the adjacent cell. Ideally it would only highlight the text in the selected cell. Is this something that could be fixed in the project as a whole, or specifically in the cellRenderer of a specific project?

![image](https://user-images.githubusercontent.com/8146241/27655788-919c299a-5c14-11e7-8ffa-f5ceab9e4334.png)

**Comment by bvaughn** [comment]
That's probably because it's just a series of `<div>` elements so far as the browser knows. So text selection continues until it hits a boundary (like a space or punctuation). This behavior would also vary based on the content of the cell.

I don't think of this as a react-virtualized bug though. Since you're completely in control of what's rendered for a given cell, maybe you could prevent this behavior. Just add a space or punctuation at the end of the cell. 😄

**Comment by turnerniles** [comment]
@bvaughn I agree, but I don't think it's the desired functionality. I guess the solution is to add a space at the end of every cell or use html table, td, tr elements.

[same issue]https://stackoverflow.com/questions/36544298/how-can-i-control-how-much-text-a-double-click-selects
)
[same issue](https://stackoverflow.com/questions/2876424/html-double-click-selection-oddity
)
