### ISSUE TITLE
Attempting to tap on a tappable row, on a mobile device, does not work immediately after scrolling a react-virtualized list

### ISSUE THREAD

**Issue by mr-e-** [bvaughn/react-virtualized#724]
Hi,

I have been having an issue mixing these two and get some strange behavior. For example, I have rows of cardviews (Paper) wrapped in a FlatButton with a ripple effect. When I attempt to tap a row shortly after doing a flick-scroll, the entire react-virtualized area gets surrounded by the thin orange box and the tap is not registered. When I tap again, the thin orange box goes away and the tap is registered. Where is this orange box coming from and why does it intercept my touch event only immediately after scrolling? This only happens when I wrap my list in react-virtualized.

**Comment by mr-e-** [comment]
I debugged the orange box, it looks like the react-virtualize box is stealing the focus instead of the passing the tap down to the inner child... Why would this be happening?

[http://i.imgur.com/KhktVnG.png](url)

**Comment by mr-e-** [comment]
Also I notice, when debugging the virtual list in the chrome debugger, I can see the divs appearing and disappearing and appearing as the list is scrolled, however when this issue occurs there appears to be a delay between when the scrollbar stops scrolling and the div shows up in place.

**Comment by bvaughn** [comment]
There are [a few issues related to this](https://github.com/bvaughn/react-virtualized/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20pointer-events) if you're curious to read more. Essentially react-virtualized (and every other windowing library) disables `pointer-events` while a user is scrolling. You can _prevent_ this behavior by passing in your own `containerStyle` that sets `pointer-events: "auto"` (and overrides RV's default).

I don't think this issue is particularly actionable so I'm going to close it. I suggest you hop into the [react-virtualized Slack channel](https://react-virtualized.now.sh) if you want to chat more about it though. 😄
