### ISSUE TITLE
measuring images onLoad results in poor scrolling behavior?

### ISSUE THREAD

**Issue by scf4** [bvaughn/react-virtualized#726]
I have large lists of posts with dynamic heights and images using a virtual list/infinite loader/window scroller/cell measurer combo.

I'm having trouble with the scrollbar jumping around when scrolling (the list itself changes height, even though all rows have been measured), but it seems removing `onLoad={measure}` from the images in posts fixes it.

Any ideas why this could be happening?

**Comment by bvaughn** [comment]
Hello! 😄 

For this type of question, I suggest using Stack Overflow with a [#react-virtualized tag](http://stackoverflow.com/questions/tagged/react-virtualized) or asking in the [react-virtualized Slack channel](https://react-virtualized.now.sh). I also suggest providing a Plnkr that demonstrates the issue you're reporting; this makes it easier for people who want to help and rules out simple mistakes (like typos).

Focusing GitHub issues on only bug reports and feature-requests helps keep the project somewhat more maintainable for me _and_ hopefully gets you an answer faster (since more people check those places than monitor GitHub issues). 😄

**Comment by acomito** [comment]
@scf4 did you ever find anything for this? I'm about to embark on building the same thing.

**Comment by scf4** [comment]
My solution was to get rid of calling measure onLoad and simply ensuring it has the image sizes ahead of time.

**Comment by JayenLee** [comment]
I have the same problem, I use this as the chat room message list, and when I slide down with this, the line with the text message will flash, but when I remove the onLoad ={measure} above the picture element, it won't, but there's a new problem, and that's some. The height of the message can not be calculated successfully, and there will be two message overlaps.
