### ISSUE TITLE
Any good sample of using react-virtualized Infinite Scroll with Redux ?

### ISSUE THREAD

**Issue by alduro** [bvaughn/react-virtualized#729]
Just that. I found it quite hard to implement it with basic documentation. Thanks.

_loadMoreRows in just create basic data to show in there. Not quite real sample.
https://github.com/bvaughn/react-virtualized/blob/master/source/InfiniteLoader/InfiniteLoader.example.js

**Comment by bvaughn** [comment]
Hello! 😄 

I suggest using Stack Overflow with a [#react-virtualized tag](http://stackoverflow.com/questions/tagged/react-virtualized) or asking in the [react-virtualized Slack channel](https://react-virtualized.now.sh) to discuss general things like this. Issues are reserved for bug reports and feature-requests.

This helps keep the project somewhat more maintainable for me _and_ hopefully gets you an answer faster (since more people check those places than monitor GitHub issues). 😄
