### ISSUE TITLE
Provide API for row right click

### ISSUE THREAD

**Issue by damian-codilime** [bvaughn/react-virtualized#738]
I need to make a context menu on row right click.
Instead of writing a row wrapper - which i did currently, i would like to pass `onRowRightClick` or `onRowContextMenu` (to be consistent with element event) to the table and get the event callback.

Implementing this is quite straightforward as i saw in code and should not take much time - i could provide a PR.

**Comment by bvaughn** [comment]
I don't like continuing to add `onRow*` properties to `Table`. I wish I had designed that part of the API differently.

If you're willing to create a PR with all of the necessary code changes (to `Table` and `defaultRowRenderer`) and docs changes (`Table.md`), and it passes lint check, etc. I guess I'll merge it and it can go into the next release. 😄 

I'm going to close this issue since I don't plan on taking action on it. But send a PR my way if you'd like!

**Comment by ryb73** [comment]
For anyone finding this from Google, this was implemented in #741, though it doesn't seem to have made it to the TypeScript defs
