### ISSUE TITLE
virtualized table multiple sort

### ISSUE THREAD

**Issue by LAP2** [bvaughn/react-virtualized#739]
Hi.
Is it possible to add multiple sort some day?
For example like this table https://react-table.js.org/#/story/custom-filtering
As I think if change **sortBy** and **sortDirection** Table props from **string** and **SortDirection** to functions with following signature:
```
function sortDirection(dataKey):SortDirection {
	//do something with this stuff
}

function sortBy(dataKey):boolean {
	//do something with this stuff
}
```
By default it could be implemented as always true for **sortBy** and direction swap for **sortDirection**. 
But if somebody wants to implement multiple sort (for example me) he could implement own **sortBy** and **sortDirection** functions

**Comment by bvaughn** [comment]
This isn't supported because I don't really understand the concept of multi-sort in a table. (When would you use this? How does it work?)

If you'd like to contribute a PR (with tests, docs, and example code) that adds this feature I'd be happy to review it 😄  but this isn't something I plan to add.

I'm going to close this issue since it's not one I plan to take action on. Happy to continue to discuss it though!

**Comment by LAP2** [comment]
Ok that's a deal.
i'm ask this question just because of this 

> **Please ask first** before embarking on any significant pull request.

rule. Probably I will send a PR lil later.
Thnx for not rejecting this proposal at once.

**Comment by bvaughn** [comment]
No worries! I'm glad you asked. 😄
