### ISSUE TITLE
out of the box search?

### ISSUE THREAD

**Issue by vgoklani** [bvaughn/react-virtualized#74]
Hey - just curious, is there a search function built in? If I have 5,000 rows, and I want to find all rows that contain the keyword "quack", is there a fast filter?

Thanks!

**Comment by bvaughn** [comment]
Hey @vgoklani,

No search functionality is built into react-virtualized but I have a few other libraries that do what you're looking for and can be used alongside react-virtualized.
* If you're using Redux, I suggest you check out [redux-search](https://github.com/treasure-data/redux-search)
* If you're not using Redux and just want a plain JavaScript util then check out either [js-worker-search](github.com/bvaughn/js-worker-search) (it's what redux-search uses under the hood) or [js-search](github.com/bvaughn/js-search) if you'd like something a little more configurable and full-featured.

**Comment by bvaughn** [comment]
I'm going to close this issue so it doesn't clutter up the issues list but I'll keep monitoring it in case you have questions. :)

**Comment by vgoklani** [comment]
great - thank you so much! This looks particularly nice: https://github.com/bvaughn/js-worker-search

**Comment by bvaughn** [comment]
Thank you :D Happy to hear. Hope it works for you!

**Comment by Sm00g15** [comment]
has this changed at all? Is there any search utility in React-Virtualized?

**Comment by bvaughn** [comment]
No. This isn't a search library.

Look at my response above though. I linked several such libraries.

**Comment by rally25rs** [comment]
Don't want to reopen this issue, but just wanted to point out that if RV supported "search" through some hooks like it does for sorting, it would make this a lot easier. Just adding an external search library is a lot harder than it sounds...

When you think through what the majority of users would expect from a search box, they expect it to work like pressing `ctrl-f` in a browser; it searches the _rendered_ text. In a table component, this means that the filtering should be done on the text returned from the `cellRenderer` functions for each column. For example my raw dataset might contain unix timestamps as a number (seconds since epoc) but the cellRenderer formats it to "December 12th" (actually a properly i18n localized date). As an end user I should be able to search for "december".

So as a programmer to implement this correctly, you actually need to loop over all your data records and all your columns, get the cell renderer for each column, render the element, and extract the text.

This in itself isn't that bad I suppose, but a large part of RV is that it can handle very large data sets by _not_ rendering them all. Now we are back to having to render them all... If RV had a hook for this, then RV could take care of only looping through records until it finds enough to fill the visible rendered rows. So if it's currently rendering 50 rows, it would only need to find the first 50 filtering results.

This would help a lot in keeping performance acceptable and making the end user experience as expected.
