### ISSUE TITLE
ScrollSync grid header is not scrollable

### ISSUE THREAD

**Issue by cephirothdy2j** [bvaughn/react-virtualized#750]
In the [ScrollSync demo](https://bvaughn.github.io/react-virtualized/#/components/ScrollSync), I noticed the header itself (cells C1 through C49) are not scrollable. Rather, they only scroll when the grid beneath them is scrolled by the user.

Is there a reason for this? As a user, I would expect scrolling behavior on the header to be preserved, and for it programmatically scroll the grid beneath it (just like it works vice-versa).

Thanks for a great plugin! I'm combining it with [react-sortable-hoc](https://github.com/clauderic/react-sortable-hoc) and an as-yet undetermined library to allow for sortable / resizable columns. I'll post an example for other users once it's complete.

**Comment by bvaughn** [comment]
This is just the way the demo is implemented. `MultiGrid` (which works similarly to `ScrollSync`) supports scrolling in the fixed rows/cols as can be seen [in the demo](https://bvaughn.github.io/react-virtualized/#/components/MultiGrid). Maybe you could use that component instead? 😄  If not, perhaps its implementation would serve as a useful reference.

I look forward to seeing your component!

Closing this issue for now since I don't think it requires any action on my part.

**Comment by cephirothdy2j** [comment]
Thanks for that, but unfortunately I don't think it will work in my case ...

1) In my ScrollSync implementation, I'm wrapping my "header grid" and its cells in `react-sortable-hoc` and it does not look like that is possible using `MultiGrid`.
2) I'm also using `ArrowKeyStepper` and do not want to allow users to step into the header row.

In your response you said:

> This is just the way the demo is implemented.

Am I to infer that there is, in fact, a way to make that header row scrollable using ScrollSync, or is just a limitation of the component?

**Comment by bvaughn** [comment]
The source code for the `ScrollSync` example is [here](https://github.com/bvaughn/react-virtualized/blob/master/source/ScrollSync/ScrollSync.example.js). I'm only listening to `onScroll` for the primary `Grid` (see [here](https://github.com/bvaughn/react-virtualized/blob/master/source/ScrollSync/ScrollSync.example.js#L187)). Try listening to all 3 and see what happens. (I haven't.)
