### ISSUE TITLE
add react-virtualized to jsspreadsheets.com

### ISSUE THREAD

**Issue by sandys** [bvaughn/react-virtualized#759]
https://jspreadsheets.com/ is one of the best sites to discover spreadsheet components for javascript. It is frequently cited in discussions on stackoverflow and hacker news.

React-virtualized is conspicuous by its absence. The way to add it is here - https://jspreadsheets.com/submit-new.html

I do request the maintainers to add themselves to jsspreadsheets.com

**Comment by bvaughn** [comment]
Hi @sandys 😄 

Looks like anybody can submit a new grid library via a PR to [krzysztofspilka/JSpreadsheets](https://github.com/krzysztofspilka/JSpreadsheets). Would you be willing to add react-virtualized to the list?

I'm going to close this issue since it's not really a react-virtualized issue. It would be cool if someone added the lib to jspreadsheets.com though. 😁
