### ISSUE TITLE
Bug: CellMeasurer doens't remove styles properly

### ISSUE THREAD

**Issue by dferber90** [bvaughn/react-virtualized#764]
I'm fairly new to `react-virtualized`, so take this with a grain of salt.
We're only using `CellMeasurer` without `Grid`etc.

The potential problem I've found is in [`_getCellMeasurements `](https://github.com/bvaughn/react-virtualized/blob/master/source/CellMeasurer/CellMeasurer.js#L82-L87) of `CellMeasurer`: When measuring an element that does not have a `style`, but has a class which specifies a `width` and `height`, the values will be overridden.

After measuring the measured node is expected to have its original styles again, but has additional `width: auto` and `height: auto` styles which overwrite those values provided through CSS classes.

This is a shortened, annotated version of `_getCellMeasurements` to highlight the issue:

```js
_getCellMeasurements () {
  // given a node that has class foo
  // <div className="foo" />
  // and a class foo which sets width and height
  // .foo { width: 100%; height: 100% }

  // these will be empty strings as the styles are not defined
  // with the style-tag, but through a class
  const styleWidth = node.style.width;
  const styleHeight = node.style.height;

  // at least one of these will be executed, setting a style on the node
  if (!cache.hasFixedWidth()) {
    node.style.width = "auto";
  }
  if (!cache.hasFixedHeight()) {
    node.style.height = "auto";
  }

  // State of node:
  // <div  style={{ width: "auto", height: "auto" }} className="foo" />

  // Now the next part is meant to remove the style overwrites,
  // but fails to do so because the original styles were applied
  // through the class, not the style tag
  if (styleWidth) {
    node.style.width = styleWidth;
  }
  if (styleHeight) {
    node.style.height = styleHeight;
  }

  // State of node:
  // <div  style={{ width: "auto", height: "auto" }} className="foo" />
}
```

To fix the issue, removing the `if` checks at the end should be enough.

```diff
-if (styleWidth) {
-  node.style.width = styleWidth;
-}
+node.style.width = styleWidth;
-if (styleHeight) {
-  node.style.height = styleHeight;
-}
+node.style.height = styleHeight;
```

In case this is expected behaviour we have already found a fix by setting `height` and `width` of the child explicitly (to `100%`). This will make `CellMeasurer` remove the styles properly after measuring. Can you shed some light on whether this is a bug or we are doing something fishy?

**Comment by bvaughn** [comment]
The explicit setting of `width: "auto", height: "auto"` is intentional to force `CellMeasurer` content to grow in the way that I _think_ people most often want it to and not to be constrained by the default width/height configured in the `CellMeasurerCache`.

However I see what you mean wrt class styles not being re-applied. I'm not sure of the best way to address this. I could use `window.getComputedStyle` but coerces any percentage values to pixels. I don't actually know of a way to restore a percentage-based style (like you mention) to its value.

However I'm also not sure why this should be necessary as each cell within a react-virtualized `Grid` is _explicitly sized_ by the `Grid`. In the case of `CellMeasurer`, the cell should be explicitly sized to the initially measured value. (In other words, what value is there to go back to `width:100%`?)

**Comment by dferber90** [comment]
Thanksgiving for the feedback. Yes we'd want to go back to 'width: 100%'.

We are using the CellMeasurer only and were caught by surprise that a "measurer" also modified the children.

We are using CellMeasurer without Grid. We have a weird mix of CellMeasurer and FixedDataTable. We decided not to upgrade react-virtualized for now. We want to reimplement our tables purely in react-virtualized at some point. Consider our use-case an edge-case.

Closing this as a fix doesn't seem necessary and the behavior is indeed intentional.
