### ISSUE TITLE
Setting <Column style={{overflow:visible}} does not work 

### ISSUE THREAD

**Issue by reggarcia** [bvaughn/react-virtualized#783]
I am trying to display a tooltip on rowMouseOver but it gets cut off. I tried setting the row and column with style {{overflow:'visible'}} and it doesn't budge. Help!

**Comment by reggarcia** [comment]
![image](https://user-images.githubusercontent.com/3925319/29472146-941e667c-8407-11e7-9f1e-de04dd8c0146.png)

**Comment by bvaughn** [comment]
Hello! 😄 

For this type of question, I suggest using Stack Overflow with a [#react-virtualized tag](http://stackoverflow.com/questions/tagged/react-virtualized) or asking in the [react-virtualized Slack channel](https://react-virtualized.now.sh). Issues are reserved for bug reports and feature-requests.

This helps keep the project somewhat more maintainable for me _and_ hopefully gets you an answer faster (since more people check those places than monitor GitHub issues). 😄
