### ISSUE TITLE
Grid custom style is removed when updating from an empty grid to a filled one

### ISSUE THREAD

**Issue by Uhsac** [bvaughn/react-virtualized#787]
Hello,

First thanks for your work on this library, it greatly designed and it's a pleasure to work with it.

I encountered a weird bug when re rendering a `Grid` from 0 rows to `n` rows (`n` > 0), custom style applied to the `Grid` (using `style` prop) are not applied anymore.

You can see the bug on this [plnkr](https://plnkr.co/edit/4jkZXuiwboyY1Ugy9s7Q), just click twice on the button and you will see that the scroll bar appear again, and if you check the style using the debugger you will see that the custom style is not applied.

I checked the code of `Grid` but I was not able to find a reason for this.

For information, I'm on a Linux system (so with ugly scroll bar) using Chrome 60.

Thanks

**Comment by bvaughn** [comment]
This is a misunderstanding b'c of the particular style you're using, `overflow`. [`Grid` specifically manages `overflowX` and `overflowY` properties](https://github.com/bvaughn/react-virtualized/blob/master/source/Grid/Grid.js#L904-L912) to avoid scrollbar problems. These properties are more specific than `overflow` and so will override your custom style because of how React handles shorthand CSS properties (see facebook/react/issues/8689).

You can confirm that `Grid` works correctly WRT custom styles by using another style (eg `border: '1px solid red'`).

**Comment by Uhsac** [comment]
Ok I understand.
FYI we do this because we want a multi grid table where the first grid (first fixed column) don't have scroll bar.
To do this we hide the scroll bar and handle scroll using `onWheel` event. We didn't find a better way to do this.

**Comment by bvaughn** [comment]
Thanks for elaborating.

You can still accomplish what you're aiming to do. You'll just need to pass an explicit `overflowX` and/or `overflowY` value (rather than `overflow`).
