### ISSUE TITLE
Cell Measurer - incorrect width for wide final column

### ISSUE THREAD

**Issue by md384** [bvaughn/react-virtualized#790]
This demo https://plnkr.co/edit/BniVkcZ1PEDgneJKO4P3?p=preview shows a problem I have been having with text overflow when using the `CellMeasurer`.

It seems to happen when the content of the final column would produce a very wide column (much wider than `defaultWidth`). Switching the penultimate and final columns in the demo appears to fix the problem.

**Comment by bvaughn** [comment]
Given your `CellMeasurerCache` configuration, I assume you want a layout like [this page](https://bvaughn.github.io/react-virtualized/#/components/CellMeasurer) where text grows in width without wrapping? If so then you'll want to [add a `whiteSpace: "nowrap"` style](https://github.com/bvaughn/react-virtualized/blob/master/source/CellMeasurer/CellMeasurer.DynamiWidthMultiGrid.example.js#L74) to your cell.

Here's a fixed Plnkr: https://plnkr.co/edit/qY0NXhiPGG3mI3cQJPUZ?p=preview

**Comment by markwoon** [comment]
@bvaughn `nowrap` doesn't really solve the original problem, which is that `CellMeasurer` is not calculating the width correctly when you have long text in the final column.

You can see that everything works as expected if you just swap the last two columns.

Here's the original as reported by @md384 with some URLs fixed so it works again: https://plnkr.co/edit/2nMKgxIy11H21rU0i1jH?p=preview

Here's what happens when you swap the last 2 columns:
https://plnkr.co/edit/gAq7DhVN2F0g7auKKuOW?p=preview

You can see that it's rendering correctly when it's _not_ the last column.  Will you consider re-opening this issue?  Or do you not think this is a problem?
