### ISSUE TITLE
Table with custom rowRenderer with CellMeasurer renders rows on top of each other

### ISSUE THREAD

**Issue by strokovnjaka** [bvaughn/react-virtualized#808]
When Table uses custom rowRenderer with CellMeasurer, it renders rows in same place, one on top of the others. If `deferredMeasurementCache={cache}` prop is removed from Table, rows are rendered one after another, but of course the height is wrong.

This plunk demonstrates the issue:
https://plnkr.co/edit/2MTxLEQi1suPCygJDGKt?p=preview

**Comment by bvaughn** [comment]
This is not how `CellMeasurer` and `Table` are meant to be used. `CellMeasurer` should wrap column content rather than the entire row. 😄

Check out an example of combining these 2 components [here](https://github.com/bvaughn/react-virtualized/blob/master/source/CellMeasurer/CellMeasurer.DynamicHeightTableColumn.example.js#L70-L94).

**Comment by strokovnjaka** [comment]
@bvaughn I was trying to get the row to expand; therefore I could not use `CellMeasurer` in column but row. I switched to `List` now.
Thank you for clearing this up, and the fabulous package you are producing!
