### ISSUE TITLE
Scrollbar in Multigrid will not be the proper length when rows have multiple lines

### ISSUE THREAD

**Issue by Typhon66** [bvaughn/react-virtualized#832]
When a cell wraps and multi-lines in a row of a multigrid that scrolls vertically, the scrollbar will not be the correct length of the actual table content, which causes a rubberband effect.

**Comment by bvaughn** [comment]
This sounds like a misconfigured `MultiGrid`. (Like you specified a `rowHeight` that is too short for your actual row's contents. If you don't know the height ahead of time, you can [use the `CellMeasurer` component](https://github.com/bvaughn/react-virtualized/blob/master/docs/CellMeasurer.md). Otherwise you can prevent text-wrapping in a cell via CSS:
```css
    white-space: pre;
    overflow-x: hidden;
    text-overflow: ellipsis;
```
