### ISSUE TITLE
Change exported library name to proper JS variable

### ISSUE THREAD

**Issue by jlongster** [bvaughn/react-virtualized#86]
Line https://github.com/bvaughn/react-virtualized/blob/master/webpack.config.dist.js#L14 in webpack makes it so that if you include this as a `<script>` tag on a page, it sets it to `window["react-virtualized"]` which is strange. I would expect it to be `window.ReactVirtualized`, so that it exposes a `ReactVirtualized` global without forcing a referencing through the window object.

**Comment by bvaughn** [comment]
Hey @jlongster. Seems like a good suggestion. Since this is a backwards incompatible change- I'm going to include this in the upcoming v5 release. (I kind of doubt anyone's using the library as `window["react-virtualized"]` but... just in case.)

PS. Perfect timing on your Twitter post about hidden messages with `script` tags. I was just briefly thrown by the seemingly cutoff email summary I got for this issue.
