### ISSUE TITLE
On resize, Column Width Function only called with index: 0

### ISSUE THREAD

**Issue by MrNice** [bvaughn/react-virtualized#864]
See: [Sandbox](https://codesandbox.io/s/pq86n5w5j)

So I had this working yesterday but somehow broke it during a refactor. I'm building a replacement for Table & Column using MultiGrid. Because I have zebra striped rows, one requirement I have is to be able to add an invisible column to fill the remaining space. Upon resizing the window, the `calculateColumnWidth` function passed to MultiGrid is only called for index zero. You can confirm this by looking at the logs, which look something like this:

![screen shot 2017-11-01 at 12 29 37 pm](https://user-images.githubusercontent.com/2587335/32293619-f5ae7dd0-bf00-11e7-91ed-c2d70da44be3.png)

Here is the behavior I had working yesterday:
![out](https://user-images.githubusercontent.com/2587335/32293832-9f676de6-bf01-11e7-8eb5-0533dc255faa.gif)

I don't really want to force update the grids every render, I feel as though changing the width prop should handle that for me.

**Comment by MrNice** [comment]
Calling recomputeGridSize on the MultiGrid during render fixes this issue, but also throws a warning because it's being called during render.

**Comment by bvaughn** [comment]
I think this is a misunderstanding. The reason the width getter is being called only for column 0 is because of [this method in `MultiGrid`](https://github.com/bvaughn/react-virtualized/blob/946ef69ccbec9556aafde8a5d69e49a610aa15f4/source/MultiGrid/MultiGrid.js#L459-L463) which checks to see if its fixed column width has changed. Since you're creating and passing a new function instance as `columnWidth ` getter each time you render, it tricks the component into [thinking that the size of its fixed column may have changed](https://github.com/bvaughn/react-virtualized/blob/946ef69ccbec9556aafde8a5d69e49a610aa15f4/source/MultiGrid/MultiGrid.js#L485). Maybe this is an optimization I should make to `MultiGrid` since people use arrow functions so often.

`Grid` on the other hand, ignores changes to getter functions like this because it's already been optimized in that way. `Grid` provides an explicit method, [`recomputeGridSize `](https://github.com/bvaughn/react-virtualized/blob/master/docs/Grid.md#recomputegridsize--columnindex-number-rowindex-number-), that you need to call if the size of individual cells have changed.

Hope this helps explain. In either case, the behavior you're describing doesn't sound broken or bad to me. 😄

**Comment by MrNice** [comment]
I've moved on from that position and no longer have access to the code, but
my solution waited 500 ms after the final browser resize event to call one
of the force calculate methods on Multigrid

**Comment by mballoni** [comment]
In the end I've managed to make it working using "recomputeGridSize" at the AutoSizer event.
 Thanks!
