### ISSUE TITLE
design for Masonry

### ISSUE THREAD

**Issue by MarsArbiter** [bvaughn/react-virtualized#870]
I think this library is wonderful.  So I check the code in Masonry. But I can't understand why Masonry need a cellMeasurerCache prop. I see that the Masonry only get width/height from the prop, but left/top from the cellPositioner who wraps another cach object. 

I'm confused that why not get width/height from the cellPositioner's cach too,  And what can we get with that we have two different cellMeasurerCache object

**Comment by bvaughn** [comment]
`Masonry`, like other RV components, cache size and position separately because size is slow to calculate and position is fast. Position can be invalidated by things like a window resize, in which case it's pretty fast to just throw away the position cache and recompute. Fewer things invalidate cached sizes and so we store them separately.

The `CellMeasurerCache` in particular is used b'c that's the way the API for `CellMeasurer` was designed and `Masonry` makes use of it. It would be possible to combine both position and size measurements into a single cache. I just didn't design it that way. 😄

**Comment by silvenon** [comment]
A related question: let's say that I want to make column widths responsive using `AutoSizer`:

1. Is that a terrible idea? 😅 
2. How do I invalidate `defaultWidth` in the `CellMeasurerCache`? Do I just call `clearAll` or should I create a new cache? If I create a new one, should I create a new `CellMeasurer` too, using the new cache?

**Comment by bvaughn** [comment]
> Is that a terrible idea? 😅

Not at all. That's how `ColumnSizer` works in most cases.

This also sounds similar to what I'm doing on the [`Masonry` demo page](https://github.com/bvaughn/react-virtualized/blob/master/source/Masonry/Masonry.example.js.

> How do I invalidate `defaultWidth` in the `CellMeasurerCache`?

You can't, currently. If changing the _actual width_ would likely impact the height as well, you should probably just create a new `CellMeasurerCache` and pass it as a prop to `CellMeasurer`. Should work?

**Comment by silvenon** [comment]
I somehow missed that part in the example, thanks a lot! I'll try it and contribute an example of an image gallery later on when I get the hang of it.
