### ISSUE TITLE
Masonry layout quirks after re-visiting  page with react router (plnkr provided)

### ISSUE THREAD

**Issue by mrbarletta** [bvaughn/react-virtualized#872]
First - awesome library :1st_place_medal:  thanks for the effort you devote to it :)
 
I am trying to do a 2 column fixed height/width product layout using Masonry (hope is this a good use case )

It works fine one first visit - showing the 2 columns correctly
![masonry1](https://user-images.githubusercontent.com/2429244/32744353-d7a845a0-c874-11e7-80fa-ce26858bbf51.jpeg)

But once I navigate away and go back, the layout shows a single column. 
I traced back the problem to the Style being sent to the cellRenderer - 
Autosizer is sending always correct sizes to the Masonry, but something is happening in the middle 

Here is a plunker with 2 links, Home/Products to show the error.  
https://plnkr.co/edit/ZZWz27bk6VQpwj5m299V?p=preview

Any guidelines appreaciated.

**Comment by bvaughn** [comment]
Thanks for the compliment. 😄 

If your layout is just 2 columns with fixed heights like this, I would suggest using `List` rather than `Masonry`. [Here's an example showing how you can create a grid/cell layout using the `List` component.](http://plnkr.co/zjCwNeRZ7XtmFp1PDBsc) You could also use `CellMeasurer` to measure your 2-column rows if you wanted to support dynamic height per row. `Masonry` can support more complicated layouts, but is a bit trickier to use as a result.

That being said, it looks like your Plnkr is showing some unexpected behavior. Comparing the DOM from the initial render to the 2nd render, it looks like the only styles being passed to cells the 2nd time is `width`, and the height of the scroll container is the height of a single cell. 🤔 

### Before
```html
<div
  class="ReactVirtualized__Masonry__innerScrollContainer"
  style="width: 100%; height: 310px; max-width: 100%; max-height: 310px; overflow: hidden; position: relative;"
>
  <div style="width: 140px; height: 150px; left: 279.5px; position: absolute; top: 0px;">
```
### After
```html
<div
  class="ReactVirtualized__Masonry__innerScrollContainer"
  style="width: 100%; height: 150px; max-width: 100%; max-height: 150px; overflow: hidden; position: relative;"
>
  <div style="width: 140px;">
```

I'll look into this a bit this morning but honestly, I don't know if I'll be able to find time to get to the bottom of it. I'm swamped lately. 😦

**Comment by bvaughn** [comment]
Looks like the 2nd time the route is loaded, the position cache is empty (since it's re-created when the `Masonry` component is instantiated) but the incoming `CellMeasurerCache` is full (because it's persisted between routes, since you've declared it outside of the scope of the components being recreated when routes change).

[This is an unexpected case.](https://github.com/bvaughn/react-virtualized/blob/34a5f25818a0dadfad7f0a57654fd3cc0330b260/source/Masonry/Masonry.js#L175-L179) `Masonry` batches up a few cells for 1st time measurement, but the `CellMeasurer` sees they've already been measured and doesn't do anything- leaving the cells kind of hung.

I'm not sure of a great way to approach this. `Masonry` could require a `PositionCache` to be passed in as a prop too, but that complicates the more common use-case. You could throw away and recreate your `CellMeasurerCache` but that's wasteful since it would require re-measuring and we don't want to do that b'c of the negative performance impact.

I think the best way to handle this would be for your application to let `Masonry` know that it needs to do work in the case of a re-loaded route by calling either either [`clearCellPositions`](https://github.com/bvaughn/react-virtualized/blob/master/docs/Masonry.md#clearcellpositions-) or [`recomputeCellPositions`](https://github.com/bvaughn/react-virtualized/blob/master/docs/Masonry.md#recomputecellpositions-).
