### ISSUE TITLE
Wrapping text with CellMeasurer

### ISSUE THREAD

**Issue by WscriChy** [bvaughn/react-virtualized#896]
I have the following use of `CellMeasurer`:

```
.item {
  border-bottom: 1px solid #eee;
  padding: 0.5rem;
  box-sizing: border-box;
}

.item-text {
  display: inline-block;
  vertical-align: top;
  white-space: pre-wrap;      /* CSS3 */
  white-space: -moz-pre-wrap; /* Firefox */
  white-space: -pre-wrap;     /* Opera <7 */
  white-space: -o-pre-wrap;   /* Opera 7 */
  word-wrap: break-word;      /* IE */
}

var cache = new CellMeasurerCache({
  defaultHeight: 20,
  defaultWidth: 50,
  fixedWidth: false
});

<CellMeasurer {...}>
  <div className="item" key={key} style={style}>
    <small>{datum.timestamp}</small>
    <br />
    <strong>{datum.author}</strong>: <div className="item-text">{datum.text}</div>
  </div>
</CellMeasurer>
```

The problem with it is when `datum.text` is a long sense/word. Then the rest of the text goes outside of the display area. I would like the text to be wrapped in available width of the list and the height to be adjusted to the wrapped text. Thanks in advance.

**Comment by richcobrien** [comment]
I believe we are also pursuing a similar functionality. We would like the row height to dynamically expand when word wrap occurs in the same row's text entry box.

With absolute positioning of rows we are looking at event triggering to do rowRecalc.

**Comment by bvaughn** [comment]
Hello! 😄 

For this type of question, I suggest using Stack Overflow with a [#react-virtualized tag](http://stackoverflow.com/questions/tagged/react-virtualized) or asking in the [react-virtualized Slack channel](https://react-virtualized.now.sh). Issues are reserved for bug reports and feature-requests.

This helps keep the project somewhat more maintainable for me _and_ hopefully gets you an answer faster (since more people check those places than monitor GitHub issues). 😄

**Comment by skipjack** [comment]
I'm running into a similar issue. Text wrapping seems to work fine with the `CellMeasurer` when used inside a `List`, however I'm seeing it fail when used within a `MultiGrid`. I may try to throw a reproducible example together.

@bvaughn I understand what you mean but it seems like this is more of a bug than a question:

> The problem with it is when datum.text is a long sense/word. Then the rest of the text goes outside of the display area. I would like the text to be wrapped in available width of the list and the height to be adjusted to the wrapped text.

I'd be happy to help once we've discussed a viable solution.

**Comment by skipjack** [comment]
Debugged this a little more and found that the issue (at least in my case) is that despite the fact that `fixedWidth` is `true` in my `CellMeasurerCache`, when `CellMeasurer._getCellMeasurements` runs, `node.style.width` is `auto` which means it's measuring the height before the before the `width` is applied. This makes total sense, because it correctly measured the height for multiple block elements in the same cell (stacked on top of one another despite the width) but failed for text wrapping because the initial render would just stretch as far as the text and never break it to multiple lines.

Funny thing is, there was already a `TODO` for this:

https://github.com/bvaughn/react-virtualized/blob/master/source/CellMeasurer/CellMeasurer.js#L54

I'm looking into a stable fix for the issue and the `TODO`. Unfortunately, it doesn't seem to be super straightforward so far so any suggestions from people more familiar with the code would be much appreciated!

**Comment by skipjack** [comment]
Also, I did find [this example](https://bvaughn.github.io/react-virtualized/#/components/CellMeasurer) (select `dynamic height text`) which demos exactly what we're looking for with a normal `Grid`. I guess there's something slightly different about how the `MultiGrid` works that causes the initial cell measurements to be off.

**Comment by skipjack** [comment]
Might just be talking to myself here at this point, but here's what I found...

I wasn't able to make any change to the `CellMeasurer` to fix it trying to measure `height` while `width` was still equal to `auto`. Every attempt I made at delaying the measurement triggered an infinite loop. However, I was able to fix the issue by firing the [`measure`][1] callback in the component's lifecycle returned by `cellRenderer`, i.e.

``` jsx
class Table extends React.Component {
    render() {
        return (
            <MultiGrid
                 ...
                 cellRender={ this._renderCell } />
         )
    }

    _renderCell = options => {
        return (
            <CellRenderer ...>
                 {({ measure }) => (
                      <Column
                          ...
                          measure={ measure } />
                 )}
             </CellRenderer>
        )    
    }
}

class Column extends React.Component {
    // ...
    componentDidUpdate(prevProps) {
        if ( prevProps.style.width !== this.props.style.width ) {
            this.props.measure()
        }
    }
}
```

Then, in order to properly handle updates (without an unmount and remount), I had to utilize the [`keyMapper`][2] method so the cached sizes would correspond directly to the data without the need for re-measuring. I also had to fire `MultiGrid.recomputeGridSize` in my `Table` component's `componentDidUpdate` in order for the keys to be updated and the right values pulled from the cache for the `cellRenderer`.

@bvaughn I like this library a lot but getting this particular feature (text-wrapping in the `MultiGrid`) to work out of the box definitely isn't super intuitive. I'm a little strapped for time at the moment, but if you're open to talking through a fix for the `CellMeasurer`, I'd love to figure out a better fix for this in the actual library (which would also close that `TODO` I found in the code). If the examples I've shared aren't enough, I'll try to throw together webpackbin that demos the problem.

As for the need for a `keyMapper` and calling `recomputeGridSize`, I think those are understandable at the consumer level as we can't know the best mapping without knowledge of the data. The only other thought I'd have is that maybe `Table` and `Column` could be re-written as wrappers around the `MultiGrid`. It could be written to still support all existing features with added support for `fixed` columns/rows and more control over cell width (with horizontal scrolling). This change would take a toll on performance though.

[1]: https://github.com/bvaughn/react-virtualized/blob/master/docs/CellMeasurer.md#using-cellmeasurer-with-images
[2]: https://github.com/bvaughn/react-virtualized/blob/master/docs/CellMeasurer.md#prop-types-1

**Comment by bdrobinson** [comment]
I don't think this relates quite to the issue you're facing @skipjack but I was facing a similar problem to OP and found that the issue my text wasn't wrapping in my `Table` cells was that the `Column` component automatically applies `white-space: nowrap;`, which was cascading down to my cell element. So in my `renderCell` method I just set that back to `white-space: normal;` and everything magically started working. See [here](https://stackoverflow.com/a/44710214/968098).
