### ISSUE TITLE
WindowScroller serverWidth, serverHeight issue

### ISSUE THREAD

**Issue by landvibe** [bvaughn/react-virtualized#910]
If I set serverWidth and serverHeight, server and client have defferent initial width and height.
As a result, react prints a mismatch warning.
I think defaultWidth, defaultHeight approach is better (in my [initial commit](https://github.com/bvaughn/react-virtualized/commit/2a387c5e98b6f929380c95b0d5f69b039176fcc5))
defaultWidth, defaultHeight will render twice as the [react docs](https://reactjs.org/docs/react-dom.html#hydrate) commented, but I think it's a reasonable solution.
@bvaughn

**Comment by bvaughn** [comment]
> If I set serverWidth and serverHeight, server and client have defferent initial width and height.
As a result, react prints a mismatch warning.

I understand your concern, and I think it's reasonable.

However, since it isn't possible to _know_ the size of the `window` on the server side, and any `style` attributes that reference it are bound to mismatch on the client- I'm also think it's reasonable to just ignore the mismatch warning.

As you've pointed out, you can work around this if you always require a second render- but I find that option kind of distasteful. And I think the API behavior you initially proposed for this is unintuitive, because props that begin with names like `default` are typically only used when the "real" value is not provided. In this case, the "real" value is the `window` measurements, which are available on the client.

This is why I named the props `serverHeight` and `serverWidth` (to avoid any potential ambiguity between expectations like mine about "default" props and expectations like yours.)

I believe it is also possible to accomplish this same thing in application code, with a wrapper component, (although I could see where you may not like this suggestion). For example, something like this:
```js
class ServerRenderingCompat extends Component {
  state = { hasMounted: false };

  componentDidMount() {
    this.setState({ hasMounted: true });
  }

  render() {
    const { children, initialHeight, initialWidth } = this.props;

    // If we have mounted (on the client) pass through the actual dimensions.
    // If we have not mounted (initial client render, or server render),
    // Override width and height with defaults so they will match.
    return this.state.hasMounted
      ? children(this.props)
      : children({
        ...this.props,
        height: this.props.initialHeight,
        width: this.props.initialWidth
      });
  }
}

ReactDOM.render(
  <WindowScroller>
    {props => (
      <ServerRenderingCompat
        {...props}
        initialWidth={400}
        initialHeight={800}
      >
        {({ height, isScrolling, registerChild, scrollTop }) => /* Your component here */}
      </ServerRenderingCompat>
    )}
  </WindowScroller>,
  document.getElementById('example')
);
```

If we hadn't already released the new props in [9.14.0](https://github.com/bvaughn/react-virtualized/blob/master/CHANGELOG.md#9140) I would consider renaming them to avoid my concerns about API confusion but...I think at this point it would just cause more churn. I don't think it's reasonable to use them for initial client rendering dimensions (because of their names) and I don't think they warrant a new major release, so... I suggest either ignoring the mismatch warning or using a decorator approach like I outlined above to ensure consistency between server and initial client render.

Thank you for creating the initial PR and for clearly outlining your concerns. I don't expect you to agree with the outcome of this issue, but I hope you understand my reasoning and concerns.

**Comment by landvibe** [comment]
I think there is no clear solution for SSR.
I agree with your dicision.

**Comment by bvaughn** [comment]
Thank you. I appreciate your saying so.
