### ISSUE TITLE
Support for some mouse events on the Table element itself

### ISSUE THREAD

**Issue by mkarajohn** [bvaughn/react-virtualized#912]
Would you ever consider adding (or accept a PR that adds) the option to pass an `onMouseEnter` and `onMouseLeave` handler on the outermost table DOM container (the `ReactVirtualized__Table` element)

My specific usecase is a table that holds a list of music tracks, which autoscrolls when the currently playing track from the list changes to another track from the list. 

I would like to negate this behaviour if the user has his mouse over the table, meaning he is in someway interacting with something inside the table.

I know what I am asking can easily be achieved by wrapping the `Table` component itself into a `div` and delegate the event handling to this `div`, but you know, why add extra markup for this when I have all the markup I need already there 😅

Sorry if there is already a way to do this with the current API, I looked as best as I could before opening this and also tried passing an `onMouseEnter` to a `Table` to see if it would work.

**Comment by bvaughn** [comment]
> I know what I am asking can easily be achieved by wrapping the Table component itself into a div and delegate the event handling to this div, but you know, why add extra markup for this when I have all the markup I need already there 😅

I understand your reluctance of adding extra wrapper elements, and I appreciate your being so candid about it!

I have a similar reluctance to add one-off event-handler props to components. Particularly with `Table` which has already had several `onRow*` props requested and added.

In this case, since there exists a relatively simple option to accomplish what you're looking for, even though it may not be ideal, I'm inclined to say you should use it. Hope you understand!
