### ISSUE TITLE
Slack channel down

### ISSUE THREAD

**Issue by wildlifehexagon** [bvaughn/react-virtualized#919]
Was going to ask a question in the Slack channel but the URL has the following error:

502 - An error occurred with your deployment

**Comment by borm** [comment]
Think project authors also forgot about us

**Comment by bvaughn** [comment]
Sounds like there was a Slack outage. Not specific to this project. Looks like it's back up now though.

**Comment by wildlifehexagon** [comment]
Still seeing the same error message at https://react-virtualized.now.sh/

**Comment by bvaughn** [comment]
Hm. I wonder if this is related to the recent Zeit outage.

The support channel is also accessible at [react-virtualized.slack.com](https://react-virtualized.slack.com/) but because of how Slack works, you'll need an invite to join initially. That's what the Now deployment handles, by using [rauchg/slackin](https://github.com/rauchg/slackin).

**Comment by bvaughn** [comment]
I've just re-deployed and it looks like it's up and working again. Thanks for correcting my initial misunderstanding, and sorry for the inconvenience!

**Comment by wildlifehexagon** [comment]
No worries, thanks for fixing it!
