### ISSUE TITLE
Newest version of MultiGrid does not fire onScrollbarPresenceChange

### ISSUE THREAD

**Issue by OleksandrNechai** [bvaughn/react-virtualized#977]
Here is  [code](https://codesandbox.io/s/0x2k95kjmw) I put together. MultiGrid for some reason does not fire onScrollbarPresenceChange callback. When I change MultiGrid --> Grid, this example works as expected.

**Comment by bvaughn** [comment]
`MultiGrid` has never supported `onScrollbarPresenceChange`. It isn't listed as a prop [in the documentation](https://github.com/bvaughn/react-virtualized/blob/master/docs/MultiGrid.md) either. That being said, adding it is pretty simple so I'll do that and push 9.18 really quick.

**Comment by bvaughn** [comment]
Added via 658767c

**Comment by OleksandrNechai** [comment]
Thanks for fast reply, Brian! 

This is a bit confusing :-). The docs say

> The majority of MultiGrid properties (eg cellRenderer) are relayed to all child Grids.

However `cellRenderer` is not listed in the docs as a prop of `MultiGrid `. So I decided that all `Grid` props are translated to MultiGrid as well, `onScrollbarPresenceChange` included. Plus I used `MultiGrid ` in my project wrapped in `AutoSizer` and `onScrollbarPresenceChange` [worked](https://codesandbox.io/s/jj0o33wp79). 

It's cool you have added this to `MultiGrid `, but this is multi grid :-). `onScrollbarPresenceChange` will report presence change for which of many grids? 

For example, in my project, I have a very weird problem when  `onScrollbarPresenceChange` is triggered for every grid in multigrid and final result is not good for me, because I do have a scrollbar in main grid, but  `onScrollbarPresenceChange` series finished on header grid which does not have a scrollbar. I did my best to reproduce it in codesandbox.io but failed.

**Comment by bvaughn** [comment]
> Plus I used `MultiGrid` in my project wrapped in `AutoSizer` and `onScrollbarPresenceChange` worked.

I didn't look at your second demo link. It's a Sunday afternoon and I'd rather relax and do stuff away from the keyboard. 😄 If it worked, it's probably due to the top, right `Grid` whereas the earlier demo you sent me was testing the bottom, right `Grid`.

The commit I linked to shows a hint at why this is. The `onScrollbarPresenceChange` prop wasn't being filtered out from the inner `Grid`s ([now it is](https://github.com/bvaughn/react-virtualized/blob/e0364f1760adf53858ef10955477d8a4c342d046/source/MultiGrid/MultiGrid.js#L260) _except_ for the bottom, right `Grid` ([which defined its own handler](https://github.com/bvaughn/react-virtualized/blob/e0364f1760adf53858ef10955477d8a4c342d046/source/MultiGrid/MultiGrid.js#L675) for unrelated purposes).

I don't have time to go into detail. (You can look through the Git history if you're interested.) But the condensed version is that- in my opinion- it really only makes sense for the bottom, right `Grid` scrollbar-event to be passed through, and as of 658767c, it now is.

Anyway, have a nice day.

**Comment by OleksandrNechai** [comment]
> it really only makes sense for the bottom, right Grid scrollbar-event to be passed through
Absolutely agree! Thanks! Have a nice Sunday away from the keyboard! :-)
