### ISSUE TITLE
When using CellMeasurer and List, changing passthrough props doesn't always update DOM row heights.

### ISSUE THREAD

**Issue by josephong** [bvaughn/react-virtualized#984]
I'm running into an issue where modifying a set of filters on an array of items displayed via a `List` with heights cached by `CellMeasurerCache` periodically causes incorrect row heights to appears, unless I call `recomputeRowHeights` on the reference for the list, or scroll the list.

In particular, the `CellMeasurerCache` has the correct heights for the items, but the style attributes on the rows aren't updating.

I've tried reading through the `Grid` code, and I see that some style object caching happens in the `defaultCellRangeRenderer`. https://github.com/bvaughn/react-virtualized/blob/17b6ff45d7d6c0d77523c73d48d880975489347c/source/Grid/defaultCellRangeRenderer.js#L61-L62

This style cache is cleared in certain places in `Grid`, relevantly in `recomputeGridSize`, which `recomputeRowHeights` relies on in: https://github.com/bvaughn/react-virtualized/blob/17b6ff45d7d6c0d77523c73d48d880975489347c/source/Grid/Grid.js#L489

I've noticed that it only clears when the rowHeight changes: https://github.com/bvaughn/react-virtualized/blob/17b6ff45d7d6c0d77523c73d48d880975489347c/source/Grid/Grid.js#L762-L766 but as the docs mentioned, this behavior is unreliable when using a function (in this case, CellMeasurerCache's rowHeight function). 

Is it a bug that the style cache isn't being cleared under the hood when passthrough props change? Calling `recomputeRowHeights` in every place where we'd modify data (sorting, filtering) for our tables leads to a bit of code pollution and less than ideal readability for new folks. Apologies if this is by design – I haven't grokked the codebase well enough to sense whether it's due to a performance constraint.

**Comment by josephong** [comment]
(I can try to reproduce this with a Plunkr when I have a bit more time if you think it's helpful, but I won't have access to a computer for a bit starting soon)

**Comment by bvaughn** [comment]
> In particular, the CellMeasurerCache has the correct heights for the items, but the style attributes on the rows aren't updating.

This is working as desired.

`CellMeasurerCache` caches _measurements and `List`/`Grid` caches _positions_. They're cached separately for a couple of reasons:
* Positions may change without measurements changing. For example, if items are added, removed, or rearranged within a list. In this case, positions can be re-calculated without requiring re-measurement which is good for performance.
* Positions are fast to calculate. Unlike size measurements, they don't require rendering or touching the DOM.

I try to make this clear in the docs for methods like `[recomputeRowHeights`](https://github.com/bvaughn/react-virtualized/blob/master/docs/List.md#recomputerowheights-index-number). If you think size has changed- then you need to explicitly let RV know to recompute its position cache. This is true if you provide your own `rowHeight` function _or_ if you're using `CellMeasurer`.

The only exception (in both cases) is the initial render, because `List` (or `Grid`) have not yet cached any position data. After that though, it's up to your app to let RV know when size may have changed. The only other option would be for `CellMeasurer` to always re-measure every time, and this would be very bad for performance.

**Comment by josephong** [comment]
Ah, I understand that the caching processes are different – I'm wondering why the position cache isn't flushed when pass-through props change. 

In this case, the CellMeasurerCache has the right values and doesn't need to be flushed, but it would be useful to automatically clear the position cache (which is much cheaper) so that any prop change affecting rows being filtered or sorted would automatically be reflected instead of having to manually call recomputeRowHeights. Is even that prohibitively expensive?

Sorry if this isn't a bug – perhaps it's more of a feature discussion (if it's too expensive to do automatically maybe exposing something to say, "call recompute on certain props changing"). I can move it to the appropriate place if you think that's the case.

**Comment by bvaughn** [comment]
> I'm wondering why the position cache isn't flushed when pass-through props change.

Why would it be? Passthrough props might have nothing to do with position cache. Clearing it every time would defeat much of the purpose of caching positions in the first place. I think it's best to leave this as an explicit thing for component authors to control.

**Comment by josephong** [comment]
Hm, okay, that makes sense. I was thinking perhaps exposing a way to specify certain props flushing the position cache (as a prop interface on the RV component). Though now I realized I can probably just do that check myself in `componentWillUpdate` as a clean pattern.

Thanks!

**Comment by bvaughn** [comment]
I think that's probably best.

I'm always open for proposals and suggestions though!
